apiVersion: v1
kind: Secret
metadata:
  name: gardener-discovery-server-tls
  namespace: {{ .Release.Namespace }}
  labels:
    app: gardener
    role: operator
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" | trunc 32 }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  tls.crt: {{ .Values.config.gardenerDiscoveryServer.tls.crt | b64enc }}
  tls.key: {{ .Values.config.gardenerDiscoveryServer.tls.key | b64enc }}
