apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- extension.yaml

patches:
- patch: |
    - op: replace
      path: /spec/deployment/admission/runtimeCluster/helm/ociRepository/ref
      value: europe-docker.pkg.dev/gardener-project/releases/charts/gardener/extensions/admission-calico-runtime:v1.50.0
    - op: replace
      path: /spec/deployment/admission/virtualCluster/helm/ociRepository/ref
      value: europe-docker.pkg.dev/gardener-project/releases/charts/gardener/extensions/admission-calico-application:v1.50.0
    - op: replace
      path: /spec/deployment/extension/helm/ociRepository/ref
      value: europe-docker.pkg.dev/gardener-project/releases/charts/gardener/extensions/networking-calico:v1.50.0
  target:
    version: v1alpha1
    group: operator.gardener.cloud
    kind: Extension
    name: networking-calico
