{
 "title": "Kubernetes API Server Details",
 "tags": [
  "seed",
  "controlplane"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "verbs",
    "label": "Verbs",
    "query": "DELETE,PUT,POST,DELETECOLLECTION,WATCH,GET,LIST,PATCH,CONNECT,UPDATE,CREATE"
   },
   { "name": "rate", "label": "Rate", "query": "1m,3m,5m" }
  ]
 },
 "panels": [
  {
   "title": "Overall API Server Request Rates",
   "type": "graph",
   "description": "Shows the rate of all API server requests.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "requests/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total[$rate]))",
     "legendFormat": "Request Rate"
    }
   ]
  },
  {
   "title": "API Server Request Latency",
   "type": "graph",
   "description": "Shows the request latency of each verb for the API server.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "sum by(verb) (rate(apiserver_latency_seconds:quantile{verb=~\"$verbs\"}[$rate]) >= 0)",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "API Server Request Rates Per Verb",
   "type": "graph",
   "description": "Shows the request rate per verb for the API server.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "requests/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{verb=~\"$verbs\"}[$rate])) by(verb)",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "API Server Request Rates Per Verb (Avg)",
   "type": "graph",
   "description": "Shows the average rate of requests to the API server.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "requests/s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(apiserver_request_total{verb=~\"$verbs\"}[$rate])) by (verb)",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "API Server Request Rates Per Scope",
   "type": "graph",
   "description": "Shows the request rate per scope for the API server.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "requests/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total[$rate])) by(scope)",
     "legendFormat": "{{scope}}-scope"
    }
   ]
  },
  {
   "title": "API Server Request Rates Per Resource",
   "type": "graph",
   "description": "Shows the request rate per resource for the API server.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "requests/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total[$rate])) by(resource)",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "API Server Request Rates Per Verb And Resource",
   "type": "graph",
   "description": "Shows the request rate per verb and resource for the API server.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "requests/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{verb=~\"$verbs\"}[$rate])) by(resource,verb,subresource)",
     "legendFormat": "{{verb}}/{{resource}}/{{subresource}}"
    }
   ]
  }
 ]
}