{
 "title": "Kubernetes Deployments",
 "tags": [
  "kubernetes",
  "seed",
  "shoot"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "type", "label": "Type", "query": "seed,shoot" },
   {
    "name": "deployment_name",
    "label": "Deployment",
    "query": "label_values(kube_deployment_metadata_generation{type=~\"$type\"}, deployment)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"$deployment_name.*\"}[$__rate_interval])) "
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"$deployment_name.*\"}) / 1024^3"
    }
   ]
  },
  {
   "title": "Network",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod=~\"$deployment_name.*\"}[$__rate_interval])) + sum(rate(container_network_receive_bytes_total{pod=~\"$deployment_name.*\"}[$__rate_interval])) "
    }
   ]
  },
  {
   "title": "Desired Replicas",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(kube_deployment_spec_replicas{instance=\"kube-state-metrics\",deployment=\"$deployment_name\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Available Replicas",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(kube_deployment_status_replicas_available{instance=\"kube-state-metrics\",deployment=\"$deployment_name\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Observed Generation",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(kube_deployment_status_observed_generation{instance=\"kube-state-metrics\",deployment=\"$deployment_name\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Metadata Generation",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(kube_deployment_metadata_generation{instance=\"kube-state-metrics\",deployment=\"$deployment_name\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(kube_deployment_status_replicas{deployment=\"$deployment_name\"}) without (instance, pod)",
     "legendFormat": "current replicas"
    },
    {
     "expr": "min(kube_deployment_status_replicas_available{deployment=\"$deployment_name\"}) without (instance, pod)",
     "legendFormat": "available"
    },
    {
     "expr": "max(kube_deployment_status_replicas_unavailable{deployment=\"$deployment_name\"}) without (instance, pod)",
     "legendFormat": "unavailable"
    },
    {
     "expr": "min(kube_deployment_status_replicas_updated{deployment=\"$deployment_name\"}) without (instance, pod)",
     "legendFormat": "updated"
    },
    {
     "expr": "max(kube_deployment_spec_replicas{deployment=\"$deployment_name\"}) without (instance, pod)",
     "legendFormat": "desired"
    }
   ]
  },
  {
   "title": "Drill down to Pod Dashboard",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "kube_pod_info{created_by_kind=\"ReplicaSet\",created_by_name=~\"$deployment_name-.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}