{
 "title": "Node/Worker Pool Overview",
 "tags": [
  "workload",
  "shoot"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "worker_group",
    "label": "Worker Group",
    "query": "label_values(kube_node_labels, label_worker_garden_sapcloud_io_group)"
   }
  ]
 },
 "panels": [
  {
   "title": "Average CPU Usage of Nodes in Worker Group(s) $worker_group",
   "type": "graph",
   "description": "Shows the average CPU usage of all nodes in the selected worker group(s).",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "avg(sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m])) by (node) + on (node) group_right sum(kube_node_labels{label_worker_garden_sapcloud_io_group=~\"$worker_group\"}) by (label_worker_garden_sapcloud_io_group, node) - 1) by (label_worker_garden_sapcloud_io_group)",
     "legendFormat": "{{label_worker_garden_sapcloud_io_group}}"
    }
   ]
  },
  {
   "title": "Average Memory Usage of Nodes in Worker Group(s) $worker_group",
   "type": "graph",
   "description": "Shows the memory usage of all nodes in the selected worker group(s).",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "avg(sum(node_memory_Active_bytes) by (node) + on (node) group_right sum(kube_node_labels{label_worker_garden_sapcloud_io_group=~\"$worker_group\"}) by (label_worker_garden_sapcloud_io_group, node) - 1) by (label_worker_garden_sapcloud_io_group)",
     "legendFormat": "{{label_worker_garden_sapcloud_io_group}}"
    }
   ]
  },
  {
   "title": "Number of Nodes in Worker Group(s) $worker_group",
   "type": "graph",
   "description": "Shows the number of nodes of selected worker groups in the cluster over time.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(sum(kube_node_info) by (node) + on (node) group_right sum(kube_node_labels{label_worker_garden_sapcloud_io_group=~\"$worker_group\"}) by (label_worker_garden_sapcloud_io_group, node))",
     "legendFormat": "nodes"
    }
   ]
  },
  {
   "title": "Average # of Pods on each Node in Worker Group(s) $worker_group",
   "type": "graph",
   "description": "Shows the average number of pods running on each node of the selected worker group(s).",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "Pods" }
   ],
   "targets": [
    {
     "expr": "avg(sum(kube_pod_info{type=\"shoot\"}) by (node) + on (node) group_right sum(kube_node_labels{label_worker_garden_sapcloud_io_group=~\"$worker_group\"}) by (label_worker_garden_sapcloud_io_group, node)) by (label_worker_garden_sapcloud_io_group)",
     "legendFormat": "{{label_worker_garden_sapcloud_io_group}}"
    }
   ]
  },
  {
   "title": "Overview of all Nodes",
   "type": "table",
   "description": "Shows an overview of all nodes in the shoot cluster.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[1m])) by (node) + on (node) group_right sum(kube_node_labels{label_worker_garden_sapcloud_io_group=~\"$worker_group\"}) by (label_worker_garden_sapcloud_io_group, node) - 1"
    },
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores) by (node) + on (node) group_right sum(kube_node_labels{label_worker_garden_sapcloud_io_group=~\"$worker_group\"}) by (label_worker_garden_sapcloud_io_group, node) - 1"
    },
    {
     "expr": "(sum(kube_node_status_allocatable_cpu_cores) by (node) - sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m])) by (node)) + on (node) group_right sum(kube_node_labels{label_worker_garden_sapcloud_io_group=~\"$worker_group\"}) by (label_worker_garden_sapcloud_io_group, node) - 1"
    },
    {
     "expr": "sum(node_memory_Active_bytes) by (node) + on (node) group_right sum(kube_node_labels{label_worker_garden_sapcloud_io_group=~\"$worker_group\"}) by (label_worker_garden_sapcloud_io_group, node) - 1"
    },
    {
     "expr": "sum(kube_node_status_allocatable_memory_bytes) by (node) + on (node) group_right sum(kube_node_labels{label_worker_garden_sapcloud_io_group=~\"$worker_group\"}) by (label_worker_garden_sapcloud_io_group, node) - 1"
    },
    {
     "expr": "(sum(kube_node_status_allocatable_memory_bytes) by (node) - sum(node_memory_Active_bytes) by (node)) + on (node) group_right sum(kube_node_labels{label_worker_garden_sapcloud_io_group=~\"$worker_group\"}) by (label_worker_garden_sapcloud_io_group, node) - 1"
    },
    {
     "expr": "sum(kube_pod_info{type=\"shoot\"}) by (node) + on (node) group_right sum(kube_node_labels{label_worker_garden_sapcloud_io_group=~\"$worker_group\"}) by (label_worker_garden_sapcloud_io_group, node)"
    }
   ]
  }
 ]
}