{
 "title": "Seed Overload",
 "tags": [
  "seed",
  "controlplane",
  "apiserver-details",
  "monitoring"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Api-server  Overload", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"kube-apiserver.*\"}) / 1024^3"
    }
   ]
  },
  { "title": "ETCD Overload", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Memory usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"etcd-main.*\"}) / 1024^3"
    }
   ]
  },
  {
   "title": "Client Traffic (In + out)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{pod=~\"etcd-main.*\"}[$__rate_interval]) + rate(container_network_receive_bytes_total{pod=~\"etcd-main.*\"}[$__rate_interval]) ",
     "legendFormat": "{{pod}} Client Traffic In"
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "etcd_mvcc_db_total_size_in_bytes{role=\"main\"}",
     "legendFormat": "{{pod}} DB Size"
    }
   ]
  },
  { "title": "Nodes Overload", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Number of Nodes in Worker Group(s) All",
   "type": "gauge",
   "description": "Shows the number of nodes of selected worker groups in the cluster over time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_labels{label_worker_gardener_cloud_pool=~\"local\"}) by (label_worker_gardener_cloud_pool)",
     "legendFormat": "{{label_worker_gardener_cloud_pool}}"
    }
   ]
  },
  { "title": "Resource Quotas Overload", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Configmaps count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(apiserver_storage_objects{resource=\"configmaps\"}) by (resource)"
    }
   ]
  }
 ]
}