{
 "title": "Shoot Node Details",
 "description": "Shoot Node stats",
 "tags": [
  "kubernetes",
  "shoot",
  "workload"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "label_values(kube_node_info{type=\"shoot\"}, node)"
   },
   { "name": "rate", "query": "1m,3m,5m" }
  ]
 },
 "panels": [
  { "title": "Node Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pods",
   "type": "gauge",
   "description": "How many pods are currently running on node $Node.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(kube_pod_info{type=\"shoot\", node=~\"$Node\"})"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "description": "Shows how much percent of the CPU is being used on the node $Node.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\", node=~\"$Node\"}[$rate])) / sum(kube_node_status_allocatable_cpu_cores{node=~\"$Node\"}) * 100"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "gauge",
   "description": "Shows how much percent of the memory is being used on the node $Node.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum(node_memory_Active_bytes{node=~\"$Node\"}) / sum(kube_node_status_allocatable_memory_bytes{node=~\"$Node\"}) * 100"
    }
   ]
  },
  {
   "title": "Pods ($Node)",
   "type": "graph",
   "description": "Shows how many pods can be allocated onto this node and how many are currently on this node.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "Pods" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_pods{node=~\"$Node\"})",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "sum(kube_pod_info{type=\"shoot\", node=~\"$Node\"})",
     "legendFormat": "Pods"
    }
   ]
  },
  {
   "title": "Node CPU Usage ($Node)",
   "type": "graph",
   "description": "Shows a node's CPU usage over time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\", node=~\"$Node\"}[$rate]))",
     "legendFormat": "CPU"
    },
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores{node=~\"$Node\"})",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores{node=~\"$Node\"}) - sum(rate(node_cpu_seconds_total{mode!=\"idle\", node=~\"$Node\"}[$rate]))",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Node Memory Usage ($Node)",
   "type": "graph",
   "description": "Shows a node's memory usage over time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_Active_bytes{node=~\"$Node\"})",
     "legendFormat": "Current"
    },
    {
     "expr": "sum(kube_node_status_allocatable_memory_bytes{node=~\"$Node\"})",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "sum(kube_node_status_allocatable_memory_bytes{node=~\"$Node\"}) - sum(node_memory_Active_bytes{node=~\"$Node\"})",
     "legendFormat": "Unused"
    }
   ]
  },
  {
   "title": "Node Filesystem ($Node)",
   "type": "graph",
   "description": "Shows the size of the node's filesystem, how much space is free and how much space is available to non-root users.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{mountpoint=\"/\",node=~\"$Node\"})",
     "legendFormat": "Size"
    },
    {
     "expr": "sum(node_filesystem_free_bytes{mountpoint=\"/\",node=~\"$Node\"})",
     "legendFormat": "Free"
    },
    {
     "expr": "sum(node_filesystem_avail_bytes{mountpoint=\"/\",node=~\"$Node\"})   ",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Network I/O pressure ($Node)",
   "type": "graph",
   "description": "Shows the node's network I/O pressure.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{kubernetes_io_hostname=~\"^$Node$\",type=\"shoot\"}[${rate}]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{kubernetes_io_hostname=~\"^$Node$\",type=\"shoot\"}[${rate}]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "System Services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "System services CPU usage (${rate} avg)",
     "type": "graph",
     "description": "Shows the CPU usage of all system services running on node $Node.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "none", "label": "Cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{systemd_service_name!=\"\",kubernetes_io_hostname=~\"^$Node$\"}[${rate}])) by (systemd_service_name)",
       "legendFormat": "{{ systemd_service_name }}"
      },
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{systemd_service_name!=\"\",kubernetes_io_hostname=~\"^$Node$\"}[${rate}]))",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "System services Memory usage",
     "type": "graph",
     "description": "Shows the Memory usage of all system services running on node $Node.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "bytes", "label": "Cores" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{systemd_service_name!=\"\",kubernetes_io_hostname=~\"^$Node$\"}) by (systemd_service_name)",
       "legendFormat": "{{ systemd_service_name }}"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{systemd_service_name!=\"\",kubernetes_io_hostname=~\"^$Node$\"})",
       "legendFormat": "total"
      }
     ]
    }
   ]
  }
 ]
}