// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apissecurityv1alpha1 "github.com/gardener/gardener/pkg/apis/security/v1alpha1"
	versioned "github.com/gardener/gardener/pkg/client/security/clientset/versioned"
	internalinterfaces "github.com/gardener/gardener/pkg/client/security/informers/externalversions/internalinterfaces"
	securityv1alpha1 "github.com/gardener/gardener/pkg/client/security/listers/security/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// CredentialsBindingInformer provides access to a shared informer and lister for
// CredentialsBindings.
type CredentialsBindingInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() securityv1alpha1.CredentialsBindingLister
}

type credentialsBindingInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewCredentialsBindingInformer constructs a new informer for CredentialsBinding type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCredentialsBindingInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCredentialsBindingInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredCredentialsBindingInformer constructs a new informer for CredentialsBinding type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCredentialsBindingInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SecurityV1alpha1().CredentialsBindings(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SecurityV1alpha1().CredentialsBindings(namespace).Watch(context.TODO(), options)
			},
		},
		&apissecurityv1alpha1.CredentialsBinding{},
		resyncPeriod,
		indexers,
	)
}

func (f *credentialsBindingInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCredentialsBindingInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *credentialsBindingInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apissecurityv1alpha1.CredentialsBinding{}, f.defaultInformer)
}

func (f *credentialsBindingInformer) Lister() securityv1alpha1.CredentialsBindingLister {
	return securityv1alpha1.NewCredentialsBindingLister(f.Informer().GetIndexer())
}
