apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- patch: |-
    - op: add
      path: /nodes/0/extraPortMappings/-
      value:
        containerPort: 30003
        hostPort: 443
        listenAddress: fd00:ff::4
    - op: add
      path: /nodes/0/extraPortMappings/-
      value:
        containerPort: 31443
        hostPort: 443
        listenAddress: fd00:ff::3
  target:
    group: kind.x-k8s.io
    kind: Cluster
    name: local
