{
 "title": "NodeLocalDNS",
 "tags": [
  "network",
  "shoot"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "NodeLocalDNS Pod",
    "query": {
     "query": "label_values(coredns_build_info, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "DNS Requests (Packets per Second)",
   "type": "graph",
   "description": "Average rate of DNS requests (in packets per second) split by DNS record types, used protocol and DNS zone.\n\nNote: The `dot` zone is the local zone managed by the NodeLocalDNS instance.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_request_duration_seconds_count{pod=~\"$pod\"}[$__rate_interval])) by (type)",
     "legendFormat": "By Record: {{type}}"
    },
    {
     "expr": "sum(rate(coredns_dns_request_duration_seconds_count{pod=~\"$pod\"}[$__rate_interval])) by (proto)",
     "legendFormat": "By Protocol: {{proto}}"
    },
    {
     "expr": "sum(rate(coredns_dns_request_duration_seconds_count{pod=~\"$pod\"}[$__rate_interval])) by (zone)",
     "legendFormat": "By Zone: {{zone}}"
    }
   ]
  },
  {
   "title": "DNS Requests (Packets)",
   "type": "graph",
   "description": "Rate of DNS Requests received by NodeLocalDNS.\n\nNote: The `dot` zone is the local zone managed by the NodeLocalDNS instance.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "packets" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total{pod=~\"$pod\"}[$__rate_interval])) by (type)",
     "legendFormat": "By Record: {{type}}"
    },
    {
     "expr": "sum(rate(coredns_dns_requests_total{pod=~\"$pod\"}[$__rate_interval])) by (proto)",
     "legendFormat": "By Protocol: {{proto}}"
    },
    {
     "expr": "sum(rate(coredns_dns_requests_total{pod=~\"$pod\"}[$__rate_interval])) by (zone)",
     "legendFormat": "By Zone: {{zone}}"
    }
   ]
  },
  {
   "title": "DNS Lookup Responses (Per Second)",
   "type": "graph",
   "description": "The average per second rate of lookup requests split by their status codes (rcode).",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(coredns_dns_responses_total{pod=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{rcode}}"
    }
   ]
  },
  {
   "title": "DNS Lookup Responses",
   "type": "graph",
   "description": "Lookup requests split by their status codes (rcode).",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(coredns_dns_responses_total{pod=~\"$pod\"} - coredns_dns_responses_total{pod=~\"$pod\"} offset $__interval) by (rcode)",
     "legendFormat": "{{rcode}}"
    }
   ]
  },
  {
   "title": "DNS Requests Latency (In Seconds)",
   "type": "graph",
   "description": "DNS Requests Latency in seconds",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum(rate(coredns_dns_request_duration_seconds_bucket{pod=~\"$pod\"}[$__rate_interval])) by (le,type))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "DNS Requests Latency Heatmap",
   "type": "heatmap",
   "description": "DNS Requests Latency in seconds",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum by (le) (rate(coredns_dns_request_duration_seconds_bucket{pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Cache Hits and Misses (Per Second)",
   "type": "graph",
   "description": "The `cache hits` describes how many DNS requests were answered due to a cached entry.\n\nThe `cache misses` describes how much DNS requests need to be looked up, because the requests entry does not exist in the local cache.\n\nThe rates are per second averages and displayed in packets per second.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(coredns_cache_hits_total{pod=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "cache hits"
    },
    {
     "expr": "rate(coredns_cache_misses_total{pod=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "cache misses"
    }
   ]
  },
  {
   "title": "Cache Hits and Misses",
   "type": "graph",
   "description": "The `cache hits` describes how many DNS requests were answered due to a cached entry.\n\nThe `cache misses` describes how much DNS requests need to be looked up, because the requests entry does not exist in the local cache.\n\n",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(coredns_cache_hits_total{pod=~\"$pod\"} - coredns_cache_hits_total{pod=~\"$pod\"} offset $__interval)",
     "legendFormat": "cache hits"
    },
    {
     "expr": "sum(coredns_cache_misses_total{pod=~\"$pod\"} - coredns_cache_misses_total{pod=~\"$pod\"} offset $__interval)",
     "legendFormat": "cache misses"
    }
   ]
  },
  {
   "title": "Cache Size",
   "type": "graph",
   "description": "Count of cached entries in the cache of the DNS.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(coredns_cache_entries{pod=~\"$pod\"}) by (type)",
     "legendFormat": "cache size: {{ type }}"
    }
   ]
  },
  { "title": "Upstream DNS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Upstream DNS Requests Per Interval",
   "type": "graph",
   "description": "Request per interval  to upstream DNS.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(coredns_forward_requests_total{pod=~\"$pod\"} - coredns_forward_requests_total{pod=~\"$pod\"} offset $__interval) by (to)",
     "legendFormat": "{{to}}"
    }
   ]
  },
  {
   "title": "Upstream DNS Requests",
   "type": "graph",
   "description": "Average request (packets per second) rate made to upstream DNS.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_forward_requests_total{pod=~\"$pod\"}[$__rate_interval])) by (to)",
     "legendFormat": "{{to}}"
    }
   ]
  },
  {
   "title": "Upstream DNS Forward Responses Per Interval",
   "type": "graph",
   "description": "DNS forward responses per interval from upstream DNS split by status code (rcode).",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(coredns_forward_responses_total{pod=~\"$pod\"} - coredns_forward_responses_total{pod=~\"$pod\"} offset $__interval) by (to,rcode)",
     "legendFormat": "{{rcode}}  ({{to}})"
    }
   ]
  },
  {
   "title": "Upstream DNS Responses",
   "type": "graph",
   "description": "Average per second rate of responses from upstream DNS split by status code (rcode).",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(coredns_forward_responses_total{pod=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{rcode}} ({{to}})"
    }
   ]
  },
  {
   "title": "Node Cache Errors",
   "type": "graph",
   "description": "Number of errors occurred during node cache operation",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_nodecache_setup_errors_total{pod=~\"$pod\"}[$__rate_interval])) by (errortype)",
     "legendFormat": "Type: {{errortype}}"
    }
   ]
  }
 ]
}