apiVersion: v1
data:
  data.yaml.br: G5UEAOTZNI9RpB4udR/kD/dqxXfQsaBjDp1LB6odVgWyna0aeAJRNH18ekAZ6Ntmg6BPNAYrVOep/VxlJl5PCRSc0iRjEWp9ueQXbm8z1xa2GNp6yAUfXV1ObPpYp1DWgdbB+AKIU2PmA0RM3AXx1XQihcKyLHm4TCcFgG8TILwlYp5/Pu4p6aws66EUVgS4xCxAmHiNN6rYJ4yi4bfEfQbESWdbp0wJkIgezT0WfLLjvEcWaaCbpUO+Dj52Gm75RXRS7+osCTe4hZtOqWi91GVsdPW8oz5hQJMwJJb5/7w5psEskb/aVGTjPnNn5cxbzG8rZ8ftCa/DbVoU4+9wWAiICPzH3qtu/nEo3QiZ9tFCG9Ha2jADiOE3hHY8T9AYwgTjaONPlPrexXw030DBdk2Vcur1vkHEChTG7bEoU78FeMxaRnjvR7l2Wib41pvQhCQ=
immutable: true
kind: Secret
metadata:
  creationTimestamp: "2025-11-10T21:13:51Z"
  labels:
    resources.gardener.cloud/garbage-collectable-reference: "true"
  name: managedresource-logging-target-60f5ba46
  namespace: shoot--inventory--inv-dev-01
  resourceVersion: "4841844502"
  uid: 73fc78ed-d386-4795-a721-030c0847c4bb
type: Opaque
