// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/gardener/gardener/pkg/apis/seedmanagement/v1alpha1"
	seedmanagementv1alpha1 "github.com/gardener/gardener/pkg/client/seedmanagement/clientset/versioned/typed/seedmanagement/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeManagedSeedSets implements ManagedSeedSetInterface
type fakeManagedSeedSets struct {
	*gentype.FakeClientWithList[*v1alpha1.ManagedSeedSet, *v1alpha1.ManagedSeedSetList]
	Fake *FakeSeedmanagementV1alpha1
}

func newFakeManagedSeedSets(fake *FakeSeedmanagementV1alpha1, namespace string) seedmanagementv1alpha1.ManagedSeedSetInterface {
	return &fakeManagedSeedSets{
		gentype.NewFakeClientWithList[*v1alpha1.ManagedSeedSet, *v1alpha1.ManagedSeedSetList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("managedseedsets"),
			v1alpha1.SchemeGroupVersion.WithKind("ManagedSeedSet"),
			func() *v1alpha1.ManagedSeedSet { return &v1alpha1.ManagedSeedSet{} },
			func() *v1alpha1.ManagedSeedSetList { return &v1alpha1.ManagedSeedSetList{} },
			func(dst, src *v1alpha1.ManagedSeedSetList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ManagedSeedSetList) []*v1alpha1.ManagedSeedSet {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.ManagedSeedSetList, items []*v1alpha1.ManagedSeedSet) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
