networks:
  kind:
    external: true

x-machine: &machine
  image: ${GIND_MACHINE_IMAGE:-gind-machine:local}
  pull_policy: never
  build:
    context: ../../pkg/provider-local/machine-provider/node
    dockerfile: Dockerfile
  entrypoint: /init-machine-state.sh
  environment:
    PATH: /gardenadm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    IMAGEVECTOR_OVERWRITE: /gardenadm/imagevector-overwrite.yaml
    IMAGEVECTOR_OVERWRITE_CHARTS: /gardenadm/imagevector-overwrite-charts.yaml
  privileged: true
  security_opt:
  - seccomp=unconfined
  - apparmor=unconfined
  tmpfs:
  - /tmp
  - /run
  volumes:
  - /lib/modules:/lib/modules:ro
  - ./init-machine-state.sh:/init-machine-state.sh:ro
  - ../infra/resolv.conf:/etc/resolv.conf
  - /var/run/docker.sock:/var/run/docker.sock
  - /gardenadm
  - ../../dev/local-backupbuckets:/etc/gardener/local-backupbuckets
  - /var/lib/containerd
  - /mnt/data
  networks:
    kind: {}

services:
  apiserver-lb:
    image: envoyproxy/envoy:v1.38.0
    container_name: gind-apiserver-lb
    ports:
    - "172.18.255.123:443:443"
    volumes:
    - ./envoy.yaml:/etc/envoy/envoy.yaml:ro
    command: ["envoy", "-c", "/etc/envoy/envoy.yaml"]
    depends_on:
    - machine-0
    networks:
      kind: {}

  # Machines are defined explicitly (instead of using `deploy.replicas`) because we want stable, predictable container
  # and host names (e.g. `gind-machine-0`) for usability/user experience, and for the envoy load balancer config.
  machine-0:
    <<: *machine
    container_name: gind-machine-0
    hostname: gind-machine-0
  machine-1:
    <<: *machine
    container_name: gind-machine-1
    hostname: gind-machine-1
  machine-2:
    <<: *machine
    container_name: gind-machine-2
    hostname: gind-machine-2
  machine-3:
    <<: *machine
    container_name: gind-machine-3
    hostname: gind-machine-3
