apiVersion: v1
kind: Secret
metadata:
  name: provider-local-image-names
  namespace: garden
  labels:
    gardener.cloud/role: resource-reference
type: Opaque
stringData:
  cloudcontrollermanager: "cloud-controller-manager-local"
  machinecontrollermanager: "machine-controller-manager-provider-local"
