// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"

	corev1beta1 "github.com/gardener/gardener/pkg/apis/core/v1beta1"
	scheme "github.com/gardener/gardener/pkg/client/core/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// BackupBucketsGetter has a method to return a BackupBucketInterface.
// A group's client should implement this interface.
type BackupBucketsGetter interface {
	BackupBuckets() BackupBucketInterface
}

// BackupBucketInterface has methods to work with BackupBucket resources.
type BackupBucketInterface interface {
	Create(ctx context.Context, backupBucket *corev1beta1.BackupBucket, opts v1.CreateOptions) (*corev1beta1.BackupBucket, error)
	Update(ctx context.Context, backupBucket *corev1beta1.BackupBucket, opts v1.UpdateOptions) (*corev1beta1.BackupBucket, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, backupBucket *corev1beta1.BackupBucket, opts v1.UpdateOptions) (*corev1beta1.BackupBucket, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*corev1beta1.BackupBucket, error)
	List(ctx context.Context, opts v1.ListOptions) (*corev1beta1.BackupBucketList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *corev1beta1.BackupBucket, err error)
	BackupBucketExpansion
}

// backupBuckets implements BackupBucketInterface
type backupBuckets struct {
	*gentype.ClientWithList[*corev1beta1.BackupBucket, *corev1beta1.BackupBucketList]
}

// newBackupBuckets returns a BackupBuckets
func newBackupBuckets(c *CoreV1beta1Client) *backupBuckets {
	return &backupBuckets{
		gentype.NewClientWithList[*corev1beta1.BackupBucket, *corev1beta1.BackupBucketList](
			"backupbuckets",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *corev1beta1.BackupBucket { return &corev1beta1.BackupBucket{} },
			func() *corev1beta1.BackupBucketList { return &corev1beta1.BackupBucketList{} },
		),
	}
}
