{
 "title": "Alerts",
 "tags": [
  "monitoring",
  "seed"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Project", "query": "label_values(ALERTS, project)" },
   {
    "name": "Shoot",
    "query": "label_values(ALERTS{project=~\"$Project\"}, name)"
   },
   { "name": "Severity", "query": "label_values(severity)" },
   { "name": "AlertState", "label": "Alert State", "query": "label_values(alertstate)" },
   { "name": "Alertname", "query": "label_values(alertname)" }
  ]
 },
 "panels": [
  { "title": "Active Alerts Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Firing Alerts",
   "type": "singlestat",
   "description": "Shows how many alerts are currently firing for shoots using this seed.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\"})"
    }
   ]
  },
  {
   "title": "Clusters with Firing Alerts",
   "type": "singlestat",
   "description": "Shows how many clusters have at least 1 firing alert.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count(ALERTS{alertstate=\"firing\"}) by (cluster))"
    }
   ]
  },
  {
   "title": "Pending Alerts",
   "type": "singlestat",
   "description": "Shows how many alerts are currently pending for shoots using this seed.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"pending\"})"
    }
   ]
  },
  {
   "title": "Clusters with Pending Alerts",
   "type": "singlestat",
   "description": "Shows how many clusters currently have at least 1 pending alert.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count(ALERTS{alertstate=\"pending\"}) by (cluster))"
    }
   ]
  },
  {
   "title": "% of Clusters with Alerts",
   "type": "gauge",
   "description": "Shows the percentage of clusters that have at least 1 firing or pending alert.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "count(count(ALERTS) by (cluster)) / sum(seed:active_shoots_total:sum) * 100"
    }
   ]
  },
  {
   "title": "Clusters Total",
   "type": "singlestat",
   "description": "Shows the total number of shoots with a control plane on this seed.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "seed:active_shoots_total:sum" }
   ]
  },
  {
   "title": "Active Alert Count ($Severity/$AlertState)",
   "type": "table",
   "description": "Shows the count of alerts with selected severity and alert state from all clusters.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "count(ALERTS{severity=~\"$Severity\", alertstate=~\"$AlertState\"}) by (alertname)"
    }
   ]
  },
  {
   "title": "Cluster Alerts ($Severity/$AlertState)",
   "type": "table",
   "description": "Shows all alerts that are currently active from the selected clusters, severity, and alert state.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "count(ALERTS{project=~\"$Project\",name=~\"$Shoot\", severity=~\"$Severity\", alertstate=~\"$AlertState\"}) by (alertname, project, name, severity, alertstate)"
    }
   ]
  },
  { "title": "Alerts by Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Cluster Alert Count ($Severity/$AlertState)",
   "type": "graph",
   "description": "Shows the number of ($Severity) alerts in Alert State ($AlertState) for the selected clusters.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Alerts" }
   ],
   "targets": [
    {
     "expr": "count(ALERTS{alertname=~\"$Alertname\", severity=~\"$Severity\", alertstate=~\"$AlertState\", project=~\"$Project\", name=~\"$Shoot\"}) by (name,project)",
     "legendFormat": "{{ project }}/{{ name }}"
    }
   ]
  },
  {
   "title": "Active Alerts ($Severity/$AlertState)",
   "type": "graph",
   "description": "Shows alerts that are/were active with the selected severity and alert state from the selected clusters. Includes the alertnames of the alerts.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(ALERTS{alertname=~\"$Alertname\", severity=~\"$Severity\", alertstate=~\"$AlertState\", project=~\"$Project\", name=~\"$Shoot\"}) by (alertname,project,name)",
     "legendFormat": "{{ alertname }}/{{ project }}/{{ name }}"
    }
   ]
  }
 ]
}