{
 "title": "Fluent Bit",
 "description": "Fluent-bit metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "pod", "label": "Pod", "query": { "query": "label_values(pod)" } },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(fluentbit_gardener_incoming_logs_total,host)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Fluent Bit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Input plugin total records",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(fluentbit_input_records_total{pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Input Plugin bytes/s",
   "type": "gauge",
   "description": "Average Input bytes processing rate of all fluent-bits.",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_input_bytes_total{pod=~\"$pod\"}[$__rate_interval])) by (name) / 1024  ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Output Plugin bytes/s",
   "type": "gauge",
   "description": "Output plugin bytes processing rate of all fluent-bits.",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_proc_bytes_total{pod=~\"$pod\"}[$__rate_interval])) by (name) /1024",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Output Plugin errors",
   "type": "gauge",
   "description": "Output plugin errors per name",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(fluentbit_output_errors_total{pod=~\"$pod\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Output Plugin dropped records",
   "type": "gauge",
   "description": "Output plugin dropped records per name",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(fluentbit_output_dropped_records_total{pod=~\"$pod\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Output Plugin total records",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(fluentbit_output_proc_records_total{pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Input Plugin records/s",
   "type": "timeseries",
   "description": "Input plugin records rate.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_input_records_total{pod=~\"$pod\"}[$__rate_interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Output Plugin records/s",
   "type": "timeseries",
   "description": "Output plugin records rate",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_proc_records_total{pod=~\"$pod\"}[$__rate_interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Input Plugin pods records/s",
   "type": "timeseries",
   "description": "Input records processing rate of all fluent-bits.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_input_records_total{pod=~\"$pod\"}[$__rate_interval])) by (pod, name)",
     "legendFormat": "{{ pod }}/{{name}}"
    }
   ]
  },
  {
   "title": "Output Plugin pods records/s",
   "type": "timeseries",
   "description": "Output records processing rate of all fluent-bits.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_proc_records_total{pod=~\"$pod\"}[$__rate_interval])) by (pod, name)",
     "legendFormat": "{{ pod }}/{{name}}"
    }
   ]
  },
  {
   "title": "Chunks in memory",
   "type": "timeseries",
   "description": "Fluent-bit chunks in memory",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "fluentbit_storage_mem_chunks{pod=~\"$pod\"}",
     "legendFormat": "mem-{{pod}}"
    }
   ]
  },
  {
   "title": "Chunks on filesystem",
   "type": "timeseries",
   "description": "Fluent-bit chunks on filesystem",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "fluentbit_storage_fs_chunks{pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Chunks on filesystem - up",
   "type": "timeseries",
   "description": "Chunks that are stored simultaneously in memory and in filesystem storage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "fluentbit_storage_fs_chunks_up{pod=~\"$pod\"}",
     "legendFormat": "up-{{pod}}"
    }
   ]
  },
  {
   "title": "Chunks on filesystem - down",
   "type": "timeseries",
   "description": "Chunks that are stored only on the filesystem ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "fluentbit_storage_fs_chunks_down{pod=~\"$pod\"}",
     "legendFormat": "down-{{pod}}"
    }
   ]
  },
  {
   "title": "Output Plugin",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total incoming records",
     "type": "stat",
     "description": "Output plugin input records",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(fluentbit_gardener_incoming_logs_total{pod=~\"$pod\",host=~\"$host\"})"
      }
     ]
    },
    {
     "title": "Total output records",
     "type": "stat",
     "description": "Total records send to output plugin clients",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(fluentbit_gardener_output_client_logs_total{pod=~\"$pod\",host=~\".+$host.+\"})"
      }
     ]
    },
    {
     "title": "Total sending clients",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 8, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (type)(fluentbit_gardener_clients_total{pod=~\"$pod\"})",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Total errors",
     "type": "stat",
     "description": "Total errors by output plugin",
     "gridPos": { "h": 5, "w": 3, "x": 14, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(fluentbit_gardener_errors_total{pod=~\"$pod\",host=~\"$host\"})"
      }
     ]
    },
    {
     "title": "Total dropped records",
     "type": "stat",
     "description": "Total records dropped by output plugin",
     "gridPos": { "h": 5, "w": 3, "x": 17, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(fluentbit_gardener_dropped_logs_total{pod=~\"$pod\",host=~\".*$host.*\"})"
      }
     ]
    },
    {
     "title": "Total OTel SDK exports",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 38 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(output_plugin_otel_sdk_exporter_log_exported_total{server_address=~\".+$host.*\"})"
      }
     ]
    },
    {
     "title": "Incoming records/s",
     "type": "timeseries",
     "description": "Output plugin incoming records rate",
     "gridPos": { "h": 8, "w": 13, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "rps" } },
     "targets": [
      {
       "expr": "sum(rate(fluentbit_gardener_incoming_logs_total{pod=~\"$pod\",host=~\"$host\"}[$__rate_interval])) by (host)",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Output records/s",
     "type": "timeseries",
     "description": "Output plugin record rate",
     "gridPos": { "h": 8, "w": 11, "x": 13, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "rps" } },
     "targets": [
      {
       "expr": "sum(rate(fluentbit_gardener_output_client_logs_total{pod=~\"$pod\",host=~\".+$host.*\"}[$__rate_interval])) by (host)",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "DQue current size",
     "type": "timeseries",
     "description": "Dque current buffer size",
     "gridPos": { "h": 8, "w": 13, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "fluentbit_gardener_dque_size{pod=~\"$pod\",name=~\"$host\"}",
       "legendFormat": "{{pod}}/{{name}}"
      }
     ]
    },
    {
     "title": "DQue buffered records",
     "type": "timeseries",
     "description": "DQue  records persisted on the filesystem.",
     "gridPos": { "h": 8, "w": 11, "x": 13, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (host)(fluentbit_gardener_buffered_logs{pod=~\"$pod\",host=~\"$host\"})"
      }
     ]
    },
    {
     "title": "Exported records/s",
     "type": "timeseries",
     "description": "Output plugin exported records rate",
     "gridPos": { "h": 8, "w": 13, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (host)(rate(fluentbit_gardener_exported_client_logs_total{pod=~\"$pod\",host=~\"$host\"}[$__rate_interval]))",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Throttled records/s",
     "type": "timeseries",
     "description": "Logs throttled by output plugin clients",
     "gridPos": { "h": 8, "w": 11, "x": 13, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (host) (rate(fluentbit_gardener_throttled_logs_total{pod=~\"$pod\",host=~\"$host\"}[$__rate_interval]))",
       "legendFormat": "{{host}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Output Plugin Go Runtime & Process Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "[Process] CPU Usage",
     "type": "timeseries",
     "description": "Total user and system CPU time spent in seconds.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "[Process] Memory Usage",
     "type": "timeseries",
     "description": "Process memory usage - resident and virtual",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{pod=~\"$pod\"}",
       "legendFormat": "{{pod}} - resident memory"
      }
     ]
    },
    {
     "title": "[Process] Network I/O Rate",
     "type": "timeseries",
     "description": "Network bytes sent and received",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(process_network_transmit_bytes_total{pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "{{pod}} - TX"
      },
      {
       "expr": "rate(process_network_receive_bytes_total{pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "{{pod}} - RX"
      }
     ]
    },
    {
     "title": "[Go] Heap memory in-use",
     "type": "timeseries",
     "description": "Memory allocated in heap and currently in use",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memstats_heap_inuse_bytes{pod=~\"$pod\"}",
       "legendFormat": "{{pod}} - heap in use"
      }
     ]
    },
    {
     "title": "[Go] GC average duration",
     "type": "timeseries",
     "description": "GC average duration",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "\nsum by (pod) (\n  rate(go_gc_duration_seconds_sum{pod=~\"fluent-bit.+\"}[$__rate_interval])\n)\n/\nsum by (pod) (\n  rate(go_gc_duration_seconds_count{pod=~\"fluent-bit.+\"}[$__rate_interval])\n)\n",
       "legendFormat": "{{pod}} - GC avg"
      }
     ]
    },
    {
     "title": "[Go] Heap allocation/free rate",
     "type": "timeseries",
     "description": "Heap object allocation/free rates ",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(go_memstats_mallocs_total{pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "{{pod}} - alloc rate"
      },
      {
       "expr": "rate(go_memstats_frees_total{pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "{{pod}} - free rate"
      }
     ]
    }
   ]
  },
  {
   "title": "OTLP Exporter Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total created records",
     "type": "stat",
     "description": "OTel exporter created records",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (output_plugin_otel_sdk_log_created_total{pod=~\"$pod\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Current in-flight records",
     "type": "gauge",
     "description": "Records not yet exported",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (\n  output_plugin_otel_sdk_exporter_log_inflight{server_address=~\".+$host.+\"}\n)",
       "legendFormat": "{{server_address}}"
      }
     ]
    },
    {
     "title": "Records throughput /s",
     "type": "timeseries",
     "description": "Otel exporter records throughput",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (server_address) (  rate(output_plugin_otel_sdk_exporter_log_exported_total{server_address=~\".+$host.+\"}[$__rate_interval]))",
       "legendFormat": "{{server_address}}"
      }
     ]
    },
    {
     "title": "Export duration P50",
     "type": "timeseries",
     "description": "OTLP Exporter Duration 50 percentile",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50,sum by (le, server_address) (    rate(output_plugin_otel_sdk_exporter_operation_duration_seconds_bucket{server_address=~\".+$host.+\"}[$__rate_interval])))",
       "legendFormat": "{{server_address}} - p50"
      }
     ]
    },
    {
     "title": "Network Throughput b/s",
     "type": "timeseries",
     "description": "Network throughput for gRPC communication",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(output_plugin_rpc_client_request_size_bytes_sum{pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "{{pod}} - request bytes/sec"
      }
     ]
    },
    {
     "title": "Latency per rpc status code",
     "type": "timeseries",
     "description": "OTLP Exporter latency per status code",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (rpc_response_status_code,server_address) (rate(output_plugin_otel_sdk_exporter_operation_duration_seconds_count{server_address=~\".+$host.+\"}[$__rate_interval]))",
       "legendFormat": "{{server_address}} - {{rpc_response_status_code}}"
      }
     ]
    },
    {
     "title": "RPC call Rate",
     "type": "timeseries",
     "description": "RPC call rate per second",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(output_plugin_rpc_client_call_duration_seconds_count{pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "{{pod}} - {{rpc_method}}"
      }
     ]
    },
    {
     "title": "Export errors",
     "type": "timeseries",
     "description": "OTLP Exporter rpc error rate",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
     "targets": [
      {
       "expr": "sum by (rpc_response_status_code, server_address) (\n  rate(output_plugin_otel_sdk_exporter_operation_duration_seconds_count{rpc_response_status_code!=\"OK\",rpc_response_status_code=~\".+\",server_address=~\".+$host.+\"}[$__rate_interval])\n)",
       "legendFormat": "{{server_address}} - {{rpc_response_status_code}}"
      }
     ]
    }
   ]
  }
 ]
}