{
 "title": "Gardener resource usage by owner and container",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(metering:working_set_memory:sum_by_namespace{shoot_uid=\"\"}, namespace)"
    }
   },
   {
    "name": "owner",
    "query": {
     "query": "label_values(metering:working_set_memory:sum_by_namespace_owner_container{shoot_uid=\"\",namespace=~\"$namespace\"}, owner)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(metering:working_set_memory:sum_by_namespace_owner_container{shoot_uid=\"\",namespace=~\"$namespace\",owner=~\"$owner\"}, container)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "CPU" }
   ],
   "targets": [
    {
     "expr": "metering:cpu_usage:sum_by_namespace{shoot_uid=\"\",namespace=~\"$namespace\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "metering:cpu_usage:sum_by_namespace_owner_container{shoot_uid=\"\",namespace=~\"$namespace\",owner=~\"$owner\",container=~\"$container\"}",
     "legendFormat": "{{owner}} / {{container}}"
    }
   ]
  },
  {
   "title": "CPU requests",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "CPU" }
   ],
   "targets": [
    {
     "expr": "metering:cpu_requests:sum_by_namespace{shoot_uid=\"\",namespace=~\"$namespace\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "metering:cpu_requests:sum_by_namespace_owner_container{shoot_uid=\"\",namespace=~\"$namespace\",owner=~\"$owner\",container=~\"$container\"}",
     "legendFormat": "{{owner}} / {{container}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "metering:memory_usage:sum_by_namespace{shoot_uid=\"\",namespace=~\"$namespace\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "metering:memory_usage:sum_by_namespace_owner_container{shoot_uid=\"\",namespace=~\"$namespace\",owner=~\"$owner\",container=~\"$container\"}",
     "legendFormat": "{{owner}} / {{container}}"
    }
   ]
  },
  {
   "title": "Working Set Memory usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "metering:working_set_memory:sum_by_namespace{shoot_uid=\"\",namespace=~\"$namespace\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "metering:working_set_memory:sum_by_namespace_owner_container{shoot_uid=\"\",namespace=~\"$namespace\",owner=~\"$owner\",container=~\"$container\"}",
     "legendFormat": "{{owner}} / {{container}}"
    }
   ]
  },
  {
   "title": "Memory requests",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "metering:memory_requests:sum_by_namespace{shoot_uid=\"\",namespace=~\"$namespace\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "metering:memory_requests:sum_by_namespace_owner_container{shoot_uid=\"\",namespace=~\"$namespace\",owner=~\"$owner\",container=~\"$container\"}",
     "legendFormat": "{{owner}} / {{container}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Network Receive",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "metering:network_receive:sum_by_namespace{shoot_uid=\"\",namespace=~\"$namespace\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "metering:network_receive:sum_by_namespace_owner{shoot_uid=\"\",namespace=~\"$namespace\",owner=~\"$owner\"}",
     "legendFormat": "{{owner}}"
    }
   ]
  },
  {
   "title": "Network Transmit",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "metering:network_transmit:sum_by_namespace{shoot_uid=\"\",namespace=~\"$namespace\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "metering:network_transmit:sum_by_namespace_owner{shoot_uid=\"\",namespace=~\"$namespace\",owner=~\"$owner\"}",
     "legendFormat": "{{owner}}"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Persistent Volume Usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "metering:persistent_volume_usage:sum_by_namespace{shoot_uid=\"\",namespace=~\"$namespace\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "metering:persistent_volume_usage:sum_by_namespace_owner{shoot_uid=\"\",namespace=~\"$namespace\",owner=~\"$owner\"}",
     "legendFormat": "{{owner}}"
    }
   ]
  },
  {
   "title": "Persistent Volume Claims",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "metering:persistent_volume_claims:sum_by_namespace{shoot_uid=\"\",namespace=~\"$namespace\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "metering:persistent_volume_claims:sum_by_namespace_owner{shoot_uid=\"\",namespace=~\"$namespace\",owner=~\"$owner\"}",
     "legendFormat": "{{owner}}"
    }
   ]
  }
 ]
}