{
 "title": "Systemd Logs",
 "description": "Vali logs panel with prometheus variables",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "systemd_component",
    "label": "Unit",
    "query": "label_values(systemd_component)"
   },
   { "name": "search" }
  ]
 },
 "panels": [
  {
   "title": "Ready Nodes",
   "type": "singlestat",
   "description": "Nodes which have status \"Ready\"",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "seed:kube_node_status_condition:sum_by_condition{condition=\"Ready\",status=\"true\"}"
    }
   ]
  },
  {
   "title": "Non-Ready Nodes",
   "type": "singlestat",
   "description": "Nodes which do not have status \"Ready\"",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(seed:kube_node_status_condition:sum_by_condition{condition!=\"Ready\",status=\"true\"})"
    }
   ]
  },
  {
   "title": "CPU Utilisation",
   "type": "singlestat",
   "description": "CPU  utilisation of all nodes.",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1 - avg(rate(seed:node_cpu_seconds_total:sum[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "singlestat",
   "description": "Memory  utilisation of all nodes.",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1 - seed:node_memory_Active_bytes:sum /seed:kube_node_status_allocatable_memory_bytes:sum"
    }
   ]
  },
  {
   "title": "CPU Requests Commitment",
   "type": "singlestat",
   "description": "CPU  requests commitment of all pods.",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "seed:kube_pod_container_resource_requests_cpu_cores:sum / seed:kube_node_status_allocatable_cpu_cores:sum"
    }
   ]
  },
  {
   "title": "Memory Requests Commitment",
   "type": "singlestat",
   "description": "Memory  requests commitment of all pods.",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "seed:kube_pod_container_resource_requests_memory_bytes:sum / seed:kube_node_status_allocatable_memory_bytes:sum"
    }
   ]
  },
  {
   "title": "CPU Limits Commitment",
   "type": "singlestat",
   "description": "CPU  limits commitment of all pods.",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "seed:kube_pod_container_resource_limits_cpu_cores:sum / seed:kube_node_status_allocatable_cpu_cores:sum"
    }
   ]
  },
  {
   "title": "Memory Limits Commitment",
   "type": "singlestat",
   "description": "Memory  limits commitment of all pods.",
   "gridPos": { "h": 2, "w": 3, "x": 19, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "seed:kube_pod_container_resource_limits_memory_bytes:sum / seed:kube_node_status_allocatable_memory_bytes:sum"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "sum(count_over_time({systemd_component=\"$systemd_component\"} |~ \"$search\"[$__interval]))"
    }
   ]
  },
  {
   "title": "Logs Panel",
   "type": "logs",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "{systemd_component=\"$systemd_component\"} |~ \"$search\""
    }
   ]
  }
 ]
}