{
 "title": "VPN",
 "tags": [
  "network",
  "shoot",
  "seed"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "VPN Connection",
   "type": "graph",
   "description": "One means connection is active. \nMissing entry means connection is down.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{job=\"tunnel-probe-apiserver-proxy\", type=\"seed\"}",
     "legendFormat": "API Server Proxy test ({{instance}})"
    }
   ]
  },
  { "title": "VPN Shoot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "VPN Shoot Network I/O",
   "type": "graph",
   "description": "Received and transmitted network i/o",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (pod) (rate (container_network_receive_bytes_total{pod=~\"vpn-shoot-.*\"}[$__rate_interval]) ))",
     "legendFormat": "Received"
    },
    {
     "expr": "-sort_desc(sum by (pod) (rate (container_network_transmit_bytes_total{pod=~\"vpn-shoot-.*\"}[$__rate_interval]) ))",
     "legendFormat": "Transmitted"
    }
   ]
  },
  {
   "title": "VPN Shoot CPU Usage",
   "type": "graph",
   "description": "CPU usage in millicores",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"vpn-shoot-.*\"}[$__rate_interval]))",
     "legendFormat": "Actual"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\", pod=~\"vpn-shoot-.*\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\", pod=~\"vpn-shoot-.*\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "VPN Shoot Memory Usage",
   "type": "graph",
   "description": "Current memory usage",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod=~\"vpn-shoot-.*\"})",
     "legendFormat": "Actual"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\", pod=~\"vpn-shoot-.*\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\", pod=~\"vpn-shoot-.*\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  { "title": "VPN Seed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "VPN Seed CPU Usage",
   "type": "graph",
   "description": "CPU usage in millicores",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\"kube-apiserver-.*|vpn-seed-.*\", container=\"vpn-.*\"}[$__rate_interval])",
     "legendFormat": "Actual ({{pod}}/{{container}})"
    },
    {
     "expr": "kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\", pod=~\"kube-apiserver-.*|vpn-seed-.*\", container=\"vpn-.*\"}",
     "legendFormat": "Requests ({{pod}}/{{container}})"
    },
    {
     "expr": "kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\", pod=~\"kube-apiserver-.*|vpn-seed-.*\", container=\"vpn-.*\"}",
     "legendFormat": "Limits ({{pod}}/{{container}})"
    }
   ]
  },
  {
   "title": "VPN Seed Memory Usage",
   "type": "graph",
   "description": "Current memory usage",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{pod=~\"vpn-seed-.*\", container=\"vpn-seed-server\"}",
     "legendFormat": "Actual ({{pod}}/{{container}})"
    },
    {
     "expr": "kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\", pod=~\"kube-apiserver-.*|vpn-seed-.*\", container=\"vpn-.*\"}",
     "legendFormat": "Request ({{pod}}/{{container}})"
    },
    {
     "expr": "kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\", pod=~\"kube-apiserver-.*|vpn-seed-.*\", container=\"vpn-.*\"}",
     "legendFormat": "Limits ({{pod}}/{{container}})"
    }
   ]
  },
  {
   "title": "API Server Proxy Test",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "API Server Proxy Test",
     "type": "graph",
     "description": "Test if the API Server proxy/port-forward is working.\nThis functionality requires an active VPN connection from the API Server to `vpn-shoot` hosted on the Shoot workers.\n\nOne means test was successful.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "probe_success{job=\"tunnel-probe-apiserver-proxy\",type=\"seed\"}",
       "legendFormat": "API Server Proxy test ({{instance}})"
      }
     ]
    },
    {
     "title": "API Server Proxy Test Response Code",
     "type": "graph",
     "description": "Test if the API Server proxy/port-forward is working.\nThis functionality requires an active VPN connection from the API Server to `vpn-shoot` hosted on the Shoot workers.\n\nStatus Code of proxy/port-forward request to the API Server.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "probe_http_status_code{job=\"tunnel-probe-apiserver-proxy\",type=\"seed\"}",
       "legendFormat": "API Server Proxy test ({{instance}})"
      }
     ]
    }
   ]
  }
 ]
}