{
 "title": "Kubernetes Cluster Health",
 "tags": [
  "kubernetes",
  "seed",
  "shoot"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Control Plane", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "kube-apiserver",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "absent(up{job=\"kube-apiserver\"} == 1)"
    }
   ]
  },
  {
   "title": "controller-manager",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "absent(up{job=\"kube-controller-manager\"} == 1)"
    }
   ]
  },
  {
   "title": "kube-scheduler",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "absent(up{job=\"kube-scheduler\"} == 1)"
    }
   ]
  },
  {
   "title": "cloud-controller-manager",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "absent(up{job=\"cloud-controller-manager\"} == 1)"
    }
   ]
  },
  {
   "title": "cluster-autoscaler",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "absent(up{job=\"cluster-autoscaler\"} == 1)"
    }
   ]
  },
  {
   "title": "machine-controller-manager",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "absent(up{job=\"machine-controller-manager\"} == 1)"
    }
   ]
  },
  { "title": "Shoot Core", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "coredns",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "absent(up{job=\"coredns\"} == 1)"
    }
   ]
  },
  { "title": "Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "prometheus",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "absent(up{job=\"prometheus\"} == 1)"
    }
   ]
  },
  {
   "title": "alertmanager",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "absent(up{job=\"alertmanager\"} == 1)"
    }
   ]
  },
  {
   "title": "state-metrics-seed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "absent(up{job=\"kube-state-metrics\",type=\"seed\"} == 1)"
    }
   ]
  },
  {
   "title": "state-metrics-shoot",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "absent(up{job=\"kube-state-metrics\",type=\"shoot\"} == 1)"
    }
   ]
  },
  {
   "title": "node-exporter",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "absent(up{job=\"node-exporter\"} == 1)"
    }
   ]
  },
  { "title": "Common", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Alerts Firing",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\",alertname!=\"DeadMansSwitch\"})"
    }
   ]
  },
  {
   "title": "Alerts Pending",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"pending\",alertname!=\"DeadMansSwitch\"})"
    }
   ]
  },
  {
   "title": "Crashlooping Pods",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(increase(kube_pod_container_status_restarts[1h]) > 5)"
    }
   ]
  }
 ]
}