{
 "title": "Kubernetes Cluster Status",
 "tags": [
  "kubernetes",
  "control-plane",
  "seed"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "API Servers UP",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(up{job=\"kube-apiserver\"} == 1) / sum(up{job=\"kube-apiserver\"})) * 100"
    }
   ]
  },
  {
   "title": "Controller Managers UP",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(up{job=\"kube-controller-manager\"} == 1) / sum(up{job=\"kube-controller-manager\"})) * 100"
    }
   ]
  },
  {
   "title": "Schedulers UP",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(up{job=\"kube-scheduler\"} == 1) / sum(up{job=\"kube-scheduler\"})) * 100"
    }
   ]
  },
  {
   "title": "API Server Request Error Rate",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(sum by(instance) (rate(apiserver_request_count{code=~\"5..\"}[5m])) / sum by(instance) (rate(apiserver_request_count[5m]))) * 100"
    }
   ]
  },
  {
   "title": "Control Plane Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{type=\"seed\"})",
     "legendFormat": "Current"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{type=\"seed\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{type=\"seed\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Control Plane CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "none", "label": "CPU/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{type=\"seed\"}[5m]))",
     "legendFormat": "Current"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{type=\"seed\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{type=\"seed\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "API Server Request Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(verb) (rate(apiserver_latency_seconds:quantile[5m]) >= 0)",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "End to End Scheduling Latency Percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cluster:scheduler_e2e_scheduling_latency_seconds:quantile",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "API Server Request Rates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(instance) (rate(apiserver_request_count{code!~\"2..\"}[5m]))",
     "legendFormat": "Error Rate"
    },
    {
     "expr": "sum by(instance) (rate(apiserver_request_count[5m]))",
     "legendFormat": "Request Rate"
    }
   ]
  }
 ]
}