{
 "title": "Kubernetes DaemonSets",
 "tags": [
  "kubernetes",
  "shoot"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "type", "label": "Type", "query": "shoot" },
   {
    "name": "daemonset_name",
    "label": "DaemonSet",
    "query": "label_values(kube_daemonset_metadata_generation{type=~\"$type\"}, daemonset)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod_name=~\"$daemonset_name.*\"}[3m])) "
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod_name=~\"$daemonset_name.*\"}) / 1024^3"
    }
   ]
  },
  {
   "title": "Network",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod_name=~\"$daemonset_name.*\"}[3m])) + sum(rate(container_network_receive_bytes_total{pod_name=~\"$daemonset_name.*\"}[3m])) "
    }
   ]
  },
  {
   "title": "Desired Scheduled",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(kube_daemonset_status_desired_number_scheduled{daemonset=\"$daemonset_name\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Current Scheduled",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(kube_daemonset_status_current_number_scheduled{daemonset=\"$daemonset_name\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Metadata Generation",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(kube_daemonset_metadata_generation{daemonset=\"$daemonset_name\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(kube_daemonset_status_current_number_scheduled{daemonset=\"$daemonset_name\"}) without (instance, pod)",
     "legendFormat": "current replicas"
    },
    {
     "expr": "min(kube_daemonset_status_number_available{daemonset=\"$daemonset_name\"}) without (instance, pod)",
     "legendFormat": "available"
    },
    {
     "expr": "max(kube_daemonset_status_number_unavailable{daemonset=\"$daemonset_name\"}) without (instance, pod)",
     "legendFormat": "unavailable"
    },
    {
     "expr": "min(kube_daemonset_updated_number_scheduled{daemonset=\"$daemonset_name\"}) without (instance, pod)",
     "legendFormat": "updated"
    },
    {
     "expr": "max(kube_daemonset_status_desired_number_scheduled{daemonset=\"$daemonset_name\"}) without (instance, pod)",
     "legendFormat": "desired"
    }
   ]
  },
  {
   "title": "Drill down to to Pod Dashboard",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "kube_pod_info{created_by_kind=\"DaemonSet\",created_by_name=\"$daemonset_name\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}