{
 "title": "VPA Recommendations",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "recommendation",
    "label": "Recommendation",
    "query": "label_values(vpa_status_recommendation, recommendation)"
   },
   {
    "name": "targetName",
    "label": "Target",
    "query": "label_values(vpa_status_recommendation, targetName)"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory Target vs Memory Usage",
   "type": "graph",
   "description": "Shows the recommendations that the VPA gives as target usage. The graph also shows the actual usage of each container.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "sum(vpa_status_recommendation{recommendation=\"$recommendation\", resource=\"memory\", targetName=\"$targetName\"})",
     "legendFormat": "sum recommendation"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{pod_name=~\"$targetName(.+)\"})",
     "legendFormat": "sum actual usage"
    },
    {
     "expr": "container_memory_working_set_bytes{pod_name=~\"$targetName(.+)\"}",
     "legendFormat": "{{ container_name }} actual usage"
    },
    {
     "expr": "vpa_status_recommendation{recommendation=\"$recommendation\", resource=\"memory\", targetName=\"$targetName\"}",
     "legendFormat": "{{ container }}-recommendation"
    }
   ]
  },
  {
   "title": "VPA Memory Recommendations vs Requests and Limits",
   "type": "graph",
   "description": "Shows the recommendation of the VPA and compares it to the requests and limits of all containers in a pod. \n\n**Requests and/or limits may not reflect useful values if they are not defined for each container in a pod.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "sum(vpa_status_recommendation{targetName=\"$targetName\", resource=\"memory\", recommendation=~\"$recommendation\"})",
     "legendFormat": "recommendation"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{pod=~\"$targetName(.+)\"})",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{pod=~\"$targetName(.+)\"})",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "CPU Target vs CPU Usage",
   "type": "graph",
   "description": "Shows the recommendations that the VPA gives as target usage. The graph also shows the actual usage of each container.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Millicores" }
   ],
   "targets": [
    {
     "expr": "sum(vpa_status_recommendation{recommendation=~\"$recommendation\", resource=\"cpu\", targetName=\"$targetName\"})",
     "legendFormat": "recommendation sum"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod_name=~\"$targetName(.+)\"}[1m])) * 1000",
     "legendFormat": "sum actual usage"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod_name=~\"$targetName(.+)\"}[1m]) * 1000",
     "legendFormat": "{{ container_name }} actual usage"
    },
    {
     "expr": "vpa_status_recommendation{recommendation=~\"$recommendation\", resource=\"cpu\", targetName=\"$targetName\"}",
     "legendFormat": "{{ container }}-recommendation"
    }
   ]
  },
  {
   "title": "VPA CPU Recommendations vs Requests and Limits",
   "type": "graph",
   "description": "Shows the recommendation of the VPA and compares it to the requests and limits of all containers in a pod. \n\n**Requests and/or limits may not reflect useful values if they are not defined for each container in a pod.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Millicores" }
   ],
   "targets": [
    {
     "expr": "sum(vpa_status_recommendation{targetName=\"$targetName\", resource=\"cpu\", recommendation=~\"$recommendation\"})",
     "legendFormat": "recommendation"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{pod=~\"$targetName(.+)\"}) * 1000",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{pod=~\"$targetName(.+)\"})* 1000",
     "legendFormat": "limits"
    }
   ]
  }
 ]
}