apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- patch: |-
    - op: add
      path: /nodes/-
      value:
        role: worker
        image: kindest/node:v1.36.1@sha256:3489c7674813ba5d8b1a9977baea8a6e553784dab7b84759d1014dbd78f7ebd5
        labels:
          topology.kubernetes.io/zone: "0"
        extraPortMappings: []
        extraMounts:
          - hostPath: ./dev/local-backupbuckets
            containerPath: /etc/gardener/local-backupbuckets
          - hostPath: ./dev-setup/infra/resolv.conf
            containerPath: /etc/resolv.conf
          - hostPath: ${DOCKER_SOCKET}
            containerPath: /var/run/docker.sock
        kubeadmConfigPatches:
          - "" # empty patch to allow adding kubeadm config patches for the control plane node only, see next patch below
               # if we'd just append to kubeadmConfigPatches, we would end up with duplication in case this node component is added multiple times (for multi-node kind clusters)
          - |
            apiVersion: kubelet.config.k8s.io/v1beta1
            kind: KubeletConfiguration
            maxPods: 500
            serializeImagePulls: false
            registryPullQPS: 10
            registryBurst: 20
            serverTLSBootstrap: true
  target:
    group: kind.x-k8s.io
    kind: Cluster
    name: gardener-local

# Patches exclusively for the control plane node (always the first one, and always only exactly one)
- patch: |-
    - op: replace
      path: /nodes/0/role
      value: control-plane
    - op: replace
      path: /nodes/0/kubeadmConfigPatches/0
      value: |
        apiVersion: kubeadm.k8s.io/v1beta4
        kind: ClusterConfiguration
  target:
    group: kind.x-k8s.io
    kind: Cluster
    name: gardener-local
