// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	corev1beta1 "github.com/gardener/gardener/pkg/apis/core/v1beta1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// NamespacedCloudProfileLister helps list NamespacedCloudProfiles.
// All objects returned here must be treated as read-only.
type NamespacedCloudProfileLister interface {
	// List lists all NamespacedCloudProfiles in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*corev1beta1.NamespacedCloudProfile, err error)
	// NamespacedCloudProfiles returns an object that can list and get NamespacedCloudProfiles.
	NamespacedCloudProfiles(namespace string) NamespacedCloudProfileNamespaceLister
	NamespacedCloudProfileListerExpansion
}

// namespacedCloudProfileLister implements the NamespacedCloudProfileLister interface.
type namespacedCloudProfileLister struct {
	listers.ResourceIndexer[*corev1beta1.NamespacedCloudProfile]
}

// NewNamespacedCloudProfileLister returns a new NamespacedCloudProfileLister.
func NewNamespacedCloudProfileLister(indexer cache.Indexer) NamespacedCloudProfileLister {
	return &namespacedCloudProfileLister{listers.New[*corev1beta1.NamespacedCloudProfile](indexer, corev1beta1.Resource("namespacedcloudprofile"))}
}

// NamespacedCloudProfiles returns an object that can list and get NamespacedCloudProfiles.
func (s *namespacedCloudProfileLister) NamespacedCloudProfiles(namespace string) NamespacedCloudProfileNamespaceLister {
	return namespacedCloudProfileNamespaceLister{listers.NewNamespaced[*corev1beta1.NamespacedCloudProfile](s.ResourceIndexer, namespace)}
}

// NamespacedCloudProfileNamespaceLister helps list and get NamespacedCloudProfiles.
// All objects returned here must be treated as read-only.
type NamespacedCloudProfileNamespaceLister interface {
	// List lists all NamespacedCloudProfiles in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*corev1beta1.NamespacedCloudProfile, err error)
	// Get retrieves the NamespacedCloudProfile from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*corev1beta1.NamespacedCloudProfile, error)
	NamespacedCloudProfileNamespaceListerExpansion
}

// namespacedCloudProfileNamespaceLister implements the NamespacedCloudProfileNamespaceLister
// interface.
type namespacedCloudProfileNamespaceLister struct {
	listers.ResourceIndexer[*corev1beta1.NamespacedCloudProfile]
}
