apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
# This kubeconfig always targets the "gardener-local" kind cluster.
- name: local
  namespace: garden-local
  options:
    disableNameSuffixHash: true
  files:
  - kubeconfig
