{
 "title": "ETCD Cluster Details",
 "tags": [
  "controlplane",
  "seed"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "role", "query": "main, events" },
   {
    "name": "member",
    "query": {
     "query": "label_values(etcd_server_has_leader{job=\"kube-etcd3-$role\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Size",
   "type": "stat",
   "description": "Observed size of the etcd cluster",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "min(etcdbr_cluster_size{job=\"kube-etcd3-backup-restore-$role\"})"
    }
   ]
  },
  {
   "title": "Running Members",
   "type": "stat",
   "description": "Total number of etcd members that are running, that may or may not be part of the same cluster (due to possible network partition or cluster formation errors)",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"kube-etcd3-backup-restore-$role\"})"
    }
   ]
  },
  {
   "title": "Quorate Members",
   "type": "stat",
   "description": "Total number of etcd members that have quorum.\nEtcd cluster is considered healthy if this value matches the \"Cluster Size\" value",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(etcd_server_has_leader{job=\"kube-etcd3-$role\"})"
    }
   ]
  },
  {
   "title": "Member Health Status",
   "type": "graph",
   "description": "Shows whether all etcd members are healthy (0=Unhealthy, 1=Healthy) over time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etcd_server_has_leader{job=\"kube-etcd3-$role\",pod=~\".*$role-($member)\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Membership Status",
   "type": "graph",
   "description": "Shows the membership state (0=Follower, 1=Learner, 2=Leader) for all etcd members over time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etcd_server_is_leader{job=\"kube-etcd3-$role\",pod=~\".*$role-($member)\"}*2 + etcd_server_is_learner{job=\"kube-etcd3-$role\",pod=~\".*$role-($member)\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Cluster Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Total Leader Elections Per Day",
   "type": "graph",
   "description": "Total number of leader changes seen per day in the cluster",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(etcd_server_leader_changes_seen_total{job=\"kube-etcd3-$role\",pod=~\".*$role-($member)\"}[1d])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Heartbeat Send Failures",
   "type": "graph",
   "description": "Total number of heartbeat send failures per etcd member",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_server_heartbeat_send_failures_total{job=\"kube-etcd3-$role\",pod=~\".*$role-($member)\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Raft Proposals",
   "type": "graph",
   "description": "Raft proposal details for the etcd cluster",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_server_proposals_failed_total{role=~\"etcd-$role\"}[$__rate_interval]))",
     "legendFormat": "Proposal Failure Rate"
    },
    {
     "expr": "sum(etcd_server_proposals_pending{role=~\"etcd-$role\"})",
     "legendFormat": "Proposal Pending"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_committed_total{role=~\"etcd-$role\"}[$__rate_interval]))",
     "legendFormat": "Proposal Commit Rate"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_applied_total{role=~\"etcd-$role\"}[$__rate_interval]))",
     "legendFormat": "Proposal Apply Rate"
    }
   ]
  },
  {
   "title": "Add Learner Duration",
   "type": "graph",
   "description": "Time taken by etcd-backup-restore to add learner to the cluster",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcdbr_add_learner_duration_seconds_bucket{job=\"kube-etcd3-backup-restore-$role\",pod=~\".*$role-($member)\"}[$__rate_interval])) by (le))",
     "legendFormat": "etcd-$role"
    }
   ]
  },
  {
   "title": "Successful Learner Promotions",
   "type": "graph",
   "description": "Total number of successful promotions from learner to voting member in the cluster",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etcd_server_learner_promote_successes{job=\"kube-etcd3-$role\",pod=~\".*$role-($member)\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Member Remove Duration",
   "type": "graph",
   "description": "Time taken by etcd-backup-restore to remove member from the cluster",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcdbr_member_remove_duration_seconds_bucket{job=\"kube-etcd3-backup-restore-$role\",pod=~\".*$role-($member)\"}[$__rate_interval])) by (le))",
     "legendFormat": "etcd-$role"
    }
   ]
  },
  { "title": "Peer Networking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Active Peers (All Members)",
   "type": "graph",
   "description": "Total number of active peers in the cluster per member",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(etcd_network_active_peers{job=\"kube-etcd3-$role\",pod=~\".*$role-($member)\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Peer RTT",
   "type": "graph",
   "description": "Round trip time taken for etcd peer communication",
   "gridPos": { "h": 5, "w": 6, "x": 4, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_network_peer_round_trip_time_seconds_bucket{job=\"kube-etcd3-$role\",pod=~\".*$role-($member)\"}[$__rate_interval])) by (pod, le))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Peer Sent Bytes",
   "type": "graph",
   "description": "Network rate for data sent from each member to other members in the cluster",
   "gridPos": { "h": 5, "w": 7, "x": 10, "y": 30 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_network_peer_sent_bytes_total{job=\"kube-etcd3-$role\",pod=~\".*$role-($member)\"}[5m])",
     "legendFormat": "{{pod}} -> {{To}}"
    }
   ]
  },
  {
   "title": "Peer Received Bytes",
   "type": "graph",
   "description": "Network rate for data received by each member from other members in the cluster",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 30 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_network_peer_received_bytes_total{job=\"kube-etcd3-$role\",pod=~\".*$role-($member)\"}[5m])",
     "legendFormat": "{{pod}} <- {{From}}"
    }
   ]
  },
  { "title": "Cluster Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Total Slow Applies",
   "type": "graph",
   "description": "Shows the slow applies on the etcd cluster",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_server_slow_apply_total{job=\"kube-etcd3-$role\",pod=~\".*$role-($member)\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total Slow Read Indexes",
   "type": "graph",
   "description": "Shows the slow index reads for the etcd cluster",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_server_slow_read_indexes_total{job=\"kube-etcd3-$role\",pod=~\".*$role-($member)\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}