{
 "title": "Mutating and ValidatingAdmissionPolicies",
 "tags": [
  "controlplane",
  "seed"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "ValidatingAdmissionPolicies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ValidatingadmissionPolicies rejection rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_validating_admission_policy_check_total{enforcement_action=\"deny\"}[$__rate_interval])) by (policy,policy_binding)",
     "legendFormat": "{{policy}}/{{policy_binding}} rejections"
    }
   ]
  },
  {
   "title": "ValidatingAdmissionPolicies 95th percentile execution times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(apiserver_validating_admission_policy_check_duration_seconds_bucket[5m])) by (le,policy,policy_binding))",
     "legendFormat": "{{policy}}/{{policy_binding}}"
    }
   ]
  },
  { "title": "MutatingAdmissionPolicies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "MutatingAdmissionPolicies execution rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_mutating_admission_policy_check_total{}[$__rate_interval])) by (policy,policy_binding)",
     "legendFormat": "{{policy}}/{{policy_binding}}"
    }
   ]
  },
  {
   "title": "MutatingAdmissionPolicies 95th percentile execution times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(apiserver_mutating_admission_policy_check_duration_seconds_bucket[5m])) by (le,policy,policy_binding))",
     "legendFormat": "{{policy}}/{{policy_binding}}"
    }
   ]
  }
 ]
}