apiVersion: v1
kind: Secret
metadata:
  name: default-domain-migration-local-gardener-cloud
  namespace: garden
  labels:
    app: gardener
    gardener.cloud/role: default-domain
  annotations:
    dns.gardener.cloud/provider: local
    dns.gardener.cloud/domain: migration.local.gardener.cloud
type: Opaque
