//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	local "github.com/gardener/gardener/pkg/provider-local/apis/local"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*CloudProfileConfig)(nil), (*local.CloudProfileConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CloudProfileConfig_To_local_CloudProfileConfig(a.(*CloudProfileConfig), b.(*local.CloudProfileConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*local.CloudProfileConfig)(nil), (*CloudProfileConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_local_CloudProfileConfig_To_v1alpha1_CloudProfileConfig(a.(*local.CloudProfileConfig), b.(*CloudProfileConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineImage)(nil), (*local.MachineImage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MachineImage_To_local_MachineImage(a.(*MachineImage), b.(*local.MachineImage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*local.MachineImage)(nil), (*MachineImage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_local_MachineImage_To_v1alpha1_MachineImage(a.(*local.MachineImage), b.(*MachineImage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineImageVersion)(nil), (*local.MachineImageVersion)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MachineImageVersion_To_local_MachineImageVersion(a.(*MachineImageVersion), b.(*local.MachineImageVersion), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*local.MachineImageVersion)(nil), (*MachineImageVersion)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_local_MachineImageVersion_To_v1alpha1_MachineImageVersion(a.(*local.MachineImageVersion), b.(*MachineImageVersion), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineImages)(nil), (*local.MachineImages)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MachineImages_To_local_MachineImages(a.(*MachineImages), b.(*local.MachineImages), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*local.MachineImages)(nil), (*MachineImages)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_local_MachineImages_To_v1alpha1_MachineImages(a.(*local.MachineImages), b.(*MachineImages), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*WorkerStatus)(nil), (*local.WorkerStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_WorkerStatus_To_local_WorkerStatus(a.(*WorkerStatus), b.(*local.WorkerStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*local.WorkerStatus)(nil), (*WorkerStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_local_WorkerStatus_To_v1alpha1_WorkerStatus(a.(*local.WorkerStatus), b.(*WorkerStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_CloudProfileConfig_To_local_CloudProfileConfig(in *CloudProfileConfig, out *local.CloudProfileConfig, s conversion.Scope) error {
	out.MachineImages = *(*[]local.MachineImages)(unsafe.Pointer(&in.MachineImages))
	return nil
}

// Convert_v1alpha1_CloudProfileConfig_To_local_CloudProfileConfig is an autogenerated conversion function.
func Convert_v1alpha1_CloudProfileConfig_To_local_CloudProfileConfig(in *CloudProfileConfig, out *local.CloudProfileConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_CloudProfileConfig_To_local_CloudProfileConfig(in, out, s)
}

func autoConvert_local_CloudProfileConfig_To_v1alpha1_CloudProfileConfig(in *local.CloudProfileConfig, out *CloudProfileConfig, s conversion.Scope) error {
	out.MachineImages = *(*[]MachineImages)(unsafe.Pointer(&in.MachineImages))
	return nil
}

// Convert_local_CloudProfileConfig_To_v1alpha1_CloudProfileConfig is an autogenerated conversion function.
func Convert_local_CloudProfileConfig_To_v1alpha1_CloudProfileConfig(in *local.CloudProfileConfig, out *CloudProfileConfig, s conversion.Scope) error {
	return autoConvert_local_CloudProfileConfig_To_v1alpha1_CloudProfileConfig(in, out, s)
}

func autoConvert_v1alpha1_MachineImage_To_local_MachineImage(in *MachineImage, out *local.MachineImage, s conversion.Scope) error {
	out.Name = in.Name
	out.Version = in.Version
	out.Image = in.Image
	return nil
}

// Convert_v1alpha1_MachineImage_To_local_MachineImage is an autogenerated conversion function.
func Convert_v1alpha1_MachineImage_To_local_MachineImage(in *MachineImage, out *local.MachineImage, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineImage_To_local_MachineImage(in, out, s)
}

func autoConvert_local_MachineImage_To_v1alpha1_MachineImage(in *local.MachineImage, out *MachineImage, s conversion.Scope) error {
	out.Name = in.Name
	out.Version = in.Version
	out.Image = in.Image
	return nil
}

// Convert_local_MachineImage_To_v1alpha1_MachineImage is an autogenerated conversion function.
func Convert_local_MachineImage_To_v1alpha1_MachineImage(in *local.MachineImage, out *MachineImage, s conversion.Scope) error {
	return autoConvert_local_MachineImage_To_v1alpha1_MachineImage(in, out, s)
}

func autoConvert_v1alpha1_MachineImageVersion_To_local_MachineImageVersion(in *MachineImageVersion, out *local.MachineImageVersion, s conversion.Scope) error {
	out.Version = in.Version
	out.Image = in.Image
	return nil
}

// Convert_v1alpha1_MachineImageVersion_To_local_MachineImageVersion is an autogenerated conversion function.
func Convert_v1alpha1_MachineImageVersion_To_local_MachineImageVersion(in *MachineImageVersion, out *local.MachineImageVersion, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineImageVersion_To_local_MachineImageVersion(in, out, s)
}

func autoConvert_local_MachineImageVersion_To_v1alpha1_MachineImageVersion(in *local.MachineImageVersion, out *MachineImageVersion, s conversion.Scope) error {
	out.Version = in.Version
	out.Image = in.Image
	return nil
}

// Convert_local_MachineImageVersion_To_v1alpha1_MachineImageVersion is an autogenerated conversion function.
func Convert_local_MachineImageVersion_To_v1alpha1_MachineImageVersion(in *local.MachineImageVersion, out *MachineImageVersion, s conversion.Scope) error {
	return autoConvert_local_MachineImageVersion_To_v1alpha1_MachineImageVersion(in, out, s)
}

func autoConvert_v1alpha1_MachineImages_To_local_MachineImages(in *MachineImages, out *local.MachineImages, s conversion.Scope) error {
	out.Name = in.Name
	out.Versions = *(*[]local.MachineImageVersion)(unsafe.Pointer(&in.Versions))
	return nil
}

// Convert_v1alpha1_MachineImages_To_local_MachineImages is an autogenerated conversion function.
func Convert_v1alpha1_MachineImages_To_local_MachineImages(in *MachineImages, out *local.MachineImages, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineImages_To_local_MachineImages(in, out, s)
}

func autoConvert_local_MachineImages_To_v1alpha1_MachineImages(in *local.MachineImages, out *MachineImages, s conversion.Scope) error {
	out.Name = in.Name
	out.Versions = *(*[]MachineImageVersion)(unsafe.Pointer(&in.Versions))
	return nil
}

// Convert_local_MachineImages_To_v1alpha1_MachineImages is an autogenerated conversion function.
func Convert_local_MachineImages_To_v1alpha1_MachineImages(in *local.MachineImages, out *MachineImages, s conversion.Scope) error {
	return autoConvert_local_MachineImages_To_v1alpha1_MachineImages(in, out, s)
}

func autoConvert_v1alpha1_WorkerStatus_To_local_WorkerStatus(in *WorkerStatus, out *local.WorkerStatus, s conversion.Scope) error {
	out.MachineImages = *(*[]local.MachineImage)(unsafe.Pointer(&in.MachineImages))
	return nil
}

// Convert_v1alpha1_WorkerStatus_To_local_WorkerStatus is an autogenerated conversion function.
func Convert_v1alpha1_WorkerStatus_To_local_WorkerStatus(in *WorkerStatus, out *local.WorkerStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_WorkerStatus_To_local_WorkerStatus(in, out, s)
}

func autoConvert_local_WorkerStatus_To_v1alpha1_WorkerStatus(in *local.WorkerStatus, out *WorkerStatus, s conversion.Scope) error {
	out.MachineImages = *(*[]MachineImage)(unsafe.Pointer(&in.MachineImages))
	return nil
}

// Convert_local_WorkerStatus_To_v1alpha1_WorkerStatus is an autogenerated conversion function.
func Convert_local_WorkerStatus_To_v1alpha1_WorkerStatus(in *local.WorkerStatus, out *WorkerStatus, s conversion.Scope) error {
	return autoConvert_local_WorkerStatus_To_v1alpha1_WorkerStatus(in, out, s)
}
