{
 "title": "OIDC Webhook Authenticator",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Requests/s grouped by result",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(oidc_webhook_authenticator_token_validation_total{job=\"oidc-webhook-authenticator\"}[$__rate_interval])) by (result)",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Total requests/s",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(oidc_webhook_authenticator_token_validation_total{job=\"oidc-webhook-authenticator\"}[$__rate_interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Validation duration per instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90,sum(rate(oidc_webhook_authenticator_token_validation_time_seconds_bucket{job=\"oidc-webhook-authenticator\"}[$__rate_interval])) by(le, instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Available instances",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "up{job=\"oidc-webhook-authenticator\"} == 1",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}