apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
# This secret contains the kubeconfig for the "gardener-local" kind cluster. Provider-local uses it to manage
# infrastructure resources in this cluster, instead of using its in-cluster ServiceAccount. See
# docs/extensions/provider-local.md#credentials for details. The kubeconfig file is copied to this directory by
# `dev-setup/kind.sh up` and `dev-setup/gind.sh`.
- name: local
  namespace: garden
  options:
    disableNameSuffixHash: true
  files:
  - kubeconfig
