images:
  cloud-controller-manager-local: image-repository:image-tag

replicas: 1
clusterName: ""
hasManagedInfrastructure: true
podAnnotations: {}
podLabels: {}
priorityClassName: system-cluster-critical

server:
  port: 10258
  tlsSecret: ""
  tlsCipherSuites: []
