#!/usr/bin/env bash

set -e

# For the build step concourse will set the following environment variables:
# SOURCE_PATH - path to component repository root directory.
# BINARY_PATH - path to an existing (empty) directory to place build results into.

if [[ -z "${SOURCE_PATH}" ]]; then
  export SOURCE_PATH="$(readlink -f $(dirname ${0})/..)"
else
  export SOURCE_PATH="$(readlink -f "${SOURCE_PATH}")"
fi

if [[ -z "${BINARY_PATH}" ]]; then
  export BINARY_PATH="${SOURCE_PATH}/bin"
else
  export BINARY_PATH="$(readlink -f "${BINARY_PATH}")/bin"
fi

# The `go <cmd>` commands requires to see the target repository to be part of a
# Go workspace. Thus, if we are not yet in a Go workspace, let's create one
# temporarily by using symbolic links.
if [[ "${SOURCE_PATH}" != *"src/github.com/gardener/gardener" ]]; then
  SOURCE_SYMLINK_PATH="${SOURCE_PATH}/tmp/src/github.com/gardener/gardener"
  if [[ -d "${SOURCE_PATH}/tmp" ]]; then
    rm -rf "${SOURCE_PATH}/tmp"
  fi
  mkdir -p "${SOURCE_PATH}/tmp/src/github.com/gardener"
  ln -s "${SOURCE_PATH}" "${SOURCE_SYMLINK_PATH}"
  cd "${SOURCE_SYMLINK_PATH}"

  export GOPATH="${SOURCE_PATH}/tmp"
  export GOBIN="${SOURCE_PATH}/tmp/bin"
  export PATH="${GOBIN}:${PATH}"
fi

###############################################################################

VERSION_FILE="$(readlink -f "${SOURCE_PATH}/VERSION")"
VERSION="$(cat "${VERSION_FILE}")"

# If no LOCAL_BUILD environment variable is set, we configure the `go build` command
# to build for linux OS, amd64 architectures and without CGO enablement.
if [[ -z "$LOCAL_BUILD" ]]; then
  CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build \
    -a \
    -v \
    -o ${BINARY_PATH}/rel/gardener-apiserver \
    -ldflags "-w -X github.com/gardener/gardener/pkg/version.Version=${VERSION}" \
    cmd/gardener-apiserver/*.go

  CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build \
    -a \
    -v \
    -o ${BINARY_PATH}/rel/gardener-controller-manager \
    -ldflags "-w -X github.com/gardener/gardener/pkg/version.Version=${VERSION}" \
    cmd/gardener-controller-manager/*.go

# If the LOCAL_BUILD environment variable is set, we simply run `go build`.
else
  go build \
    -v \
    -o ${BINARY_PATH}/gardener-apiserver \
    -ldflags "-w -X github.com/gardener/gardener/pkg/version.Version=${VERSION}" \
    cmd/gardener-apiserver/*.go

  go build \
    -v \
    -o ${BINARY_PATH}/gardener-controller-manager \
    -ldflags "-w -X github.com/gardener/gardener/pkg/version.Version=${VERSION}" \
    cmd/gardener-controller-manager/*.go
fi
