#!/usr/bin/env bash
#
# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

"$(dirname $0)"/../hack/.ci/component_descriptor "$(dirname $0)"/..
