#!/usr/bin/env bash

set -e

images_file="$(dirname "$0")/../charts/images.yaml"
images="$(yaml2json < $images_file)"

echo "enriching creating component descriptor from ${BASE_DEFINITION_PATH}"

eval "$(jq -r ".images |
  map(select(.name != \"gardenlet\") |
    if (.name == \"kube-apiserver\" or .name == \"kube-controller-manager\" or .name == \"kube-scheduler\" or .name == \"kube-proxy\") then
      \"--generic-dependencies '{\\\"name\\\": \\\"\" + .name + \"\\\", \\\"version\\\": \\\"\" + .tag + \"\\\"}'\"
    elif (.repository | startswith(\"eu.gcr.io/gardener-project/gardener\")) then
      \"--component-dependencies '{\\\"name\\\": \\\"\" + .sourceRepository + \"\\\", \\\"version\\\": \\\"\" + .tag + \"\\\"}'\"
    else
      \"--container-image-dependencies '{\\\"name\\\": \\\"\" + .name + \"\\\", \\\"image_reference\\\": \\\"\" + .repository + \":\" + .tag + \"\\\", \\\"version\\\": \\\"\" + .tag + \"\\\"}'\"
    end) |
  \"${ADD_DEPENDENCIES_CMD} \\\\\n\" +
  join(\" \\\\\n\")" <<< "$images")"

cp "${BASE_DEFINITION_PATH}" "${COMPONENT_DESCRIPTOR_PATH}"
