#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

cd "$(dirname $0)/.."

git config --global user.email "gardener@sap.com"
git config --global user.name "Gardener CI/CD"

apt-get update
apt-get install -y unzip jq

mkdir -p /go/src/github.com/gardener/gardener
cp -r . /go/src/github.com/gardener/gardener
cd /go/src/github.com/gardener/gardener

make verify-extended
