{
 "title": "Cluster Overview",
 "tags": [
  "Control Planes",
  "shoot"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "shoot",
    "label": "Shoot",
    "query": "label_values(seed:container_cpu_usage_seconds_total:sum_by_pod{namespace=~\"shoot(.+)\"},namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "API Server Count",
   "type": "graph",
   "description": "Shows how many API Servers are running for the selected shoot.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "shoot:kube_apiserver:sum_by_pod{cluster=~\"$shoot\"}",
     "legendFormat": "API Server Replicas"
    }
   ]
  },
  {
   "title": "Node Count",
   "type": "graph",
   "description": "Shows the number of nodes that the selected cluster has.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "shoot:kube_node_info:count{cluster=~\"$shoot\"}",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "Control Plane CPU Usage",
   "type": "graph",
   "description": "Shows the CPU usage of the control plane for the selected shoot.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(seed:container_cpu_usage_seconds_total:sum_by_pod{namespace=~\"$shoot\"})",
     "legendFormat": "$shoot"
    }
   ]
  },
  {
   "title": "Control Plane Memory Usage",
   "type": "graph",
   "description": "Shows the memory usage of the selected control plane.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum(seed:container_memory_working_set_bytes:sum_by_pod{namespace=~\"$shoot\"})",
     "legendFormat": "$shoot"
    }
   ]
  }
 ]
}