{
 "title": "Controller Runtime / Controllers",
 "tags": [ "controller-runtime" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(controller_runtime_reconcile_total{}, job)"
    }
   },
   {
    "name": "instance_name",
    "label": "name",
    "query": {
     "query": "label_values(controller_runtime_reconcile_total{job=\"$job\"},app_kubernetes_io_instance)"
    }
   },
   {
    "name": "controller",
    "query": {
     "query": "label_values(controller_runtime_reconcile_total{job=\"$job\",app_kubernetes_io_instance=\"$instance_name\"}, controller)"
    }
   },
   { "name": "percentile", "query": "50,90,99" }
  ]
 },
 "panels": [
  { "title": "Headlines (over time range)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Reconciliation Rate",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{job=\"$job\",controller=~\"$controller\"}[$__range])) by (controller)",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Total Workers by controller",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(controller_runtime_max_concurrent_reconciles{job=\"$job\",controller=~\"$controller\"}) by (controller)"
    }
   ]
  },
  {
   "title": "Reconciliation Time Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_time_seconds_sum{job=\"$job\",controller=~\"$controller\"}[$__range])) by (controller)",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  { "title": "Reconciliations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Number of Reconciliations by controller",
   "type": "timeseries",
   "description": "Shows the total number of reconciliations per controller.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{job=\"$job\",controller=~\"$controller\"}[$__rate_interval])) by (controller)",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Reconciliation Rate",
   "type": "timeseries",
   "description": "Shows the reconciliation rate per controller.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_time_seconds_count{job=\"$job\",controller=~\"$controller\"}[$__rate_interval])) by(controller)",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Reconciliation Rate by result",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{job=\"$job\",controller=~\"$controller\"}[$__rate_interval])) by (result)",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Error Rate by controller",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_errors_total{job=\"$job\",controller=~\"$controller\"}[$__rate_interval])) by (controller)",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Reconciliation Time by controller (P$percentile)",
   "type": "graph",
   "description": "Shows the length per reconciliation per controller.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($percentile/100, sum(rate(controller_runtime_reconcile_time_seconds_bucket{job=\"$job\",controller=~\"$controller\"}[$__rate_interval])) by (controller,le))",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  { "title": "Workers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Active workers by controller",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(controller_runtime_active_workers{job=\"$job\",controller=~\"$controller\"}) by (controller)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": " max(controller_runtime_max_concurrent_reconciles{job=\"$job\",controller=~\"$controller\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Total workers by controllers",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(controller_runtime_max_concurrent_reconciles{job=\"$job\",controller=~\"$controller\"}) by (controller)"
    }
   ]
  },
  {
   "title": "Longest Running Worker by controller",
   "type": "timeseries",
   "description": "Shows for how many seconds the longest running worker for a workqueue has been running.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(workqueue_longest_running_processor_seconds{job=\"$job\",name=~\"$controller\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Unfinished Work by controller",
   "type": "timeseries",
   "description": "Rate of unfinished work per second not observed in work duration metrics. A constant value of 1 could indicate 1 stuck worker routine.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(workqueue_unfinished_work_seconds{job=\"$job\",name=~\"$controller\"}[$__rate_interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Work Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Enqueues",
   "type": "timeseries",
   "description": "Shows the total number of adds to the work queue.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(workqueue_adds_total{job=\"$job\",name=~\"$controller\"}[$__rate_interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Retries",
   "type": "timeseries",
   "description": "Shows the total number of retries handled by the workqueue.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(workqueue_retries_total{job=\"$job\",name=~\"$controller\"}[$__rate_interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Work Rate",
   "type": "timeseries",
   "description": "Shows how many items of the workqueue are processed.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(workqueue_work_duration_seconds_count{job=\"$job\",name=~\"$controller\"}[$__rate_interval])) by(name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Queue Duration by controller (P$percentile)",
   "type": "timeseries",
   "description": "Shows how long an item stays in the workqueue before being requested.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile/100, sum(rate(workqueue_queue_duration_seconds_bucket{job=\"$job\",name=~\"$controller\"}[$__rate_interval])) by (name,le))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Work Duration (P$percentile)",
   "type": "timeseries",
   "description": "Shows how long it takes to process an item.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile/100, sum(rate(workqueue_work_duration_seconds_bucket{job=\"$job\",name=~\"$controller\"}[$__rate_interval])) by (name,le))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Queue Length by controller",
   "type": "graph",
   "description": "Shows the current length of the workqueue.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(workqueue_depth{job=\"$job\",name=~\"$controller\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}