{
 "title": "Extensions",
 "tags": [
  "extensions",
  "resources"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Extension", "query": "label_values(namespace)" },
   {
    "name": "Pod",
    "query": "label_values(seed:container_cpu_usage_seconds_total:sum_by_pod{namespace=~\"extension-$Extension\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "Shows the CPU usage of selected extension controllers.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "seed:container_cpu_usage_seconds_total:sum_by_pod{namespace=~\"extension-$Extension\", pod=~\"$Pod\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Shows the memory usage of selected extension controllers.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "seed:container_memory_working_set_bytes:sum_by_pod{namespace=~\"extension-$Extension\", pod=~\"$Pod\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "description": "Shows the network I/O of the selected extension controllers.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "- seed:container_network_receive_bytes_total:sum_by_pod{namespace=~\"extension-$Extension\", pod=~\"$Pod\"}",
     "legendFormat": "{{ pod }}(receive)"
    },
    {
     "expr": "seed:container_network_transmit_bytes_total:sum_by_pod{namespace=~\"extension-$Extension\", pod=~\"$Pod\"}",
     "legendFormat": "{{ pod }}(transmit)"
    }
   ]
  }
 ]
}