{
 "title": "Fluent Bit",
 "description": "Fluent-bit metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Input Bytes Processing Rate",
   "type": "graph",
   "description": "Input bytes processing rate of all fluent-bits.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentbit_input_bytes_total[$__rate_interval])) by (pod, name)",
     "legendFormat": "{{ pod }}/{{name}}"
    }
   ]
  },
  {
   "title": "Output Bytes Processing Rate",
   "type": "graph",
   "description": "Output bytes processing rate of all fluent-bits.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_proc_bytes_total[$__rate_interval])) by (pod, name)",
     "legendFormat": "{{ pod }}/{{name}}"
    }
   ]
  },
  {
   "title": "Input Records Processing Rate",
   "type": "graph",
   "description": "Input records processing rate of all fluent-bits.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentbit_input_records_total[$__rate_interval])) by (pod, name)",
     "legendFormat": "{{ pod }}/{{name}}"
    }
   ]
  },
  {
   "title": "Output Record Processing Rate",
   "type": "graph",
   "description": "Output records processing rate of all fluent-bits.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_proc_records_total[$__rate_interval])) by (pod, name)",
     "legendFormat": "{{ pod }}/{{name}}"
    }
   ]
  },
  {
   "title": "Output Retry/Failed Rates",
   "type": "graph",
   "description": "Failed retries of the fluent-bit's output plugin.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_retries_total[$__rate_interval])) by (pod, name)",
     "legendFormat": "{{pod}} Retries to {{name}}"
    },
    {
     "expr": "sum(rate(fluentbit_output_retries_failed_total[$__rate_interval])) by (pod, name)",
     "legendFormat": "{{pod}} Failed Retries to {{ name }}"
    }
   ]
  },
  {
   "title": "Output Error Rate",
   "type": "graph",
   "description": "Errors of the fluent-bit's output plugin.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "errors/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_errors_total[$__rate_interval])) by (pod, name)",
     "legendFormat": "{{ pod }}/{{ name }}"
    }
   ]
  }
 ]
}