{
 "title": "Gardener Resource Manager",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "result",
    "label": "Reconciliation Result",
    "query": {
     "query": "label_values(controller_runtime_reconcile_total, result)"
    }
   },
   {
    "name": "url",
    "label": "Request URL",
    "query": {
     "query": "label_values(rest_client_request_latency_seconds_bucket, url)"
    }
   },
   {
    "name": "code",
    "label": "Response Code",
    "query": {
     "query": "label_values(rest_client_requests_total, code)"
    }
   },
   { "name": "percentile", "label": "Percentile", "query": "90,95,99" }
  ]
 },
 "panels": [
  { "title": "Controllers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Max Concurrent Reconciliations",
   "type": "bargauge",
   "description": "Shows the maximum number of concurrent reconciliations per controller.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(controller_runtime_max_concurrent_reconciles{job=\"gardener-resource-manager\"}) by (controller)",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Active Controller Workers",
   "type": "graph",
   "description": "Shows the active workers per controller.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "workers/s" }
   ],
   "targets": [
    {
     "expr": "sum(controller_runtime_active_workers{job=\"gardener-resource-manager\"}) by (controller)",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Number of Reconciliations For Result \"$result\"",
   "type": "graph",
   "description": "Shows the total number of reconciliations per controller.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "reconciliations/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{job=\"gardener-resource-manager\",result=~\"$result\"}[$__rate_interval])) by (controller)",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Reconciliation Errors",
   "type": "graph",
   "description": "Shows the total number of reconciliation errors per controller.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "errors/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_errors_total{job=\"gardener-resource-manager\"}[$__rate_interval])) by (controller)",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Length of Reconciliation Times (${percentile}th Percentile)",
   "type": "graph",
   "description": "Shows the length per reconciliation per controller.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($percentile/100,sum(rate(controller_runtime_reconcile_time_seconds_bucket{job=~\"gardener-resource-manager\"}[$__rate_interval])) by(le,controller))",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Reconciliation Rate",
   "type": "graph",
   "description": "Shows the reconciliation rate per controller.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "none", "label": "1/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_time_seconds_count{job=\"gardener-resource-manager\"}[$__rate_interval])) by(controller)",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  { "title": "Webhooks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Total Requests",
   "type": "graph",
   "description": "Shows the total number of admission requests being served.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "requests/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_webhook_requests_total{job=\"gardener-resource-manager\"}[$__rate_interval])) by (webhook,code)",
     "legendFormat": "{{webhook}} ({{code}})"
    }
   ]
  },
  {
   "title": "Inflight Requests",
   "type": "graph",
   "description": "Shows the current number of admission requests being served.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "requests/s" }
   ],
   "targets": [
    {
     "expr": "sum(controller_runtime_webhook_requests_in_flight{job=\"gardener-resource-manager\"}) by (webhook)",
     "legendFormat": "{{webhook}}"
    }
   ]
  },
  {
   "title": "Latency (${percentile}th Percentile)",
   "type": "graph",
   "description": "Shows the latency of processing admission requests.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($percentile/100,sum(rate(controller_runtime_webhook_latency_seconds_bucket{job=\"gardener-resource-manager\"}[$__rate_interval])) by(le,webhook))",
     "legendFormat": "{{webhook}}"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "graph",
   "description": "Shows the latency of processing admission requests.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "none", "label": "1/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_webhook_latency_seconds_count{job=\"gardener-resource-manager\"}[$__rate_interval])) by(webhook)",
     "legendFormat": "{{webhook}}"
    }
   ]
  },
  { "title": "REST Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "HTTP Requests For API Server",
   "type": "graph",
   "description": "Shows the total number of HTTP requests.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short", "label": "requests/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"gardener-resource-manager\",code=~\"$code\"}[$__rate_interval])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  { "title": "Workqueues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Queue Duration (${percentile}th Percentile)",
   "type": "graph",
   "description": "Shows how long an item stays in the workqueue before being requested.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($percentile/100,sum(rate(workqueue_queue_duration_seconds_bucket{job=~\"gardener-resource-manager\"}[$__rate_interval])) by(le,name))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Work Duration (${percentile}th Percentile)",
   "type": "graph",
   "description": "Shows how long it takes to process an item.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($percentile/100,sum(rate(workqueue_work_duration_seconds_bucket{job=\"gardener-resource-manager\"}[$__rate_interval])) by(le,name))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Work Rate",
   "type": "graph",
   "description": "Shows how many items of the workqueue are processed.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "none", "label": "1/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(workqueue_work_duration_seconds_count{job=\"gardener-resource-manager\"}[$__rate_interval])) by(name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Queue Length",
   "type": "graph",
   "description": "Shows the current length of the workqueue.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(workqueue_depth{job=\"gardener-resource-manager\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Enqueues",
   "type": "graph",
   "description": "Shows the total number of adds to the work queue.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short", "label": "adds/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(workqueue_adds_total{job=\"gardener-resource-manager\"}[$__rate_interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Retries",
   "type": "graph",
   "description": "Shows the total number of retries handled by the workqueue.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "short", "label": "retries/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(workqueue_retries_total{job=\"gardener-resource-manager\"}[$__rate_interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Longest Running Processor",
   "type": "graph",
   "description": "Shows for how many seconds the longest running processor for a workqueue has been running.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(workqueue_longest_running_processor_seconds{job=\"gardener-resource-manager\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Unfinished Work",
   "type": "graph",
   "description": "Shows for how many seconds of work has been done that is in progress and hasn't been observed by work_duration. Large values indicate stuck threads. One can deduce the number of stuck threads by observing the rate at which this increases.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(workqueue_unfinished_work_seconds{job=\"gardener-resource-manager\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}