{
 "title": "Shoot control plane resource usage by owner and container",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(metering:working_set_memory:sum_by_namespace{shoot_uid!=\"\"}, namespace)"
    }
   },
   {
    "name": "owner",
    "query": {
     "query": "label_values(metering:working_set_memory:sum_by_namespace_owner_container{shoot_uid!=\"\",namespace=~\"$namespace\"}, owner)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(metering:working_set_memory:sum_by_namespace_owner_container{shoot_uid!=\"\",namespace=~\"$namespace\",owner=~\"$owner\"}, container)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Shoot UID",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metering:cpu_usage:sum_by_namespace:avg_over_time{shoot_uid!=\"\",namespace=~\"$namespace\"}",
     "legendFormat": "{{shoot_uid}}"
    }
   ]
  },
  {
   "title": "Elapsed usage time in the current calendar month",
   "type": "stat",
   "gridPos": { "h": 2, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metering:memory_usage_seconds{shoot_uid!=\"\",namespace=~\"$namespace\"}",
     "legendFormat": "CPU, Memory, Network usage time in {{year}}/{{month}} "
    },
    {
     "expr": "metering:disk_usage_seconds{shoot_uid!=\"\",namespace=~\"$namespace\"}",
     "legendFormat": "Disk usage time in {{year}}/{{month}} "
    }
   ]
  },
  {
   "title": "Average resource usage in the current calendar month when the cluster was active",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metering:cpu_usage:sum_by_namespace:avg_over_time{shoot_uid!=\"\",namespace=~\"$namespace\"}",
     "legendFormat": "CPU usage"
    },
    {
     "expr": "metering:cpu_requests:sum_by_namespace:avg_over_time{shoot_uid!=\"\",namespace=~\"$namespace\"}",
     "legendFormat": "CPU requests"
    },
    {
     "expr": "metering:memory_usage:sum_by_namespace:avg_over_time{shoot_uid!=\"\",namespace=~\"$namespace\"}",
     "legendFormat": "Memory usage"
    },
    {
     "expr": "metering:working_set_memory:sum_by_namespace:avg_over_time{shoot_uid!=\"\",namespace=~\"$namespace\"}",
     "legendFormat": "Working Set Memory usage"
    },
    {
     "expr": "metering:memory_requests:sum_by_namespace:avg_over_time{shoot_uid!=\"\",namespace=~\"$namespace\"}",
     "legendFormat": "Memory requests"
    },
    {
     "expr": "metering:persistent_volume_usage:sum_by_namespace:avg_over_time{shoot_uid!=\"\",namespace=~\"$namespace\"}",
     "legendFormat": "Disk usage"
    },
    {
     "expr": "metering:persistent_volume_claims:sum_by_namespace:avg_over_time{shoot_uid!=\"\",namespace=~\"$namespace\"}",
     "legendFormat": "Disk requests"
    },
    {
     "expr": "metering:network_receive:sum_by_namespace{shoot_uid!=\"\",namespace=~\"$namespace\"} + metering:network_transmit:sum_by_namespace{shoot_uid!=\"\",namespace=~\"$namespace\"}",
     "legendFormat": "Network"
    }
   ]
  },
  {
   "title": "Current resource usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metering:cpu_usage:sum_by_namespace{shoot_uid!=\"\",namespace=~\"$namespace\"}",
     "legendFormat": "CPU usage"
    },
    {
     "expr": "metering:cpu_requests:sum_by_namespace{shoot_uid!=\"\",namespace=~\"$namespace\"}",
     "legendFormat": "CPU requests"
    },
    {
     "expr": "metering:memory_usage:sum_by_namespace{shoot_uid!=\"\",namespace=~\"$namespace\"}",
     "legendFormat": "Memory usage"
    },
    {
     "expr": "metering:working_set_memory:sum_by_namespace{shoot_uid!=\"\",namespace=~\"$namespace\"}",
     "legendFormat": "Working Set Memory usage"
    },
    {
     "expr": "metering:memory_requests:sum_by_namespace{shoot_uid!=\"\",namespace=~\"$namespace\"}",
     "legendFormat": "Memory requests"
    },
    {
     "expr": "metering:persistent_volume_usage:sum_by_namespace{shoot_uid!=\"\",namespace=~\"$namespace\"}",
     "legendFormat": "Disk usage"
    },
    {
     "expr": "metering:persistent_volume_claims:sum_by_namespace{shoot_uid!=\"\",namespace=~\"$namespace\"}",
     "legendFormat": "Disk requests"
    },
    {
     "expr": "metering:network_receive:sum_by_namespace{shoot_uid!=\"\",namespace=~\"$namespace\"} + metering:network_transmit:sum_by_namespace{shoot_uid!=\"\",namespace=~\"$namespace\"}",
     "legendFormat": "Network"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "CPU" }
   ],
   "targets": [
    {
     "expr": "metering:cpu_usage:sum_by_namespace{shoot_uid!=\"\",namespace=~\"$namespace\"}",
     "legendFormat": "Total {{shoot_uid}}"
    },
    {
     "expr": "sum without(shoot_uid) (metering:cpu_usage:sum_by_namespace_owner_container{shoot_uid!=\"\",namespace=~\"$namespace\",owner=~\"$owner\",container=~\"$container\"})",
     "legendFormat": "{{owner}} / {{container}}"
    }
   ]
  },
  {
   "title": "CPU requests",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "CPU" }
   ],
   "targets": [
    {
     "expr": "metering:cpu_requests:sum_by_namespace{shoot_uid!=\"\",namespace=~\"$namespace\"}",
     "legendFormat": "Total {{shoot_uid}}"
    },
    {
     "expr": "sum without(shoot_uid) (metering:cpu_requests:sum_by_namespace_owner_container{shoot_uid!=\"\",namespace=~\"$namespace\",owner=~\"$owner\",container=~\"$container\"})",
     "legendFormat": "{{owner}} / {{container}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "metering:memory_usage:sum_by_namespace{shoot_uid!=\"\",namespace=~\"$namespace\"}",
     "legendFormat": "Total {{shoot_uid}}"
    },
    {
     "expr": "sum without(shoot_uid) (metering:memory_usage:sum_by_namespace_owner_container{shoot_uid!=\"\",namespace=~\"$namespace\",owner=~\"$owner\",container=~\"$container\"})",
     "legendFormat": "{{owner}} / {{container}}"
    }
   ]
  },
  {
   "title": "Working Set Memory usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "metering:working_set_memory:sum_by_namespace{shoot_uid!=\"\",namespace=~\"$namespace\"}",
     "legendFormat": "Total {{shoot_uid}}"
    },
    {
     "expr": "sum without(shoot_uid) (metering:working_set_memory:sum_by_namespace_owner_container{shoot_uid!=\"\",namespace=~\"$namespace\",owner=~\"$owner\",container=~\"$container\"})",
     "legendFormat": "{{owner}} / {{container}}"
    }
   ]
  },
  {
   "title": "Memory requests",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "metering:memory_requests:sum_by_namespace{shoot_uid!=\"\",namespace=~\"$namespace\"}",
     "legendFormat": "Total {{shoot_uid}}"
    },
    {
     "expr": "sum without(shoot_uid) (metering:memory_requests:sum_by_namespace_owner_container{shoot_uid!=\"\",namespace=~\"$namespace\",owner=~\"$owner\",container=~\"$container\"})",
     "legendFormat": "{{owner}} / {{container}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Network Receive",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "metering:network_receive:sum_by_namespace{shoot_uid!=\"\",namespace=~\"$namespace\"}",
     "legendFormat": "Total {{shoot_uid}}"
    },
    {
     "expr": "sum without(shoot_uid) (metering:network_receive:sum_by_namespace_owner{shoot_uid!=\"\",namespace=~\"$namespace\",owner=~\"$owner\"})",
     "legendFormat": "{{owner}}"
    }
   ]
  },
  {
   "title": "Network Transmit",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "metering:network_transmit:sum_by_namespace{shoot_uid!=\"\",namespace=~\"$namespace\"}",
     "legendFormat": "Total {{shoot_uid}}"
    },
    {
     "expr": "sum without(shoot_uid) (metering:network_transmit:sum_by_namespace_owner{shoot_uid!=\"\",namespace=~\"$namespace\",owner=~\"$owner\"})",
     "legendFormat": "{{owner}}"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Persistent Volume Usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "metering:persistent_volume_usage:sum_by_namespace{shoot_uid!=\"\",namespace=~\"$namespace\"}",
     "legendFormat": "Total {{shoot_uid}}"
    },
    {
     "expr": "sum without(shoot_uid) (metering:persistent_volume_usage:sum_by_namespace_owner{shoot_uid!=\"\",namespace=~\"$namespace\",owner=~\"$owner\"})",
     "legendFormat": "{{owner}}"
    }
   ]
  },
  {
   "title": "Persistent Volume Claims",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "metering:persistent_volume_claims:sum_by_namespace{shoot_uid!=\"\",namespace=~\"$namespace\"}",
     "legendFormat": "Total {{shoot_uid}}"
    },
    {
     "expr": "sum without(shoot_uid) (metering:persistent_volume_claims:sum_by_namespace_owner{shoot_uid!=\"\",namespace=~\"$namespace\",owner=~\"$owner\"})",
     "legendFormat": "{{owner}}"
    }
   ]
  }
 ]
}