{
 "title": "Shoot control plane resource usage overview",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(metering:working_set_memory:sum_by_namespace{shoot_uid!=\"\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Shoot Cluster Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(metering:memory_usage_seconds{shoot_uid!=\"\"})",
     "legendFormat": "Current"
    },
    {
     "expr": "count(metering:memory_usage_seconds:this_month{shoot_uid!=\"\"}) by (year, month)",
     "legendFormat": "Total in {{year}}/{{month}}"
    }
   ]
  },
  {
   "title": "Average CPU Usage per Shoot Cluster",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(metering:cpu_usage:sum_by_namespace:avg_over_time:this_month{shoot_uid!=\"\"})",
     "legendFormat": "Minimum"
    },
    {
     "expr": "quantile(0.5, metering:cpu_usage:sum_by_namespace:avg_over_time:this_month{shoot_uid!=\"\"})",
     "legendFormat": "Median"
    },
    {
     "expr": "max(metering:cpu_usage:sum_by_namespace:avg_over_time:this_month{shoot_uid!=\"\"})",
     "legendFormat": "Maximum"
    },
    {
     "expr": "avg(metering:cpu_usage:sum_by_namespace:avg_over_time:this_month{shoot_uid!=\"\"})",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Average Memory Usage per Shoot Cluster",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(metering:memory_usage:sum_by_namespace:avg_over_time:this_month{shoot_uid!=\"\"})",
     "legendFormat": "Minimum"
    },
    {
     "expr": "quantile(0.5, metering:memory_usage:sum_by_namespace:avg_over_time:this_month{shoot_uid!=\"\"})",
     "legendFormat": "Median"
    },
    {
     "expr": "max(metering:memory_usage:sum_by_namespace:avg_over_time:this_month{shoot_uid!=\"\"})",
     "legendFormat": "Maximum"
    },
    {
     "expr": "avg(metering:memory_usage:sum_by_namespace:avg_over_time:this_month{shoot_uid!=\"\"})",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Average Network Usage per Shoot Cluster",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(metering:network_receive:sum_by_namespace:avg_over_time:this_month{shoot_uid!=\"\"}+metering:network_transmit:sum_by_namespace:avg_over_time:this_month{shoot_uid!=\"\"})",
     "legendFormat": "Minimum"
    },
    {
     "expr": "quantile(0.5, metering:network_receive:sum_by_namespace:avg_over_time:this_month{shoot_uid!=\"\"}+metering:network_transmit:sum_by_namespace:avg_over_time:this_month{shoot_uid!=\"\"})",
     "legendFormat": "Median"
    },
    {
     "expr": "max(metering:network_receive:sum_by_namespace:avg_over_time:this_month{shoot_uid!=\"\"}+metering:network_transmit:sum_by_namespace:avg_over_time:this_month{shoot_uid!=\"\"})",
     "legendFormat": "Maximum"
    },
    {
     "expr": "avg(metering:network_receive:sum_by_namespace:avg_over_time:this_month{shoot_uid!=\"\"}+metering:network_transmit:sum_by_namespace:avg_over_time:this_month{shoot_uid!=\"\"})",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Average Working Set Memory Usage per Shoot Cluster",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(metering:working_set_memory:sum_by_namespace:avg_over_time:this_month{shoot_uid!=\"\"})",
     "legendFormat": "Minimum"
    },
    {
     "expr": "quantile(0.5, metering:working_set_memory:sum_by_namespace:avg_over_time:this_month{shoot_uid!=\"\"})",
     "legendFormat": "Median"
    },
    {
     "expr": "max(metering:working_set_memory:sum_by_namespace:avg_over_time:this_month{shoot_uid!=\"\"})",
     "legendFormat": "Maximum"
    },
    {
     "expr": "avg(metering:working_set_memory:sum_by_namespace:avg_over_time:this_month{shoot_uid!=\"\"})",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Average monthly shoot resource usage of currently existing shoot clusters",
   "type": "table",
   "description": "Note: Memory usage time is identical to the CPU and Network usage time. For simplicity's sake, only memory usage time is listed in this table.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (namespace, shoot_uid) (metering:cpu_usage:sum_by_namespace:avg_over_time{shoot_uid!=\"\",namespace=~\"$namespace\"})",
     "legendFormat": "CPU usage"
    },
    {
     "expr": "sum by (shoot_uid) (metering:cpu_requests:sum_by_namespace:avg_over_time{shoot_uid!=\"\",namespace=~\"$namespace\"})",
     "legendFormat": "CPU requests"
    },
    {
     "expr": "sum by (shoot_uid) (metering:working_set_memory:sum_by_namespace:avg_over_time{shoot_uid!=\"\",namespace=~\"$namespace\"})",
     "legendFormat": "Working Set Memory usage"
    },
    {
     "expr": "sum by (shoot_uid) (metering:memory_usage:sum_by_namespace:avg_over_time{shoot_uid!=\"\",namespace=~\"$namespace\"})",
     "legendFormat": "Memory Usage"
    },
    {
     "expr": "sum by (shoot_uid) (metering:memory_requests:sum_by_namespace:avg_over_time{shoot_uid!=\"\",namespace=~\"$namespace\"})",
     "legendFormat": "Memory requests"
    },
    {
     "expr": "sum by (shoot_uid) (metering:persistent_volume_usage:sum_by_namespace:avg_over_time{shoot_uid!=\"\",namespace=~\"$namespace\"})",
     "legendFormat": "Disk usage"
    },
    {
     "expr": "sum by (shoot_uid) (metering:persistent_volume_claims:sum_by_namespace:avg_over_time{shoot_uid!=\"\",namespace=~\"$namespace\"})",
     "legendFormat": "Disk requests"
    },
    {
     "expr": "sum by (shoot_uid) (metering:network_receive:sum_by_namespace:avg_over_time{shoot_uid!=\"\",namespace=~\"$namespace\"} + metering:network_transmit:sum_by_namespace:avg_over_time{shoot_uid!=\"\",namespace=~\"$namespace\"})",
     "legendFormat": "Network"
    },
    {
     "expr": "sum by (shoot_uid) (metering:memory_usage_seconds{shoot_uid!=\"\",namespace=~\"$namespace\"})",
     "legendFormat": "Memory Usage Time"
    },
    {
     "expr": "sum by (shoot_uid) (metering:disk_usage_seconds{shoot_uid!=\"\",namespace=~\"$namespace\"})",
     "legendFormat": "Disk Usage Time"
    }
   ]
  },
  {
   "title": "Calendar month average shoot resource usage including deleted shoot clusters",
   "type": "table",
   "description": "Note: Memory usage time is identical to the CPU and Network usage time. For simplicity's sake, only memory usage time is listed in this table.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (namespace, shoot_uid) (metering:cpu_usage:sum_by_namespace:avg_over_time:this_month{shoot_uid!=\"\",namespace=~\"$namespace\"})",
     "legendFormat": "CPU usage"
    },
    {
     "expr": "sum by (shoot_uid) (metering:cpu_requests:sum_by_namespace:avg_over_time:this_month{shoot_uid!=\"\",namespace=~\"$namespace\"})",
     "legendFormat": "CPU requests"
    },
    {
     "expr": "sum by (shoot_uid) (metering:working_set_memory:sum_by_namespace:avg_over_time:this_month{shoot_uid!=\"\",namespace=~\"$namespace\"})",
     "legendFormat": "Working Set Memory usage"
    },
    {
     "expr": "sum by (shoot_uid) (metering:memory_usage:sum_by_namespace:avg_over_time:this_month{shoot_uid!=\"\",namespace=~\"$namespace\"})",
     "legendFormat": "Memory Usage"
    },
    {
     "expr": "sum by (shoot_uid) (metering:memory_requests:sum_by_namespace:avg_over_time:this_month{shoot_uid!=\"\",namespace=~\"$namespace\"})",
     "legendFormat": "Memory requests"
    },
    {
     "expr": "sum by (shoot_uid) (metering:persistent_volume_usage:sum_by_namespace:avg_over_time:this_month{shoot_uid!=\"\",namespace=~\"$namespace\"})",
     "legendFormat": "Disk usage"
    },
    {
     "expr": "sum by (shoot_uid) (metering:persistent_volume_claims:sum_by_namespace:avg_over_time:this_month{shoot_uid!=\"\",namespace=~\"$namespace\"})",
     "legendFormat": "Disk requests"
    },
    {
     "expr": "sum by (shoot_uid) (metering:network_receive:sum_by_namespace:avg_over_time:this_month{shoot_uid!=\"\",namespace=~\"$namespace\"} + metering:network_transmit:sum_by_namespace:avg_over_time:this_month{shoot_uid!=\"\",namespace=~\"$namespace\"})",
     "legendFormat": "Network"
    },
    {
     "expr": "sum by (shoot_uid) (metering:memory_usage_seconds:this_month{shoot_uid!=\"\",namespace=~\"$namespace\"})",
     "legendFormat": "Memory Usage Time"
    },
    {
     "expr": "sum by (shoot_uid) (metering:disk_usage_seconds:this_month{shoot_uid!=\"\",namespace=~\"$namespace\"})",
     "legendFormat": "Disk Usage Time"
    }
   ]
  }
 ]
}