{
 "title": "Controller Runtime / Webhooks",
 "tags": [ "controller-runtime" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(controller_runtime_webhook_requests_total{}, job)"
    }
   },
   {
    "name": "webhook",
    "query": {
     "query": "label_values(controller_runtime_webhook_requests_total{job=\"$job\"},webhook)"
    }
   },
   {
    "name": "code",
    "query": {
     "query": "label_values(controller_runtime_webhook_requests_total{job=\"$job\"},code)"
    }
   },
   { "name": "percentile", "query": "50,90,99" }
  ]
 },
 "panels": [
  {
   "title": "Total Requests by webhook",
   "type": "graph",
   "description": "Shows the total number of admission requests being served per webhook.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "requests/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_webhook_requests_total{job=\"gardener-resource-manager\",webhook=~\"$webhook\"}[$__rate_interval])) by (webhook)",
     "legendFormat": "{{webhook}}"
    }
   ]
  },
  {
   "title": "Total Requests by code",
   "type": "graph",
   "description": "Shows the total number of admission requests being served per code.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "requests/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_webhook_requests_total{job=\"gardener-resource-manager\",webhook=~\"$webhook\"}[$__rate_interval])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Inflight Requests",
   "type": "graph",
   "description": "Shows the current number of admission requests being served.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "requests/s" }
   ],
   "targets": [
    {
     "expr": "sum(controller_runtime_webhook_requests_in_flight{job=\"gardener-resource-manager\",webhook=~\"$webhook\"}) by (webhook)",
     "legendFormat": "{{webhook}}"
    }
   ]
  },
  {
   "title": "Latency (${percentile}th Percentile)",
   "type": "graph",
   "description": "Shows the latency of processing admission requests.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($percentile/100,sum(rate(controller_runtime_webhook_latency_seconds_bucket{job=\"gardener-resource-manager\",webhook=~\"$webhook\"}[$__rate_interval])) by(le,webhook))",
     "legendFormat": "{{webhook}}"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "graph",
   "description": "Shows the latency of processing admission requests.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "1/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_webhook_latency_seconds_count{job=\"gardener-resource-manager\",webhook=~\"$webhook\"}[$__rate_interval])) by(webhook)",
     "legendFormat": "{{webhook}}"
    }
   ]
  }
 ]
}