#!/bin/bash
#
# Copyright (c) 2018 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

DEV_DIR=$(dirname "${0}")/../../dev
EXAMPLE_DIR=$(dirname "${0}")/../../example
LANDSCAPER_DIR=$(dirname "${0}")/../../landscaper

source $(dirname "${0}")/common/helpers
kubernetes_env="$(k8s_env)"
PLATFORM='-'$( uname -m ); case $PLATFORM in -ppc64le|-arm64) ;; *) PLATFORM=;; esac

# test if we are running against a Minikube, Docker or kind Kubernetes local setup
case "${kubernetes_env}" in
    $NODELESS)
        echo "Found Nodeless Kubernetes ..."
        ;;
    $REMOTE)
        echo "Found Remote Kubernetes ..."
        ;;
    $KIND)
        echo "Found kind ..."
        LOCAL_K8S_HOST_IP=localhost
        ETCD_DATA_DIR="/var/lib/docker/gardener/gardener-etcd"
        ;;
    $DOCKER_FOR_DESKTOP)
        echo "Found Docker Kubernetes ..."
        LOCAL_K8S_HOST_IP=localhost
        ETCD_DATA_DIR="/Users/$(whoami)/.docker/gardener-etcd"
        ;;
    $MINIKUBE)
        echo "Found Minikube ..."
        LOCAL_K8S_HOST_IP="$(minikube ip)"
        ETCD_DATA_DIR="/data/gardener-etcd"
        if [[ "$(uname)" == "Darwin" ]]; then
          echo "After OSX sleep, minikube's time is off."
          echo "This results in x509 certificate auth to not work for shoot certificates"
          minikube ssh -- docker run -i --rm --privileged --pid=host alpine:3 nsenter -t 1 -m -u -n -i date -u $(date -u +%m%d%H%M%Y)
        fi
        ;;
 esac

mkdir -p ${DEV_DIR}/landscaper

cp ${EXAMPLE_DIR}/20-componentconfig-*.yaml ${DEV_DIR}/
cp ${LANDSCAPER_DIR}/pkg/gardenlet/example/gardenlet-landscaper-imports.yaml ${DEV_DIR}/landscaper
cp ${LANDSCAPER_DIR}/pkg/gardenlet/example/run-locally/gardenlet-landscaper-component-descriptor-list.yaml ${DEV_DIR}/landscaper

kubectl apply -f ${EXAMPLE_DIR}/00-namespace-garden.yaml
kubectl apply -f ${EXAMPLE_DIR}/00-namespace-garden-dev.yaml

if [ "${kubernetes_env}" != $NODELESS ] && [ "${kubernetes_env}" != $REMOTE ] ; then
  cat <<EOF | kubectl apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd
  namespace: garden
spec:
  replicas: 1
  selector:
    matchLabels:
      run: etcd
  template:
    metadata:
      labels:
        run: etcd
    spec:
      containers:
      - image: quay.io/coreos/etcd:v3.3.17${PLATFORM}
        name: etcd
        command:
        - etcd
        - -advertise-client-urls=http://${LOCAL_K8S_HOST_IP}:2379
        - -listen-client-urls=http://0.0.0.0:2379
        - -data-dir=/etcd-data
        volumeMounts:
        - mountPath: /etcd-data
          name: data
      volumes:
      - name: data
        hostPath:
          path: ${ETCD_DATA_DIR}
---
apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: garden
spec:
  ports:
  - port: 2379
    nodePort: 32379
  selector:
    run: etcd
  type: NodePort
EOF
fi

mkdir -p ${DEV_DIR}/tls

cat <<EOF > "${DEV_DIR}/tls/gardener-apiserver-ca.crt"
-----BEGIN CERTIFICATE-----
MIIFRDCCAyygAwIBAgIUaZ5FZ0Uu8qUD09cFHnFo4TKJzOIwDQYJKoZIhvcNAQEN
BQAwOjEPMA0GA1UEBhMGRXVyb3BlMREwDwYDVQQKEwhHYXJkZW5lcjEUMBIGA1UE
AxMLZ2FyZGVuZXIgY2EwHhcNMjAwNzE1MDgzMTAwWhcNMjUwNzE0MDgzMTAwWjA6
MQ8wDQYDVQQGEwZFdXJvcGUxETAPBgNVBAoTCEdhcmRlbmVyMRQwEgYDVQQDEwtn
YXJkZW5lciBjYTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBANlSwk5M
40MQM9J4ozYCWxu9AsdUDhnF9RZAQE/JLLJLt5uST9/6O+z301oc0+VRxpS+Q0hI
5Dv0vsKY2txWareif07OG67B9BGsrbg6I/Qr4DRMbnZz2MKxTqJ3Pj8BXSsmAdjP
ZQt1ChIkDFPukRcjKwrUL1jF1/3CqKPAUw1f071oEhfO+3k9D2Z3n5670my4fGJa
Z67HPWSxbx6i3qX0m2HjKj8UAYntlVN5bkI+xRIEA0pk5RJnJ+0ld/r0BQW9/3Mh
v0qWYfiK0Wif3dXMS7jkSf47wKwb2QO8Y0yjnYS+yR6nwQtvtB1JOMiswsxy5cQL
hb24NRHmfZ+2rbMCaF9oeH4JPLbfzWEKeEtdWEEvzQcrpmJBf/3D8Kopgj8x27eX
Eq0p+NsjNo2W8+VyGxKH2z23YiXycaDs7ycoLG5+HuP/nSNKPrBgFlONengl7BYb
bz7vlwfRFCygEE/dvFzJ4a51Cddy/6Own6vrvdhJhIr3wpdUHld8XZDW1KMm+rgf
6Pv09Dbx4RgfAIarqcn6uiz8NYvk7xcj+iTznAiSgBm4Bw0lEbmxWRGVQiyS0rJ1
jy9YFLjJEjf3VOsUDdupa+5s25FYfgP+tUjF4cQXNakDsYac0DEsobWKEPcx4qUT
CbyWfn0rQVWcAvnUIgdblNM2AemyCzuUyLaJAgMBAAGjQjBAMA4GA1UdDwEB/wQE
AwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBRUBRei2YCpiyOY1ltU6bX4
W0yCTjANBgkqhkiG9w0BAQ0FAAOCAgEAjHHxk3p+6o8VLZtNR5Yq4dkoxdajl6xw
8xiLM81WEUFzjf4Z1Q1h54n2zcLCbocWCg6BDz9lxrkrix5Eyqo4Xpt+repXu5cJ
Sa4k3bXXZpzmTFuqIcBXTWaYvIdgBumMcuAY6jfnuqptX0mHoMQQXf5OT0pIYKq9
CkjDZszXzafYFd9F3oYuz9z3iP++thhG/PhubirmiSyPxDf2rAt3iinfVLZBzYFm
pUK8fzOfBx8IukLBL/+kmfxAolrGQbCvKf9OkO/ZemFNz0ww526UcV75twhwgnwL
7X+ZKTPzYZomv9t09fBNfpw7R1RjEvPYLX2/FkHIwvNguNfjcXP2Y8+ICZEE+1YL
g+0+TMygwfhXyBNgWBMgRqPXtDxWkQ/eXyNmE5cm3FT4D+ENEvfzLKc43SMpoOAp
6V2PRXXJa+44GucALClv06ZGH387GfEr7xHDDcn9s8V7TMhYaSFWtmpCHRHPAe7T
HlAK9I4g2oexSLfyUr08OacPafpQFRl47TqvSaYK/qB68DRaiE/M6uQbisC3aZ80
XmnX7AFAgfqX3mMSo4PFF6Tk6VD0B9ScizTPQSf4VpOAHV1GhKgbcSihiKjs7jIT
7xz7VmLAuAZxLSDWh5EYWi0H1BIhEZbO4yOuMtZ9H6Aooow6MnnaDLTAh+Rjki7w
FZ+O4VgtPps=
-----END CERTIFICATE-----
EOF

cat <<EOF > "${DEV_DIR}/tls/gardener-apiserver-ca.key"
-----BEGIN RSA PRIVATE KEY-----
MIIJKgIBAAKCAgEA2VLCTkzjQxAz0nijNgJbG70Cx1QOGcX1FkBAT8kssku3m5JP
3/o77PfTWhzT5VHGlL5DSEjkO/S+wpja3FZqt6J/Ts4brsH0EaytuDoj9CvgNExu
dnPYwrFOonc+PwFdKyYB2M9lC3UKEiQMU+6RFyMrCtQvWMXX/cKoo8BTDV/TvWgS
F877eT0PZnefnrvSbLh8Ylpnrsc9ZLFvHqLepfSbYeMqPxQBie2VU3luQj7FEgQD
SmTlEmcn7SV3+vQFBb3/cyG/SpZh+IrRaJ/d1cxLuORJ/jvArBvZA7xjTKOdhL7J
HqfBC2+0HUk4yKzCzHLlxAuFvbg1EeZ9n7atswJoX2h4fgk8tt/NYQp4S11YQS/N
ByumYkF//cPwqimCPzHbt5cSrSn42yM2jZbz5XIbEofbPbdiJfJxoOzvJygsbn4e
4/+dI0o+sGAWU416eCXsFhtvPu+XB9EULKAQT928XMnhrnUJ13L/o7Cfq+u92EmE
ivfCl1QeV3xdkNbUoyb6uB/o+/T0NvHhGB8Ahqupyfq6LPw1i+TvFyP6JPOcCJKA
GbgHDSURubFZEZVCLJLSsnWPL1gUuMkSN/dU6xQN26lr7mzbkVh+A/61SMXhxBc1
qQOxhpzQMSyhtYoQ9zHipRMJvJZ+fStBVZwC+dQiB1uU0zYB6bILO5TItokCAwEA
AQKCAgEAjTQel+2RREPEyB4mPbNuKym2InlU6B4dTqXUo4KdDgPwep6oU2ktgpzL
sKNGcpudoYu1/8OMuAAf6iSTH9LuZ/6nJTb5+aR/xvQhs6/jKIVRmemHZGOFFYtL
Anjj8uAZ/y0kyhCHINidAIh3khlSIGxzTQfs84so+fJ+zFbsH6aB13FFQD72WiH4
XaWgCu0Snh2IhAclkwRVuZUoFAnTDJVQWFvXWUDQdyPtgF1H7LcIKNp+oNnJlRl9
cbKEsIPYt5Bp6A6nUflAEtNvmME2y/F/ydRa11tPpwQ5DxpakrNEZ7nmx4pL/fhI
WTb4NDs8HscQzz6FWW3U3ZqbSSjS1mdxZvhzMuyg+b6qX+Z6ISEpMm+i2SKwUrHn
USQH+jrqO3T2VcTT+9aywYCp/SX2sLvWw1jT9P+ym689C+Hu4cCF2MPvg42Pia4t
ZJroOUMINt5lVpuMXUwELbF2RYyINIy4sdIQcxVx1FDQKdt8OvJJfLIZDEq1u4fZ
Q3y+uYUxqONQumr5alZhgEbZpeIqMjS+7AcqE2/VUjEyqs2TMQX4yVRrt9sN00AJ
2uSbnq6anuqcZPHHNmCG9eWQJWc1+IMMGjdwRicaBnXT0WT24ugMYvkc4oOd/TGr
miDpB7qmEOQKASgBAA0WDsA5ckJg4KYby+wUujCnHvtBvqPoRLkCggEBANpxGtik
6zkEJVJttdAe7j060qV/ibtDAIP46T/J0gCTgH25cjHsHUuX1tdfwB3oEuKhY9uO
REaTp97W2AclVIWzj2V2b5WdOn6j/HhwVHx3JE7ZLkZ0Lr/MLUgZ24CZL5gWgafJ
qkITmcGwDMdUzRNIfaFxl3rMGAwHFQCQsvumB4nQg8bbxmVLaFv14xAP7JdTUtBp
dLTSoBluvnmfJC2remkB1NOOBuXp1oZn/dSoGuTQ6H3Wn4TjMPG0mlP5ov53Gl//
OlXfadqnHqVj6Ez0CODhgXNghNfsnq4ktlFLZ2MwrNeP3KkmscJYVllvEbpG4JKd
FkwudoLlVRO3D38CggEBAP6wa7ZfujReSQCfJsSZZ7wZOdKYLXWGkTu0unxICmoN
ER66BRKPawYBi88CqrM7CTe9gHSut6XuLdegDnY24Y9SEA8MndeBo6v/yFsMZw2j
L3CzkwvgNXhrbx22kYF/UeB+5TqJZP3lJP3jUpgFzYcvwQ3hr+EiLa2dlQ0nyhn5
wB/g6JyBpwUAUAteSICHXegI+qVLcyRnib/PGkWuAxxhXgwf6o11P0CtGywOjUnG
MxMYgTK+wM/Ohgvr9d+A8SVM5ZoEgdV0MOtNkGVHqY9PLbTYOhPUlEIBI98a4/Qd
4ThnUX9WeeRib8lKzuzaUv/MNKY3AYBPCIrTW3NIvfcCggEALigoHA79BRczK6+y
8z8V6Co9yGqil8cYnMpDvw7OKQEB7Y756kKSDh8PboL0/VzEYM7pYsM0+hTJK/UJ
wLjKm1XNvwq/mUWXzpqoBmr17zbdnSuW85wpJK3oA4wzLYEw5VocG3ApYbzyiFLC
4HuyuZhfs3VlJLVrf18fuPbaWwJCJYTB04ss6Mp+SrAyQnqa637XyOH/nxXCbp1P
8jMGWgAZ5YZVij5AhuRaSBxBLmY3CJJ8DdsD6fh3pxsaYRQmtM5F7HLpyKtkmqcl
ep0ZwOjv11TPHaoPZ/C/ttxbCeJ8/iCS5Rmo7rUWapJv7IXjoRDI8zHuPDq1IAOF
bp0H0QKCAQEA1Nq06rKOeH3kHTTlvaFH5RhgDvVH6NUSRAgDYyMCMSfCix+EZcKe
+2IHanccGrbYOVGTLfFnYrHwdik6bOnpEVLQQQOWVyntlC4tUIrJBcjAOTybRG2Z
wo5nSznt2YCC+VCUW5vAX8FGbTmzKYKQBs+OVP+tckaSTmtIyrnaWmM0gnABd+uT
nsZoH1go1+JKRUZb1BF+pYoywa9gkaOgzfNCGngCGz9GIdOKxgNTabjPrsHoGHT7
x7EerpAB6U1mPHpL2bCyoaZ9y+oDJ+IAf9j4pg+gWjprvc4eILPkl3zxYaZXokiv
joQGUQDId4LvowETb2bBRm7HAN8rqum8eQKCAQEAgZjhxE6S5QBSXd42EZQxZh2W
GEkOlJ1xvwjQCpXaQaE5692I9J+mqAHNf46A4LAGFsmYrmYyTSK4e9eAjyeB4Nvi
FEZOQqELcylqlPQrWKNw0z9/POOJ+zfIa5IjF4R8BaWPI5BX3TaErNunXbgkXXMb
+DUV1xMC5C0vONl0Nv5xY/YaRQSS2RaHh6PYvQNcu082r9sy/sutE6z0qYUbZ6Eh
QNIE2SVficeUlWQ2TIGIeu5UaYKL6u1oywxRbDX7lU73Vs+uoxsWlkeL6Lg/g3JM
eAWTg7HrpQRnE3/wd1OMC5ERc+F17dJX21ChvS1q9OqPJUc95kKpuI9rRaqlRw==
-----END RSA PRIVATE KEY-----
EOF

cat <<EOF > "${DEV_DIR}/tls/gardener-apiserver.crt"
-----BEGIN CERTIFICATE-----
MIIELTCCAhWgAwIBAgIUNOSE1llgkYCtLo01d1x+ZjRLPj4wDQYJKoZIhvcNAQEN
BQAwOjEPMA0GA1UEBhMGRXVyb3BlMREwDwYDVQQKEwhHYXJkZW5lcjEUMBIGA1UE
AxMLZ2FyZGVuZXIgY2EwHhcNMjAwNzE1MDgzMzAwWhcNMjUwNzE0MDgzMzAwWjBP
MQswCQYDVQQGEwJVUzELMAkGA1UECBMCQ0ExFjAUBgNVBAcTDVNhbiBGcmFuY2lz
Y28xGzAZBgNVBAMTEmdhcmRlbmVyLWFwaXNlcnZlcjBZMBMGByqGSM49AgEGCCqG
SM49AwEHA0IABH+zkKU1GT8ZsyPEvISnX9DzSR6gDtdD2NevkCcr1nucgkGQsMhw
qxNrENYvHlpPgpmutuM1BzKN/j9pbbO2/3ajgeAwgd0wDgYDVR0PAQH/BAQDAgWg
MBMGA1UdJQQMMAoGCCsGAQUFBwMBMAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFF5V
spjSVkl3pbp1B+MmcWjTtVIrMB8GA1UdIwQYMBaAFFQFF6LZgKmLI5jWW1Tptfhb
TIJOMGgGA1UdEQRhMF+CEmdhcmRlbmVyLWFwaXNlcnZlcoIZZ2FyZGVuZXItYXBp
c2VydmVyLmdhcmRlboIdZ2FyZGVuZXItYXBpc2VydmVyLmdhcmRlbi5zdmOCCWxv
Y2FsaG9zdIcEfwAAATANBgkqhkiG9w0BAQ0FAAOCAgEApP/HKCzG//3574/gFWFZ
gRPyqIGkbIyA4Tm8fS5cnj9MS1kInCBrh6wznPNYlbRlcHk0XrydD+1sr3tUze1h
0VFprTJ4gRPeeeGlhqdu6yCvgpVG89gNr2b/BPC6383+dyr/Wm/pRZA68Y0YKywg
DTOEtb93kk8r8ron4XxtTiRedkaXzSmXkoDaPMz/96YSu3QgZZ4nezrI0PSVHY5e
pHfjBeF0oIQtQifazp0HQUdxyKHmj7ud/On520G8LPV2VHhO3nxYDWnspachEtzH
vczucz8YUH6A5ESI3nqBrkAVEjealeAs2YX4yAjMGc78Etj65qBq+gHW7hiMoqm+
nw2gkxRarDZ5foC/LKf34czchZ3Ojzuu9/SRrk5HcxeuREo2PXbd9g01LuhmX3l8
MFb1ZdmSA87DrLMAGPvEewYy8Y0V5kcLnA6lelNIHO50DDCejblwQT8mHNrnGPZ4
mp3HZuimTNmmUKIMNoYaf163oMyzAopeVWroqBBe52D65T5nCiYFZstCtr3kzNjN
tlBJHT4RR3XI6OPztLe5/d8iruekzdahtRd4EV33hyGT9uXVIBIn+R3uq7zsqJMG
CUE2TgJFclIPNxPY9PvZw2kapNuroSipIWOkXzPDltYG5UCxl3WFd+KV02UT1fVg
xjmpZ1DdM8MUDXHIo+UNLzY=
-----END CERTIFICATE-----
EOF

cat <<EOF > "${DEV_DIR}/tls/gardener-apiserver.key"
-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIGTTsZQjQGbMXDsz/HGhNY6ml0V6s7nCW9ehgwb5PMHHoAoGCCqGSM49
AwEHoUQDQgAEf7OQpTUZPxmzI8S8hKdf0PNJHqAO10PY16+QJyvWe5yCQZCwyHCr
E2sQ1i8eWk+Cma624zUHMo3+P2lts7b/dg==
-----END EC PRIVATE KEY-----
EOF

mkdir -p "${DEV_DIR}/tls/gardener-admission-controller"

cat <<EOF > "${DEV_DIR}/tls/gardener-admission-controller/tls.crt"
-----BEGIN CERTIFICATE-----
MIIEEzCCAvugAwIBAgIJAKVcj0hHoSuaMA0GCSqGSIb3DQEBBQUAMEgxCzAJBgNV
BAYTAlVTMQswCQYDVQQIEwJDQTEWMBQGA1UEBxMNU2FuIEZyYW5jaXNjbzEUMBIG
A1UEAxMLZXhhbXBsZS5uZXQwHhcNMjAwOTA4MTcyMjQ2WhcNMzAwOTA2MTcyMjQ2
WjBgMQswCQYDVQQGEwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTEWMBQGA1UEBwwN
U2FuIEZyYW5jaXNjbzERMA8GA1UECgwIZ2FyZGVuZXIxETAPBgNVBAMMCGdhcmRl
bmVyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAragksFWulbJPWT/U
npbtg79pOLzsXF2RIyaUOD0HCk9QlrP8a5ojglzEvuNF8NVZeaj090nFRE51Vnou
qUgktnaHNwL3fuZcVyl5J66asiskPsfZcxT5nOC1uIegQWa8bSiqnPRbQUX3QNFS
zA9RmRSTjbRPzBm72Y2grV+vNYysuq1p8l/qs2GDJZTuLpMBYGrWxcmD6bgLy1Um
gCzK58fFnMR8Muq+jCIPsSD1FMD3Q6FVMXi58pHufxl6UgmzbO0phs5SsBE0mhIX
2OHx1VHsk/2OH4GKpOBppcyQLdtpxxfsX8Xg6gazVH5G6nT/rFVUM/S+4UJCOYyd
eQZ/QQIDAQABo4HnMIHkMAkGA1UdEwQCMAAwHQYDVR0OBBYEFAKLcqSN8WadFaaC
aMgbPTrlPUSBMAsGA1UdDwQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAgYIKwYB
BQUHAwEwgYsGA1UdEQSBgzCBgIcEfwAAAYIJbG9jYWxob3N0gh1nYXJkZW5lci1h
ZG1pc3Npb24tY29udHJvbGxlcoIkZ2FyZGVuZXItYWRtaXNzaW9uLWNvbnRyb2xs
ZXIuZ2FyZGVugihnYXJkZW5lci1hZG1pc3Npb24tY29udHJvbGxlci5nYXJkZW4u
c3ZjMA0GCSqGSIb3DQEBBQUAA4IBAQClPcPMvtjLs/XHQZ+AZ8iCC8PJlbFRp6EW
MABvamp4b/WjC05CM0/bGhxqSTriUHliQsSuxL4LjkX0y9vT1SZlXQ4ukvYh5Nlb
Ocy/OJH67ulKu+gk45P72ZDE9ctnYGY7CXqPwolPHQDYPfpp9JHlnrhctGwG79UD
ZAAbhemvzKSoyiKE/PLutGtPvcEoRi9ZDLl/6/BerTUxm1svo00FBqzUla74btuW
uViZCXagBrBGzjEK1hC6jmD4jxQJWpM1l1B0JnIaP8zG/baBtFLwR93kZKm3MabS
z8pIqr/J04+HQR+VcLkCe7kaJc/sQlN5Ov6snGPvGenPkL5gMrD6
-----END CERTIFICATE-----
EOF

cat <<EOF > "${DEV_DIR}/tls/gardener-admission-controller/tls.key"
-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEAragksFWulbJPWT/Unpbtg79pOLzsXF2RIyaUOD0HCk9QlrP8
a5ojglzEvuNF8NVZeaj090nFRE51VnouqUgktnaHNwL3fuZcVyl5J66asiskPsfZ
cxT5nOC1uIegQWa8bSiqnPRbQUX3QNFSzA9RmRSTjbRPzBm72Y2grV+vNYysuq1p
8l/qs2GDJZTuLpMBYGrWxcmD6bgLy1UmgCzK58fFnMR8Muq+jCIPsSD1FMD3Q6FV
MXi58pHufxl6UgmzbO0phs5SsBE0mhIX2OHx1VHsk/2OH4GKpOBppcyQLdtpxxfs
X8Xg6gazVH5G6nT/rFVUM/S+4UJCOYydeQZ/QQIDAQABAoIBAAlb4n5OX9ZZgcVB
l2fkonBTRIx2QhbIRCYs0hgl0ddQZvt4P8ZczEUeUswm24IbPXM9E9av9x2zTMeY
ViNxa+kZgjgIxOXl7FwWNB1bX6LyiEWJ58I4AyvdQG3tgUmFC+qmImvLD4/5AVZQ
8bFlsfQaE8mzSgmp6WHULDCr03mDQKAglJQ3oUWJFfqDQUDTf8SpRBw9S0WewpFX
hs9BF6YPxcI6rFqNge8MAUXWeBkP8BQV4S59xtq3szK4ydVCJlSyKaUYpThHiBRU
WU9VSyfA4t68ouUcSYDJ3boR9odYTYU2QdjQxYkOyyNvnqLE4kMP1x7+0zbxrKyy
1LezzkECgYEA2AM1SHzFY35oIt8Lvd0nGkCZFJ8zI8JNPV7HeaJYyfj9MpRrKD5i
2ZRDU1wZ97ML9gMwsTbasW0Nb6aLDQLdZI5boS8XfPRqGUTYkuPj+VzGRlmlx7We
KDVZzPVoNd71H4rPPjfTDGyfoI9jpjyVGJWTuKy2UQgzU/9GP2cQzsUCgYEAzc20
rEYKnpslMHe7puPG5RVOqIdRsyZmcaRbN9OwIguJELaPWx1GVkl8uCPCbZ1tmgnL
AQRCnFhlC5JlggkDdYM1Kwq4HdszHMrmxewbEnzkLMdHtg0sQU6FRSM5HHXVaW/n
6jyiD8p/aZWlo7H35DGRCFU8h4XJYJMGxa2b9k0CgYBSZqbkx/PkSEwhQUSRYNOR
yCKdIz223l/okUc2tx93rGup58QYzfOXXF9yZSfivYJKjlz8vRgfpqIBfV590CH0
QfniOryTBgmTKhgTsKs+bI2WOIxs6nMyk2d2MAdYxXxsU99KtLDlhGpALXKt715Q
yn5XbEsADkjGOhLqDL70oQKBgDagx7iCzwbSv8hhv9nI1F6yjTKG2NTo+IBp1By5
gCNJVJSvINZaqvT0hLqMI2vdQd6FgvE+JEBD5m5v6aneoqBqt445Ri4GpUabRS58
QaNiq16Hdy2HyZt8MDvt4ZcAYCmgnrq6ZXozkiaApnsRHm/gCFNh7LM8e/u6iy2l
q6RxAoGBAMa+VsZ2EPYQ+g9IFTydvkx0MZOL7b08z3F3875k+vU5EJOWanv5DF/f
nIjRtpdOj7GZ4IZYyIAdBNlgPoCX6rc8mhQA4ehT0CN/D/xIkKIz76CtCVtUhE0P
9vnayDhnZXJcT8dPkJHYucd+rydSy2PZUVU2LospQ+V9scuThRID
-----END RSA PRIVATE KEY-----

EOF

$(dirname "${0}")/dev-setup-register-gardener "$@"
