#!/bin/bash -e
#
# Copyright (c) 2021 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source $(dirname "${0}")/common/helpers
REPO_ROOT=$(dirname "${0}")/../..
ETCD_BACKUP_DIR=$REPO_ROOT/dev/local-backupbuckets
CONTAINER_PATH=/etc/gardener/local-backupbuckets

mktemp_kubeconfig
kubeconfig="$__tmp_kubeconfig"
trap cleanup_kubeconfig EXIT

export LEADER_ELECTION_NAMESPACE=garden
export GO111MODULE=on
export GARDENER_SHOOT_CLIENT=external

# sudo is required for now, as we need to manipulate /etc/hosts for making the shoot API server reachable on the host machine
SUDO=
if [ "$USER" != root ]; then
  SUDO="sudo -E"
fi

$SUDO go run \
  -mod=vendor \
  -ldflags "$("$(dirname $0)"/../get-build-ld-flags.sh)" \
  "$REPO_ROOT/cmd/gardener-extension-provider-local/main.go" \
  --kubeconfig="${KUBECONFIG:-$kubeconfig}" \
  --leader-election=false \
  --webhook-config-mode=url \
  --webhook-config-server-host=0.0.0.0 \
  --webhook-config-server-port=8444 \
  --webhook-config-url=$(get_host_address):8444 \
  --gardener-version="$(cat "$(dirname $0)/../../VERSION")" \
  --backupbucket-local-dir="$ETCD_BACKUP_DIR" \
  --backupbucket-container-mount-path="$CONTAINER_PATH"
