#!/bin/bash -e
#
# Copyright (c) 2018 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source $(dirname "${0}")/common/helpers
source $(dirname "${0}")/common/local-imagevector-overwrite

REPO_ROOT=$(dirname $0)/../..

if [[ $(k8s_env) == "$NODELESS" ]]; then
  kubeconfig="$(dirname $0)/local-garden/kubeconfigs/gardenlet.conf"
else
  mktemp_kubeconfig
  kubeconfig="$__tmp_kubeconfig"
  trap cleanup_kubeconfig EXIT
fi

file_imagevector_overwrite="$(mktemp_imagevector_overwrite github.com/gardener/gardener "$REPO_ROOT" "$REPO_ROOT"/charts)"
if [ ! -f "$file_imagevector_overwrite" ]; then
    echo "failed to generate local image vector override: $file_imagevector_overwrite"
else
  trap cleanup_imagevector_overwrite EXIT

  KUBECONFIG="${KUBECONFIG:-$kubeconfig}" \
  GARDEN_KUBECONFIG="${GARDEN_KUBECONFIG:-$kubeconfig}" \
  IMAGEVECTOR_OVERWRITE="$file_imagevector_overwrite" \
  GO111MODULE=on \
      go run \
        -mod=vendor \
        -ldflags "$("$(dirname $0)"/../get-build-ld-flags.sh)" \
        "$(dirname $0)"/../../cmd/gardenlet/main.go \
        --config="$(dirname $0)"/../../dev/20-componentconfig-gardenlet.yaml
fi
