#!/usr/bin/env bash
#
# Copyright 2022 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

source $(dirname "${0}")/common/helpers

mktemp_kubeconfig
kubeconfig="$__tmp_kubeconfig"
trap cleanup_kubeconfig EXIT

kubectl create namespace garden || true

# apply RBAC resources nad priority class in garden runtime cluster
helm template \
  "$(dirname "$0")/../../charts/gardener/operator" \
  -n garden \
  -s templates/clusterrole.yaml \
  -s templates/clusterrolebinding.yaml \
  -s templates/role.yaml \
  -s templates/rolebinding.yaml \
  -s templates/priorityclass.yaml |\
  KUBECONFIG="$kubeconfig" kubectl apply -f -

if [[ $(k8s_env) == "$KIND" ]]; then
  serviceaccount_based_kubeconfig "gardener-operator" > "$kubeconfig"
fi

KUBECONFIG="$kubeconfig" \
GO111MODULE=on \
GARDENER_OPERATOR_LOCAL=true \
WEBHOOK_MODE=url \
WEBHOOK_URL="$(get_host_address):$(cat "$(dirname "$0")/../../example/operator/10-componentconfig.yaml" | yq eval '.server.webhooks.port' -)" \
    go run \
      -mod=vendor \
      -ldflags "$("$(dirname $0)"/../get-build-ld-flags.sh)" \
      "$(dirname $0)"/../../cmd/gardener-operator/main.go \
      --config="$(dirname $0)"/../../example/operator/10-componentconfig.yaml
