#!/usr/bin/env bash
#
# Copyright (c) 2021 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

source $(dirname "${0}")/common/helpers
REPO_ROOT=$(dirname "${0}")/../..
ETCD_BACKUP_DIR=$REPO_ROOT/dev/local-backupbuckets
CONTAINER_PATH=/etc/gardener/local-backupbuckets

WEBHOOK_SERVER_PORT=${WEBHOOK_SERVER_PORT:-8444}
WEBHOOK_CERT_DIR=${WEBHOOK_CERT_DIR:-/tmp/gardener-extensions-cert}
SERVICE_HOST_IP=${SERVICE_HOST_IP:-127.0.0.1}
SERVICE_ZONE_0_IP=${SERVICE_ZONE_0_IP:-127.0.0.10}
SERVICE_ZONE_1_IP=${SERVICE_ZONE_1_IP:-127.0.0.11}
SERVICE_ZONE_2_IP=${SERVICE_ZONE_2_IP:-127.0.0.12}
METRICS_BIND_ADDRESS=${METRICS_BIND_ADDRESS:-:8080}
HEALTH_BIND_ADDRESS=${HEALTH_BIND_ADDRESS:-:8081}

mktemp_kubeconfig
kubeconfig="$__tmp_kubeconfig"
trap cleanup_kubeconfig EXIT

export LEADER_ELECTION_NAMESPACE=garden
export GO111MODULE=on
export GARDENER_SHOOT_CLIENT=external

# The namespace for the provider-local extension controller is required for various reasons
# (heartbeats, secrets management, network policies, ...).
EXTENSION_NAMESPACE="$(kubectl get namespaces -l controllerregistration.core.gardener.cloud/name=provider-local -o jsonpath='{.items[0].metadata.name}')"
if [ -z "$EXTENSION_NAMESPACE" ]; then
  echo "gardenlet has not yet created the namespace for the extension, cannot start provider-local"
  exit 1
fi

# sudo is required for now, as we need to manipulate /etc/hosts for making the shoot API server reachable on the host machine
SUDO=
if [ "$USER" != root ]; then
  SUDO="sudo -E"
fi

PROVIDER_LOCAL_DISABLE_COREDNS_MUTATION=true $SUDO go run \
  -mod=vendor \
  -ldflags "$("$(dirname $0)"/../get-build-ld-flags.sh)" \
  "$REPO_ROOT/cmd/gardener-extension-provider-local/main.go" \
  --kubeconfig="${KUBECONFIG:-$kubeconfig}" \
  --leader-election=false \
  --webhook-config-mode=url \
  --webhook-config-server-host=0.0.0.0 \
  --webhook-config-server-port="${WEBHOOK_SERVER_PORT}" \
  --webhook-config-url=$(get_host_address):${WEBHOOK_SERVER_PORT} \
  --webhook-config-cert-dir="${WEBHOOK_CERT_DIR}" \
  --webhook-config-namespace="${EXTENSION_NAMESPACE}" \
  --service-host-ip="${SERVICE_HOST_IP}" \
  --service-zone-0-ip="${SERVICE_ZONE_0_IP}" \
  --service-zone-1-ip="${SERVICE_ZONE_1_IP}" \
  --service-zone-2-ip="${SERVICE_ZONE_2_IP}" \
  --metrics-bind-address="${METRICS_BIND_ADDRESS}" \
  --health-bind-address="${HEALTH_BIND_ADDRESS}" \
  --heartbeat-namespace="${EXTENSION_NAMESPACE}" \
  --gardener-version="$(cat "$(dirname $0)/../../VERSION")" \
  --backupbucket-local-dir="$ETCD_BACKUP_DIR" \
  --backupbucket-container-mount-path="$CONTAINER_PATH"
