#!/bin/bash -e
#
# Copyright (c) 2021 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if [ "$1" != "RECONCILE" ] && [ "$1" != "DELETE" ]; then
  echo "Please set the argument \"OPERATION\" to either \"RECONCILE\" or \"DELETE\" (\"make start-landscaper-gardenlet OPERATION=RECONCILE\")"
  exit 1
fi

printf "Using import values from 'dev/landscaper/gardenlet-landscaper-imports.yaml'. \n \n"

GO111MODULE=on \
OPERATION="$1" \
IMPORTS_PATH=dev/landscaper/gardenlet-landscaper-imports.yaml \
COMPONENT_DESCRIPTOR_PATH=dev/landscaper/gardenlet-landscaper-component-descriptor-list.yaml \
    go run \
      -mod=vendor \
      -ldflags "$(./hack/get-build-ld-flags.sh)" \
      "$(dirname $0)"/../../landscaper/cmd/landscaper-gardenlet/main.go
