#!/bin/bash -e
#
# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

source $(dirname "${0}")/common/helpers

mktemp_kubeconfig
kubeconfig="$__tmp_kubeconfig"
trap cleanup_kubeconfig EXIT

GO111MODULE=on \
    go run \
      -mod=vendor \
      -ldflags "$(./hack/get-build-ld-flags.sh)" \
      "$(dirname $0)"/../../cmd/gardener-seed-admission-controller/main.go \
      --kubeconfig="${KUBECONFIG:-$kubeconfig}" \
      --tls-cert-path="$(dirname $0)/../../example/seed-admission-controller/tls.crt" \
      --tls-private-key-path="$(dirname $0)/../../example/seed-admission-controller/tls.key"
