#!/bin/bash -e
#
# SPDX-FileCopyrightText: 2018 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

source $(dirname "${0}")/common/helpers

mktemp_kubeconfig
kubeconfig="$__tmp_kubeconfig"
trap cleanup_kubeconfig EXIT

KUBECONFIG="${KUBECONFIG:-$kubeconfig}" GO111MODULE=on \
    go run \
      -mod=vendor \
      -ldflags "$("$(dirname $0)"/../get-build-ld-flags.sh)" \
      "$(dirname $0)"/../../cmd/gardener-controller-manager/main.go \
      --config="$(dirname $0)"/../../dev/20-componentconfig-gardener-controller-manager.yaml
