#!/bin/bash -eu
#
# Copyright 2018 The Gardener Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

VERSION="${1:-$($(dirname $0)/get-next-version)}"
COMMIT="${2:-true}"

echo "Bumping version to $VERSION"
echo $VERSION > $(dirname $0)/../VERSION

# commit
if [[ $COMMIT == true ]]; then
  git status
  read -p "Continue (y/n)? " response
  if [[ "$response" =~ ^(yes|y) ]]; then
    git add .
    git commit -m "Bump version to $VERSION"
  fi
  git status
fi
