#!/bin/bash -e
#
# Copyright 2018 The Gardener Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

VERSION=$(go version)
MAJOR_GOVERSION=$(echo -n "$VERSION" | grep -o 'go1\.[0-9]' || true)
UNSUPPORTED=("go1.0" "go1.1" "go1.2" "go1.3" "go1.4" "go1.5" "go1.6" "go1.7" "go1.8")

for V in "${UNSUPPORTED[@]}"; do
  if [ "$V" = "$MAJOR_GOVERSION" ]; then
    >&2 echo "ERROR: Gardener requires Go version 1.9+. Please update your Go installation: https://golang.org/dl/"
    exit 1
  fi
done

