#!/bin/bash
#
# Copyright (c) 2018 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

DOCKER_FOR_DESKTOP="docker-for-desktop"
MINIKUBE="minikube"
SUPPORTED_K8S_ENVS=($DOCKER_FOR_DESKTOP $MINIKUBE)

API_SERVER_SECURE_PORT="${API_SERVER_SECURE_PORT:-8443}"

__k8s_env=""
k8s_env() {
    if [[ "$__k8s_env" == "" ]]; then
        __k8s_env=$(kubectl get node -o jsonpath="{.items[*].metadata.name}")
    fi
    for supported_k8s_env in ${SUPPORTED_K8S_ENVS[@]}; do
        if [[ "$supported_k8s_env" == "$__k8s_env" ]]; then
            echo "$supported_k8s_env"
            return
        fi
    done
    >&2 echo "Unsupported Kubernetes Environment: $__k8s_env"
    exit 1
}
