#!/bin/bash
#
# Copyright (c) 2018 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source $(dirname "${0}")/common

DEV_DIR=$(dirname "${0}")/../dev
EXAMPLE_DIR=$(dirname "${0}")/../example
MINIKUBE_IP=$(minikube ip)
IP_ROUTE=$(ip route get 1)
IP_ADDRESS=$(echo ${IP_ROUTE#*src} | awk '{print $1}')
MINIKUBE_SEED_KUBECONFIG=${DEV_DIR}/minikube-seed-kubeconfig

kubectl apply -f ${EXAMPLE_DIR}/05-project-dev.yaml
kubectl apply -f ${EXAMPLE_DIR}/06-namespace-garden-dev.yaml
kubectl apply -f ${EXAMPLE_DIR}/30-cloudprofile-local.yaml
kubectl apply -f ${EXAMPLE_DIR}/70-secret-cloudprovider-local.yaml
kubectl apply -f ${EXAMPLE_DIR}/80-secretbinding-cloudprovider-local.yaml

kubectl config set-cluster gardener-dev \
  --kubeconfig ${MINIKUBE_SEED_KUBECONFIG} \
  --certificate-authority $HOME/.minikube/ca.crt \
  --server https://${MINIKUBE_IP}:$API_SERVER_SECURE_PORT \
  --embed-certs=true

kubectl config set-credentials gardener-dev \
  --kubeconfig ${MINIKUBE_SEED_KUBECONFIG} \
  --client-certificate $HOME/.minikube/client.crt \
  --client-key $HOME/.minikube/client.key \
  --embed-certs=true

kubectl config set-context gardener-dev \
  --kubeconfig ${MINIKUBE_SEED_KUBECONFIG} \
  --cluster gardener-dev \
  --user gardener-dev

kubectl config use-context gardener-dev \
  --kubeconfig ${MINIKUBE_SEED_KUBECONFIG}

# Different base64 implementations have different flags
MINIKUBE_SEED_KUBECONFIG_B64=$(base64 ${MINIKUBE_SEED_KUBECONFIG} | tr -d '\r\n')

sed -e "s/kubeconfig: base64(kubeconfig-for-seed-cluster)/kubeconfig: ${MINIKUBE_SEED_KUBECONFIG_B64}/g" example/40-secret-seed-local.yaml | \
  kubectl apply -f -

sed -e "s/ingressDomain: <minikube-ip>.nip.io/ingressDomain: ${MINIKUBE_IP}.nip.io/g" example/50-seed-local.yaml | \
  kubectl apply -f -

sed -e "s/domain: <minikube-ip>.nip.io/domain: ${MINIKUBE_IP}.nip.io/g" example/90-shoot-local.yaml | \
  sed -e "s/endpoint: localhost:3777/endpoint: ${IP_ADDRESS}:3777/g" | \
  sed -e "s/name: johndoe-local/name: local/g" >${DEV_DIR}/90-shoot-local.yaml

# Update Vagrant images and prune the outdated ones
(cd vagrant; vagrant box update; vagrant box prune)
