#!/bin/bash
#
# Copyright (c) 2018 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#!/bin/sh

set -e

DEV_DIR=$(dirname "${0}")/../dev
EXAMPLE_DIR=$(dirname "${0}")/../example

source $(dirname "${0}")/common

# test if we are running against a Minikube or Docker Kubernetes local setup
case $(k8s_env) in
    $DOCKER_FOR_DESKTOP)
        echo "Found Docker Kubernetes ..."
        LOCAL_K8S_HOST_IP=localhost
        ETCD_DATA_DIR="/Users/$(whoami)/.docker/gardener-etcd"
        ;;
    $MINIKUBE)
        echo "Found Minikube ..."
        LOCAL_K8S_HOST_IP="$(minikube ip)"
        ETCD_DATA_DIR="/data/gardener-etcd"
        echo "After OSX sleep, minikube's time is off."
        echo "This results in x509 certificate auth to not work for shoot certificates"
        minikube ssh -- docker run -i --rm --privileged --pid=host debian nsenter -t 1 -m -u -n -i date -u $(date -u +%m%d%H%M%Y)
        ;;
 esac

mkdir -p ${DEV_DIR}

cp ${EXAMPLE_DIR}/20-componentconfig-gardener-controller-manager.yaml ${DEV_DIR}/

kubectl apply -f ${EXAMPLE_DIR}/00-namespace-garden.yaml
kubectl apply -f ${EXAMPLE_DIR}/00-namespace-garden-dev.yaml
kubectl apply -f ${EXAMPLE_DIR}/10-secret-internal-domain-unmanaged.yaml

cat <<EOF | kubectl apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd
  namespace: garden
spec:
  replicas: 1
  selector:
    matchLabels:
      run: etcd
  template:
    metadata:
      labels:
        run: etcd
    spec:
      containers:
      - image: quay.io/coreos/etcd:v3.3.2
        name: etcd
        command:
        - etcd
        - -advertise-client-urls=http://${LOCAL_K8S_HOST_IP}:2379
        - -listen-client-urls=http://0.0.0.0:2379
        - -data-dir=/etcd-data
        volumeMounts:
        - mountPath: /etcd-data
          name: data
      volumes:
      - name: data
        hostPath:
          path: ${ETCD_DATA_DIR}
---
apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: garden
spec:
  ports:
  - port: 2379
    nodePort: 32379
  selector:
    run: etcd
  type: NodePort
EOF

$(dirname "${0}")/dev-setup-register-gardener
