#!/bin/bash -eu

# install python requirements if needed
if ! pip list 2>&1 | grep Mako &>/dev/null; then
  pip install Mako
fi

PATH_TEMPLATES="$(dirname $0)/templates/resources"
PATH_EXAMPLES="$(dirname $0)/../example"

mkdir -p "$PATH_EXAMPLES"

# render cloud-specific templates
for cloud in aws azure gcp openstack local; do
  echo "* Rendering manifests for cloud '$cloud':"
  for resource in cloudprofile seed secret-seed secret-cloudprovider secretbinding-cloudprovider shoot; do
    echo "  * Template '$resource' rendered."
    mako-render --var cloud="$cloud" "$PATH_TEMPLATES/$resource.yaml.tpl" > "$PATH_EXAMPLES/$resource-$cloud.yaml"
  done
  echo
done

# render cloud-independent templates
for template in quota; do
  echo "* Template '$template' rendered."
  mako-render "$PATH_TEMPLATES/$template.yaml.tpl" > "$PATH_EXAMPLES/$template.yaml"
done
