#!/bin/bash -e
#
# Copyright (c) 2018 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

GO111MODULE=on go get -u sigs.k8s.io/controller-tools/cmd/controller-gen

# The CRD generator does not understand APIs managed by aggregated API servers.
cp -r pkg/apis pkg/apis-tmp
rm -rf pkg/apis/core pkg/apis/garden
# The CRD generator does not understand the embedded structs - the validation for these
# fields needs to be added manually after generation.
rm -f pkg/apis/extensions/v1alpha1/types_defaults.go

function end_execution() {
  trap - HUP QUIT PIPE INT TERM EXIT
  rm -rf pkg/apis
  mv pkg/apis-tmp pkg/apis
}
trap end_execution INT TERM EXIT

controller-gen crd \
  --domain=extensions.gardener.cloud \
  --output-dir=dev/extensions-crds
