#!/bin/bash
#
# Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

function headers() {
  echo '''/*
Copyright YEAR (c) 2019 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
'''
}

rm -f $GOPATH/bin/*-gen

$(dirname $0)/../vendor/k8s.io/code-generator/generate-internal-groups.sh \
  all \
  github.com/gardener/gardener/pkg/client/garden \
  github.com/gardener/gardener/pkg/apis \
  github.com/gardener/gardener/pkg/apis \
  garden:v1beta1 \
  -h <(headers)

$(dirname $0)/../vendor/k8s.io/code-generator/generate-internal-groups.sh \
  deepcopy,defaulter \
  github.com/gardener/gardener/pkg/client/componentconfig \
  github.com/gardener/gardener/pkg/apis \
  github.com/gardener/gardener/pkg/apis \
  "componentconfig:v1alpha1" \
  -h <(headers)

$(dirname $0)/../vendor/k8s.io/code-generator/generate-internal-groups.sh \
  conversion \
  github.com/gardener/gardener/pkg/client/componentconfig \
  github.com/gardener/gardener/pkg/apis \
  github.com/gardener/gardener/pkg/apis \
  "componentconfig:v1alpha1" \
  --extra-peer-dirs=github.com/gardener/gardener/pkg/apis/componentconfig,github.com/gardener/gardener/pkg/apis/componentconfig/v1alpha1,k8s.io/apimachinery/pkg/apis/meta/v1,k8s.io/apimachinery/pkg/conversion,k8s.io/apimachinery/pkg/runtime \
  -h <(headers)

$(dirname $0)/../vendor/k8s.io/code-generator/generate-groups.sh \
  client,lister,informer \
  github.com/gardener/gardener/pkg/client/machine \
  github.com/gardener/machine-controller-manager/pkg/apis \
  machine:v1alpha1 \
  -h <(headers)

rm -Rf ./$(dirname "${0}")/../openapi/openapi_generated.go
go install ./$(dirname "${0}")/../vendor/k8s.io/kube-openapi/cmd/openapi-gen

echo "Generating openapi definitions"
${GOPATH}/bin/openapi-gen "$@" \
  --v 1 \
  --logtostderr \
  --input-dirs=github.com/gardener/gardener/pkg/apis/garden/v1beta1 \
  --input-dirs=k8s.io/api/core/v1 \
  --input-dirs=k8s.io/api/rbac/v1 \
  --input-dirs=k8s.io/apimachinery/pkg/apis/meta/v1 \
  --input-dirs=k8s.io/apimachinery/pkg/api/resource \
  --input-dirs=k8s.io/apimachinery/pkg/types \
  --input-dirs=k8s.io/apimachinery/pkg/version \
  --input-dirs=k8s.io/apimachinery/pkg/runtime \
  --input-dirs=k8s.io/apimachinery/pkg/util/intstr \
  --report-filename=./$(dirname "${0}")/../pkg/openapi/api_violations.report \
  --output-package=github.com/gardener/gardener/pkg/openapi \
  -h <(headers)

echo
echo "NOTE: If you changed the API then consider updating the example manifests by modifying '$(dirname $0)/templates/resources/*.yaml.tpl' and running '$(dirname $0)/generate-examples'".
