#!/bin/bash -e
#
# Copyright (c) 2018 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

function increment() {
  echo $(awk "BEGIN {print $1+1; exit}")
}

TYPE="${1:-default}"

CURRENT_VERSION="$(cat $(dirname $0)/../VERSION)"
MAJOR="$(echo $CURRENT_VERSION | sed -E 's/^([0-9]*).*$/\1/')"
MINOR="$(echo $CURRENT_VERSION | sed -E 's/^.*\.([0-9]*)\..*$/\1/')"
PATCH="$(echo $CURRENT_VERSION | sed -E 's/^.*\.([0-9]*)$/\1/')"

if [[ $TYPE == "hotfix" || "$(git rev-parse --abbrev-ref HEAD)" == *release* ]]; then
  echo $MAJOR.$MINOR.$(increment $PATCH)
else
  PATCH=0
  echo $MAJOR.$(increment $MINOR).$PATCH
fi

