#!/bin/bash
#
# Copyright (c) 2018 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

source $(dirname "${0}")/common

case $(k8s_env) in
    $DOCKER_FOR_DESKTOP)
        echo "Found Docker Kubernetes ..."
        go run cmd/gardener-apiserver/main.go \
          --authentication-kubeconfig ~/.kube/config \
          --authorization-kubeconfig ~/.kube/config \
          --authorization-always-allow-paths=/healthz \
          --etcd-servers http://localhost:32379 \
          --kubeconfig ~/.kube/config \
          --tls-cert-file <(kubectl config view -o go-template='{{range .users}}{{if eq .name "docker-for-desktop"}}{{index .user "client-certificate-data"}}{{end}}{{end}}' --raw | base64 -d) \
          --tls-private-key-file <(kubectl config view -o go-template='{{range .users}}{{if eq .name "docker-for-desktop"}}{{index .user "client-key-data"}}{{end}}{{end}}' --raw | base64 -d) \
          --secure-port=8443 \
          --v 2
        ;;
    $MINIKUBE)
        echo "Found Minikube ..."
        go run cmd/gardener-apiserver/main.go \
          --authentication-kubeconfig ~/.kube/config \
          --authorization-kubeconfig ~/.kube/config \
          --etcd-servers http://$(minikube ip):32379 \
          --kubeconfig ~/.kube/config \
          --tls-cert-file ~/.minikube/apiserver.crt \
          --tls-private-key-file ~/.minikube/apiserver.key \
          --secure-port=8443 \
          --v 2
        ;;
esac
