apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-provider-config
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    apiVersion: local.provider.gardener.cloud/v1alpha1
    kind: CloudProviderConfig
    {{- with .Values.runtimeCluster }}
    runtimeCluster:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    loadBalancer:
      image: {{ .Values.loadBalancer.image }}
