{
 "title": "VPA Updater",
 "tags": [ "Autoscaling" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(vpa_updater_controlled_pods_total,pod)"
    }
   },
   {
    "name": "vpa_namespace",
    "label": "VPA object namespace",
    "query": {
     "query": "{__name__=~\"vpa_updater_.+\", pod=~\"$pod\", vpa_namespace!=\"\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Aggregation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "In-place Pod resource updates",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(vpa_updater_in_place_updated_pods_total{pod=~\"$pod\"}[$__range]))",
     "legendFormat": "Successful "
    },
    {
     "expr": "sum(increase(vpa_updater_failed_in_place_update_attempts_total{pod=~\"$pod\"}[$__range]))",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Pod evictions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(vpa_updater_evicted_pods_total{pod=~\"$pod\"}[$__range]))",
     "legendFormat": "Successful "
    },
    {
     "expr": "sum(increase(vpa_updater_failed_eviction_attempts_total{pod=~\"$pod\"}[$__range]))",
     "legendFormat": "Failed"
    }
   ]
  },
  { "title": "Scale", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Total Controlled Pods",
   "type": "graph",
   "gridPos": { "h": 11, "w": 17, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vpa_updater_controlled_pods_total{pod=~\"$pod\"}) by (update_mode)",
     "legendFormat": "{{update_mode}}"
    },
    {
     "expr": "sum(vpa_updater_controlled_pods_total{pod=~\"$pod\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Current update mode distribution by Pods",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vpa_updater_controlled_pods_total{pod=~\"$pod\"}) by (update_mode)",
     "legendFormat": "{{update_mode}}"
    }
   ]
  },
  {
   "title": "Pods pending in-place update",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vpa_updater_in_place_updatable_pods_total{pod=~\"$pod\"})",
     "legendFormat": "Pending in-place update"
    },
    {
     "expr": "sum(vpa_updater_controlled_pods_total{pod=~\"$pod\", update_mode=\"InPlaceOrRecreate\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "VPAs with in-place updatable Pods",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vpa_updater_vpas_with_in_place_updatable_pods_total{pod=~\"$pod\"})",
     "legendFormat": "In-place updatable"
    },
    {
     "expr": "sum(floor(increase(vpa_updater_vpas_with_in_place_updated_pods_total{pod=~\"$pod\"}[$__rate_interval])))",
     "legendFormat": "Successfully in-place updated"
    }
   ]
  },
  {
   "title": "Pods pending eviction",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vpa_updater_evictable_pods_total{pod=~\"$pod\"}) by (update_mode)",
     "legendFormat": "Pending eviction with '{{update_mode}}' mode"
    },
    {
     "expr": "sum(vpa_updater_controlled_pods_total{pod=~\"$pod\", update_mode!=\"InPlaceOrRecreate\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "VPAs with evictable Pods",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vpa_updater_vpas_with_evictable_pods_total{pod=~\"$pod\"}) by (update_mode)",
     "legendFormat": "Evictable with '{{update_mode}}' update mode"
    },
    {
     "expr": "sum(floor(increase(vpa_updater_vpas_with_evicted_pods_total{pod=~\"$pod\"}[$__rate_interval]))) by (update_mode)",
     "legendFormat": "Successfully evicted with '{{update_mode}}' mode"
    }
   ]
  },
  { "title": "Pod in-place resource updates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Successful Pod in-place updates by VPA",
   "type": "graph",
   "description": "Initial data points are set to 0, because the VPA Updater component does not emit default counter values. This behaviour causes the increase() function to perform its calculation with a single sample, resulting in 0. For more details, see https://github.com/kubernetes/autoscaler/issues/9058.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(floor(increase(vpa_updater_in_place_updated_pods_total{pod=~\"$pod\", vpa_namespace=~\"$vpa_namespace\"}[$__rate_interval]))) by (vpa_name,vpa_namespace)",
     "legendFormat": "{{vpa_namespace}}/{{vpa_name}}"
    },
    {
     "expr": "sum(floor(increase(vpa_updater_in_place_updated_pods_total{pod=~\"$pod\", vpa_namespace=~\"$vpa_namespace\"}[$__rate_interval])))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Failed Pod in-place updates by VPA",
   "type": "graph",
   "description": "Initial data points are set to 0, because the VPA Updater component does not emit default counter values. This behaviour causes the increase() function to perform its calculation with a single sample, resulting in 0. For more details, see https://github.com/kubernetes/autoscaler/issues/9058.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(floor(increase(vpa_updater_failed_in_place_update_attempts_total{pod=~\"$pod\", vpa_namespace=~\"$vpa_namespace\"}[$__rate_interval]))) by (vpa_name,vpa_namespace)",
     "legendFormat": "{{vpa_namespace}}/{{vpa_name}}"
    },
    {
     "expr": "sum(floor(increase(vpa_updater_failed_in_place_update_attempts_total{pod=~\"$pod\", vpa_namespace=~\"$vpa_namespace\"}[$__rate_interval])))",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Pod evictions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Successful Pod evictions by VPA",
   "type": "graph",
   "description": "Initial data points are set to 0, because the VPA Updater component does not emit default counter values. This behaviour causes the increase() function to perform its calculation with a single sample, resulting in 0. For more details, see https://github.com/kubernetes/autoscaler/issues/9058.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(floor(increase(vpa_updater_evicted_pods_total{pod=~\"$pod\", vpa_namespace=~\"$vpa_namespace\"}[$__rate_interval]))) by (vpa_name,vpa_namespace)",
     "legendFormat": "{{vpa_namespace}}/{{vpa_name}}"
    },
    {
     "expr": "sum(floor(increase(vpa_updater_evicted_pods_total{pod=~\"$pod\", vpa_namespace=~\"$vpa_namespace\"}[$__rate_interval])))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Failed Pod evictions by VPA",
   "type": "graph",
   "description": "Initial data points are set to 0, because the VPA Updater component does not emit default counter values. This behaviour causes the increase() function to perform its calculation with a single sample, resulting in 0. For more details, see https://github.com/kubernetes/autoscaler/issues/9058.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(floor(increase(vpa_updater_failed_eviction_attempts_total{pod=~\"$pod\", vpa_namespace=~\"$vpa_namespace\"}[$__rate_interval]))) by (vpa_name,vpa_namespace)",
     "legendFormat": "{{vpa_namespace}}/{{vpa_name}}"
    },
    {
     "expr": "sum(floor(increase(vpa_updater_failed_eviction_attempts_total{pod=~\"$pod\", vpa_namespace=~\"$vpa_namespace\"}[$__rate_interval])))",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}