{
 "title": "Seed Resource Usage",
 "tags": [
  "seed",
  "usage"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "seed",
    "query": {
     "query": "label_values(seed:container_cpu_usage_seconds_total:sum, seed)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Shoots per Seed",
   "type": "bargauge",
   "description": "Shows the number of shoots per seed (does not count hibernated shoots).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(garden_shoot_info{seed=~\"$seed\"}) by (seed)",
     "legendFormat": "{{ seed }}"
    }
   ]
  },
  {
   "title": "Shoots per Seed",
   "type": "graph",
   "description": "Shows the number of shoots per seed (does not count hibernated shoots).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Shoots" }
   ],
   "targets": [
    {
     "expr": "count(garden_shoot_info{seed=~\"$seed\"}) by (seed)",
     "legendFormat": "{{ seed }}"
    }
   ]
  },
  {
   "title": "CPU Control Plane Utilization",
   "type": "graph",
   "description": "How much of the seed CPU is utilized for control planes.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(seed:container_cpu_usage_seconds_total:sum_cp{seed=~\"$seed\"}/seed:container_cpu_usage_seconds_total:sum{seed=~\"$seed\"}) by (seed)",
     "legendFormat": "{{ seed }}"
    }
   ]
  },
  {
   "title": "Memory Control Plane Utilization",
   "type": "graph",
   "description": "How much of the seed memory is utilized for control planes.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(seed:container_memory_working_set_bytes:sum_cp{seed=~\"$seed\"}/seed:container_memory_working_set_bytes:sum{seed=~\"$seed\"}) by (seed)",
     "legendFormat": "{{ seed }}"
    }
   ]
  },
  {
   "title": "Total CPU Utilization (Requests)",
   "type": "graph",
   "description": "How much of the seed CPU is utilized based on requests.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(seed:kube_pod_container_resource_requests_cpu_cores:sum{seed=~\"$seed\"}/seed:kube_node_status_allocatable_cpu_cores:sum{seed=~\"$seed\"}) by (seed)",
     "legendFormat": "{{ seed }}"
    }
   ]
  },
  {
   "title": "Total Memory Utilization (Requests)",
   "type": "graph",
   "description": "How much of the seed memory is utilized based on requests.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(seed:kube_pod_container_resource_requests_memory_bytes:sum{seed=~\"$seed\"}/seed:kube_node_status_allocatable_memory_bytes:sum{seed=~\"$seed\"}) by (seed)",
     "legendFormat": "{{ seed }}"
    }
   ]
  },
  { "title": "Total Seed Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Seed CPU Usage",
   "type": "graph",
   "description": "Shows the total CPU usage of each seed.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "sum(seed:container_cpu_usage_seconds_total:sum{seed=~\"$seed\"}) by (seed)",
     "legendFormat": "{{ seed }}"
    }
   ]
  },
  {
   "title": "Seed Memory Usage",
   "type": "graph",
   "description": "Shows the total memory usage of each seed.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum(seed:container_memory_working_set_bytes:sum{seed=~\"$seed\"}) by (seed)",
     "legendFormat": "{{ seed }}"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "bargauge",
   "description": "Shows the total number of nodes for each seed.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(shoot:kube_node_info:count{project=\"garden\", shoot_name=~\"$seed\"}) by (shoot_name)",
     "legendFormat": "{{ shoot_name }}"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "graph",
   "description": "Shows the total number of nodes for each seed.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "Nodes" }
   ],
   "targets": [
    {
     "expr": "sum(shoot:kube_node_info:count{project=\"garden\", shoot_name=~\"$seed\"}) by (shoot_name)",
     "legendFormat": "{{ shoot_name }}"
    }
   ]
  },
  {
   "title": "Control Planes per Node",
   "type": "graph",
   "description": "Shows how many controlplanes are hosted on each node on average.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "none", "label": "ControlPlanes" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(sum(seed:active_shoots_total:sum) by (seed), 'shoot_name', '$1', 'seed', '(.+)')) by (shoot_name) / sum(shoot:kube_node_info:count{project='garden'}) by (shoot_name)",
     "legendFormat": "{{ shoot_name }}"
    }
   ]
  },
  {
   "title": "Images",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Image Count",
     "type": "graph",
     "description": "Shows the current count of each image on the seeds.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "seed:images:count{seed=~\"$seed\"}",
       "legendFormat": "{{image}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Control Plane Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Seed Control Plane CPU Usage",
     "type": "graph",
     "description": "Shows the control plance CPU usage of each seed.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short", "label": "Cores" }
     ],
     "targets": [
      {
       "expr": "sum(seed:container_cpu_usage_seconds_total:sum_cp{seed=~\"$seed\"}) by (seed)",
       "legendFormat": "{{ seed }}"
      }
     ]
    },
    {
     "title": "Seed Control Plane Memory Usage",
     "type": "graph",
     "description": "Shows the control plane memory usage of each seed.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "bytes", "label": "Memory" }
     ],
     "targets": [
      {
       "expr": "sum(seed:container_memory_working_set_bytes:sum_cp{seed=~\"$seed\"}) by (seed)",
       "legendFormat": "{{ seed }}"
      }
     ]
    }
   ]
  },
  {
   "title": "System Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Seed System CPU Usage",
     "type": "graph",
     "description": "Shows the system CPU usage of each seed. (Extensions, kube-system, and garden)",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Cores" }
     ],
     "targets": [
      {
       "expr": "sum(seed:container_cpu_usage_seconds_total:sum{seed=~\"$seed\"} - seed:container_cpu_usage_seconds_total:sum_cp{seed=~\"$seed\"}) by (seed)",
       "legendFormat": "{{ seed }}"
      }
     ]
    },
    {
     "title": "Seed System Memory Usage",
     "type": "graph",
     "description": "Shows the system memory usage of each seed. (Extensions, kube-system and garden)",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "bytes", "label": "Memory" }
     ],
     "targets": [
      {
       "expr": "sum(seed:container_memory_working_set_bytes:sum{seed=~\"$seed\"} - seed:container_memory_working_set_bytes:sum_cp{seed=~\"$seed\"}) by (seed)",
       "legendFormat": "{{ seed }}"
      }
     ]
    }
   ]
  },
  { "title": "Extensions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Extension CPU Usage",
   "type": "graph",
   "description": "Shows how many CPU cores each extension uses.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "sum(metering:cpu_usage:sum_by_namespace_owner_container{container=~\".+extension.+\",seed=~\"$seed\"}) by (seed,namespace)",
     "legendFormat": "{{seed}}/{{ namespace }}"
    }
   ]
  },
  {
   "title": "Extension Memory Usage",
   "type": "graph",
   "description": "Shows how much memory each extension is using.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "decbytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum(metering:memory_usage:sum_by_namespace_owner_container{container=~\".+extension.+\",seed=~\"$seed\"}) by (seed,namespace)",
     "legendFormat": "{{ seed }}/{{namespace}}"
    }
   ]
  }
 ]
}