{
 "title": "Extensions",
 "tags": [
  "extensions",
  "resources"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "container", "label": "Container", "query": "label_values(container_name)" }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "Shows the CPU usage of selected extension controllers.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(seed:container_cpu_usage_seconds_total:sum_by_container{container=\"$container\"}) by (container)",
     "legendFormat": "{{ container }}"
    },
    {}
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Shows the memory usage of selected extension controllers.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(seed:container_memory_working_set_bytes:sum_by_container{container=\"$container\"}) by (container)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{container_name=~\"$container\"}"
    }
   ]
  }
 ]
}