{
 "title": "Seed Resource Usage",
 "tags": [
  "seed",
  "overview",
  "resources"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "The CPU Usage of the seed.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "sum(seed:container_cpu_usage_seconds_total:sum)",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Shows the total memory usage of the seed.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum(seed:container_memory_working_set_bytes:sum)",
     "legendFormat": "Memory"
    }
   ]
  },
  { "title": "Control Planes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "CPU Usage Control Planes",
   "type": "graph",
   "description": "Shows how many CPU cores are required for the control planes on the seed.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "sum(seed:container_cpu_usage_seconds_total:sum_cp)",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Memory Usage Control Plane",
   "type": "graph",
   "description": "Shows the total memory usage of all control planes on the seed.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum(seed:container_memory_working_set_bytes:sum_cp)",
     "legendFormat": "Memory"
    }
   ]
  }
 ]
}