# Envoy proxy and istio do not support HTTP/2 client connection coalescing natively.
# Clients, especially web browsers, may open a single HTTP/2 connection and send requests
# targeted at different hosts all backed by the same IP address and wildcard certificate.
# Returning 421 for requests where the server name and the authority header do not match
# indicates to the client that it should open a new connection for the request.
# Issues:
# - https://github.com/envoyproxy/envoy/issues/6767
# - https://github.com/istio/istio/issues/13589
# Documentation:
# - https://istio.io/latest/docs/ops/common-problems/network-issues/#404-errors-occur-when-multiple-gateways-configured-with-same-tls-certificate
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: misdirected-requests
  namespace: {{ .Release.Namespace }}
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        portNumber: 9443
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.router
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.lua
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
          inlineCode: |
            function envoy_on_request(request_handle)
              local streamInfo = request_handle:streamInfo()
              local rsn = streamInfo:requestedServerName()

              if rsn == nil or rsn == "" then
                return
              end

              local authority = request_handle:headers():get(":authority")
              if authority == nil then
                return
              end

              -- Strip trailing 443 port
              authority = authority:gsub(":443$", "")

              if rsn ~= authority then
                request_handle:respond({[":status"] = "421"}, "Misdirected Request")
              end
            end
