{
 "title": "Reversed VPN OpenVPN Server (HA)",
 "description": "OpenVPN Server status using Prometheus and OpenVPN exporter (High availability only)",
 "tags": [
  "controlplane",
  "network",
  "seed"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Traffic VPN Clients of all Kube-apiservers (vpn-seed-client)",
   "type": "graph",
   "description": "Traffic for all VPN tunnels of all VPN clients of all Kube-apiservers pods",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum (rate(openvpn_server_client_received_bytes_total{common_name=\"vpn-seed-client\"}[$__rate_interval])) by (service)",
     "legendFormat": "{{service}} Received"
    },
    {
     "expr": "sum (rate(openvpn_server_client_sent_bytes_total{common_name=\"vpn-seed-client\"}[$__rate_interval])) by (service)",
     "legendFormat": "{{service}} Sent"
    }
   ]
  },
  {
   "title": "Traffic VPN Clients vpn-shoot-0",
   "type": "graph",
   "description": "Traffic for all VPN tunnels to shoot pod vpn-shoot-0",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum (rate(openvpn_server_client_received_bytes_total{common_name=\"vpn-shoot-client-0\"}[$__rate_interval])) by (service)",
     "legendFormat": "{{service}} Received"
    },
    {
     "expr": "sum (rate(openvpn_server_client_sent_bytes_total{common_name=\"vpn-shoot-client-0\"}[$__rate_interval])) by (service)",
     "legendFormat": "{{service}} Sent"
    }
   ]
  },
  {
   "title": "Traffic VPN Clients vpn-shoot-1",
   "type": "graph",
   "description": "Traffic for all VPN tunnels to shoot pod vpn-shoot-1",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum (rate(openvpn_server_client_received_bytes_total{common_name=\"vpn-shoot-client-1\"}[$__rate_interval])) by (service)",
     "legendFormat": "{{service}} Received"
    },
    {
     "expr": "sum (rate(openvpn_server_client_sent_bytes_total{common_name=\"vpn-shoot-client-1\"}[$__rate_interval])) by (service)",
     "legendFormat": "{{service}} Sent"
    }
   ]
  },
  {
   "title": "UP Status VPN Seed Servers",
   "type": "graph",
   "description": "UP status of VPN seed servers",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Servers" }
   ],
   "targets": [
    {
     "expr": "count(timestamp(openvpn_status_update_time_seconds)-openvpn_status_update_time_seconds < 35) by (service)",
     "legendFormat": "UP {{service}}"
    }
   ]
  },
  {
   "title": "VPN Seed Servers Client Count",
   "type": "graph",
   "description": "Count of connected clients per VPN seed server",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Clients" }
   ],
   "targets": [
    {
     "expr": "count(timestamp(openvpn_server_route_last_reference_time_seconds) - openvpn_server_route_last_reference_time_seconds < 35) by (service)",
     "legendFormat": "Connected clients of {{service}}"
    }
   ]
  },
  {
   "title": "Traffic sent in the last 24 hour",
   "type": "stat",
   "description": "Traffic sent to clients by OpenVPN server instance (reflects only values of current running server instances)",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(openvpn_server_client_sent_bytes_total[1d])) by (service)",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "Traffic received in the last 24 hour",
   "type": "stat",
   "description": "Traffic received from clients by OpenVPN server instance (reflects only values of current running server instances)",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(openvpn_server_client_received_bytes_total[1d])) by (service)",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "Current OpenVPN Clients",
   "type": "table",
   "description": "Please note:\n- Column 'Client Common Name': kube-apiserver pods appear with name \"vpn-seed-client\"\n- Column 'Last seen' may have value \"NaN\" if the tunnel is not active\n- Column 'Cluster IP': For \"vpn-shoot-client-*\" it shows the IP of the used istio-ingressgateway pod",
   "gridPos": { "h": 13, "w": 14, "x": 10, "y": 30 },
   "targets": [
    {
     "expr": "sum(openvpn_server_client_sent_bytes_total{}) by(common_name, connection_time,virtual_address,real_ip,real_address,service)"
    },
    {
     "expr": "sum(openvpn_server_client_received_bytes_total{}) by(common_name, connection_time,virtual_address,real_ip,real_address,service)"
    },
    {
     "expr": "openvpn_server_route_last_reference_time_seconds"
    }
   ]
  },
  {
   "title": "Top Logins",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(6, sum(count_values(\"connection_time\", count_over_time(openvpn_server_client_received_bytes_total{common_name!=\"UNDEF\"}[1d]))by(common_name))by(common_name)>1)",
     "legendFormat": "{{ common_name }}"
    }
   ]
  },
  {
   "title": "Top Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 36 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(6, sum(increase(openvpn_server_client_received_bytes_total{common_name!=\"UNDEF\"}[1d])+increase(openvpn_server_client_sent_bytes_total{common_name!=\"UNDEF\"}[1d]))by(common_name))",
     "legendFormat": "{{ common_name }}"
    }
   ]
  }
 ]
}