{
 "title": "Istio Control Plane Dashboard",
 "tags": [ "istio" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "istiod",
    "label": "istiod",
    "query": {
     "query": "label_values(pilot_services{}, pod)"
    }
   },
   {
    "name": "igw",
    "label": "Ingress Gateway",
    "query": {
     "query": "label_values(envoy_server_hot_restart_epoch{}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Deployed Versions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pilot Versions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(istio_build{component=\"pilot\", pod=~\"$istiod\"}) by (tag)",
     "legendFormat": "{{ tag }}"
    }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(process_virtual_memory_bytes{job=\"istiod\"})",
     "legendFormat": "Virtual Memory"
    },
    {
     "expr": "sum(process_resident_memory_bytes{job=\"istiod\"})",
     "legendFormat": "Resident Memory"
    },
    {
     "expr": "sum(go_memstats_alloc_bytes{job=\"istiod\"})",
     "legendFormat": "Alloc"
    },
    {
     "expr": "sum(go_memstats_heap_inuse_bytes{job=\"istiod\"})",
     "legendFormat": "Heap in-use"
    },
    {
     "expr": "sum(go_memstats_stack_inuse_bytes{job=\"istiod\"})",
     "legendFormat": "Stack in-use"
    },
    {
     "expr": "seed:container_memory_working_set_bytes:sum_by_container{container=\"discovery\"}",
     "legendFormat": "Discovery (container)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "seed:container_cpu_usage_seconds_total:sum_by_container{container=\"discovery\"}\n",
     "legendFormat": "Discovery (container)"
    },
    {
     "expr": "sum(irate(process_cpu_seconds_total{job=\"istiod\"}[$__rate_interval]))",
     "legendFormat": "Discovery (process)"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{container=\"discovery\", pod=~\"$istiod\"})",
     "legendFormat": "Discovery"
    },
    {
     "expr": "sum(container_fs_usage_bytes{container=\"istio-proxy\", pod=~\"$istiod\"})",
     "legendFormat": "Sidecar"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_goroutines{job=\"istiod\", pod=~\"$istiod\"})",
     "legendFormat": "Number of Goroutines"
    }
   ]
  },
  { "title": "Pilot Push Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Pilot Pushes",
   "type": "graph",
   "description": "Shows the rate of pilot pushes",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(clamp_min(pilot_xds_pushes{type=\"cds\", pod=~\"$istiod\"} - pilot_xds_pushes{type=\"cds\", pod=~\"$istiod\"} offset $__interval, 0))",
     "legendFormat": "Cluster"
    },
    {
     "expr": "sum(clamp_min(pilot_xds_pushes{type=\"eds\", pod=~\"$istiod\"} - pilot_xds_pushes{type=\"eds\", pod=~\"$istiod\"} offset $__interval, 0))",
     "legendFormat": "Endpoints"
    },
    {
     "expr": "sum(clamp_min(pilot_xds_pushes{type=\"lds\", pod=~\"$istiod\"} - pilot_xds_pushes{type=\"lds\", pod=~\"$istiod\"} offset $__interval, 0))",
     "legendFormat": "Listeners"
    },
    {
     "expr": "sum(clamp_min(pilot_xds_pushes{type=\"rds\", pod=~\"$istiod\"} - pilot_xds_pushes{type=\"rds\", pod=~\"$istiod\"} offset $__interval, 0))",
     "legendFormat": "Routes"
    },
    {
     "expr": "sum(clamp_min(pilot_xds_pushes{type=\"sds\", pod=~\"$istiod\"} - pilot_xds_pushes{type=\"sds\", pod=~\"$istiod\"} offset $__interval, 0))",
     "legendFormat": "Secrets"
    },
    {
     "expr": "sum(clamp_min(pilot_xds_pushes{type=\"nds\", pod=~\"$istiod\"} - pilot_xds_pushes{type=\"nds\", pod=~\"$istiod\"} offset $__interval, 0))",
     "legendFormat": "Nametables"
    }
   ]
  },
  {
   "title": "Pilot Errors",
   "type": "graph",
   "description": "Captures a variety of pilot errors",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pilot_xds_cds_reject{job=\"istiod\", pod=~\"$istiod\"}) or (absent(pilot_xds_cds_reject{job=\"istiod\", pod=~\"$istiod\"}) - 1)",
     "legendFormat": "Rejected CDS Configs"
    },
    {
     "expr": "sum(pilot_xds_eds_reject{job=\"istiod\", pod=~\"$istiod\"}) or (absent(pilot_xds_eds_reject{job=\"istiod\", pod=~\"$istiod\"}) - 1)",
     "legendFormat": "Rejected EDS Configs"
    },
    {
     "expr": "sum(pilot_xds_rds_reject{job=\"istiod\", pod=~\"$istiod\"}) or (absent(pilot_xds_rds_reject{job=\"istiod\", pod=~\"$istiod\"}) - 1)",
     "legendFormat": "Rejected RDS Configs"
    },
    {
     "expr": "sum(pilot_xds_lds_reject{job=\"istiod\", pod=~\"$istiod\"}) or (absent(pilot_xds_lds_reject{job=\"istiod\", pod=~\"$istiod\"}) - 1)",
     "legendFormat": "Rejected LDS Configs"
    },
    {
     "expr": "sum(rate(pilot_xds_write_timeout{job=\"istiod\", pod=~\"$istiod\"}[$__rate_interval]))",
     "legendFormat": "Write Timeouts"
    },
    {
     "expr": "sum(rate(pilot_total_xds_internal_errors{job=\"istiod\", pod=~\"$istiod\"}[$__rate_interval]))",
     "legendFormat": "Internal Errors"
    },
    {
     "expr": "sum(rate(pilot_total_xds_rejects{job=\"istiod\", pod=~\"$istiod\"}[$__rate_interval]))",
     "legendFormat": "Config Rejection Rate"
    },
    {
     "expr": "sum(rate(pilot_xds_push_context_errors{job=\"istiod\", pod=~\"$istiod\"}[$__rate_interval]))",
     "legendFormat": "Push Context Errors"
    },
    {
     "expr": "sum(rate(pilot_xds_write_timeout{job=\"istiod\", pod=~\"$istiod\"}[$__rate_interval]))",
     "legendFormat": "Push Timeouts"
    }
   ]
  },
  {
   "title": "Proxy Push Time",
   "type": "graph",
   "description": "Shows the total time it takes to push a config update to a proxy",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(pilot_proxy_convergence_time_bucket[$__rate_interval])) by (le))",
     "legendFormat": "p50 "
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(pilot_proxy_convergence_time_bucket[$__rate_interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(pilot_proxy_convergence_time_bucket[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(pilot_proxy_convergence_time_bucket[$__rate_interval])) by (le))",
     "legendFormat": "p99.9"
    }
   ]
  },
  {
   "title": "Conflicts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pilot_conflict_inbound_listener{job=\"istiod\"}",
     "legendFormat": "Inbound Listeners"
    },
    {
     "expr": "pilot_conflict_outbound_listener_http_over_current_tcp{job=\"istiod\"}",
     "legendFormat": "Outbound Listeners (http over current tcp)"
    },
    {
     "expr": "pilot_conflict_outbound_listener_tcp_over_current_tcp{job=\"istiod\"}",
     "legendFormat": "Outbound Listeners (tcp over current tcp)"
    },
    {
     "expr": "pilot_conflict_outbound_listener_tcp_over_current_http{job=\"istiod\"}",
     "legendFormat": "Outbound Listeners (tcp over current http)"
    }
   ]
  },
  {
   "title": "ADS Monitoring",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(pilot_virt_services{job=\"istiod\"})",
     "legendFormat": "Virtual Services"
    },
    {
     "expr": "avg(pilot_services{job=\"istiod\"})",
     "legendFormat": "Services"
    },
    {
     "expr": "sum(pilot_xds{job=\"istiod\"}) by (pod)",
     "legendFormat": "Connected Endpoints {{pod}}"
    }
   ]
  },
  { "title": "Envoy Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Envoy Details",
   "type": "graph",
   "description": "Shows details about Envoy proxies in the mesh",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(clamp_min(envoy_cluster_upstream_cx_total{cluster_name=\"xds-grpc\", pod=~\"$igw\"} - envoy_cluster_upstream_cx_total{cluster_name=\"xds-grpc\", pod=~\"$igw\"} offset $__interval, 0))",
     "legendFormat": "XDS Connections"
    },
    {
     "expr": "sum(clamp_min(envoy_cluster_upstream_cx_connect_fail{cluster_name=\"xds-grpc\", pod=~\"$igw\"} - envoy_cluster_upstream_cx_connect_fail{cluster_name=\"xds-grpc\", pod=~\"$igw\"} offset $__interval, 0))",
     "legendFormat": "XDS Connection Failures"
    },
    {
     "expr": "sum(clamp_min(envoy_server_hot_restart_epoch{pod=~\"$igw\"} - envoy_server_hot_restart_epoch{pod=~\"$igw\"} offset $__interval, 0))",
     "legendFormat": "Envoy Restarts"
    }
   ]
  },
  {
   "title": "XDS Active Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_cx_active{cluster_name=\"xds-grpc\"})",
     "legendFormat": "XDS Active Connections"
    }
   ]
  },
  {
   "title": "XDS Requests Size",
   "type": "graph",
   "description": "Shows the size of XDS requests and responses",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "max(rate(envoy_cluster_upstream_cx_rx_bytes_total{cluster_name=\"xds-grpc\"}[$__rate_interval]))",
     "legendFormat": "XDS Response Bytes Max"
    },
    {
     "expr": "quantile(0.5, rate(envoy_cluster_upstream_cx_rx_bytes_total{cluster_name=\"xds-grpc\"}[$__rate_interval]))",
     "legendFormat": "XDS Response Bytes Average"
    },
    {
     "expr": "max(rate(envoy_cluster_upstream_cx_tx_bytes_total{cluster_name=\"xds-grpc\"}[$__rate_interval]))",
     "legendFormat": "XDS Request Bytes Max"
    },
    {
     "expr": "quantile(.5, rate(envoy_cluster_upstream_cx_tx_bytes_total{cluster_name=\"xds-grpc\"}[$__rate_interval]))",
     "legendFormat": "XDS Request Bytes Average"
    }
   ]
  },
  { "title": "Webhooks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Configuration Validation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(clamp_min(galley_validation_passed{pod=~\"$istiod\"} - galley_validation_passed{pod=~\"$istiod\"} offset $__interval, 0))",
     "legendFormat": "Validations (Success)"
    },
    {
     "expr": "sum(clamp_min(galley_validation_failed{pod=~\"$istiod\"} - galley_validation_failed{pod=~\"$istiod\"} offset $__interval, 0))",
     "legendFormat": "Validation (Failure)"
    }
   ]
  },
  {
   "title": "Sidecar Injection",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(sidecar_injection_success_total{pod=~\"$istiod\"}[$__rate_interval]))) or absent(sidecar_injection_success_total{pod=~\"$istiod\"})-1",
     "legendFormat": "Injections (Success)"
    },
    {
     "expr": "(sum(rate(sidecar_injection_failure_total{pod=~\"$istiod\"}[$__rate_interval]))) or absent(sidecar_injection_failure_total{pod=~\"$istiod\"})-1",
     "legendFormat": "Injections (Failure)"
    }
   ]
  }
 ]
}