apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
metadata:
  name: local

nodes: []

containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry]
    config_path = "/etc/containerd/certs.d"

networking:
  disableDefaultCNI: true # disable kindnet since we install calico for network policy support
  ipFamily: ipv4
  podSubnet: 10.0.0.0/15
  serviceSubnet: 10.2.0.0/16
