image: kindest/node:v1.35.1@sha256:05d7bcdefbda08b4e038f644c4df690cdac3fba8b06f8289f30e10026720a1ab

repositoryRoot: "."

gardener:
  selfHostedShoot:
    deployed: true
    listenAddress: 172.18.255.4
    virtualGarden:
      listenAddress: 172.18.255.3

networking:
  ipFamily: ipv4
  podSubnet: 10.0.0.0/15
  serviceSubnet: 10.2.0.0/16

#workers:
#- zone: "1"
#- zone: "2"
