{
 "title": "Shoot SLI",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "iaas",
    "query": "label_values(probe_failure, iaas)"
   },
   {
    "name": "purpose",
    "query": "label_values(probe_failure, purpose)"
   },
   {
    "name": "project",
    "query": "label_values(probe_failure, project)"
   },
   {
    "name": "window",
    "query": "label_values(probe_failure:run:time:total:percent, window)"
   },
   {
    "name": "term",
    "query": "label_values(probe_failure:run:time:total:percent,term)"
   },
   { "name": "SLO", "query": "99.95,99.9,99,95,50,:)" }
  ]
 },
 "panels": [
  {
   "title": "Welcome",
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard is one possible\nvisualisation for the error budgets\nof the shoots, grouped by the infrastructure.\n\nQuestions/comments: #gardener-monitoring"
   }
  },
  {
   "title": "Min over past 24h, excluding worst 10%",
   "type": "stat",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "min_over_time((1- quantile(0.9, probe_failure:run:time:total:percent{iaas=~\"$iaas\"}) by (iaas))[24h:10m])",
     "legendFormat": "{{iaas}}"
    }
   ]
  },
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Shoot SLIs",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "1 - max(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=\"$term\",window=\"$window\"}) by (iaas)"
      },
      {
       "expr": "count(probe_failure:run{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\"}) by (iaas)"
      },
      {
       "expr": "1 - quantile(0.9,probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=\"$term\",window=\"$window\"}) by (iaas)"
      },
      {
       "expr": "1 - avg(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=\"$term\",window=\"$window\"}) by (iaas)"
      },
      {
       "expr": "1 - min(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=\"$term\",window=\"$window\"}) by (iaas)"
      }
     ]
    },
    {
     "title": "Top 10 Shoots exceeding the SLO",
     "type": "table",
     "description": "No data means that no shoot cluster exceeds the SLO",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "targets": [
      {
       "expr": "topk(10,probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\", term=~\"$term\", window=\"$window\"} > 1-$SLO/100) * 100"
      }
     ]
    },
    {
     "title": "Shoot SLI + Error Budget, excluding worst 10%)",
     "type": "graph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "1- quantile(0.9, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"}) by (iaas)",
       "legendFormat": "{{iaas}}"
      },
      { "expr": "$SLO/100", "legendFormat": "SLO" },
      { "expr": "1", "legendFormat": "100%" }
     ]
    }
   ]
  },
  {
   "title": "Funnel",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Funnel",
     "type": "graph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "1- max(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "min"
      },
      { "expr": "$SLO/100", "legendFormat": "SLO" },
      {
       "expr": "1- min(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "max"
      },
      {
       "expr": "1- quantile(0.1, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "90%"
      },
      {
       "expr": "1- quantile(0.9, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "10%"
      },
      {
       "expr": "1- quantile(0.5, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "50%"
      },
      {
       "expr": "1- avg(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "avg"
      },
      {
       "expr": "count(probe_failure:run{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\"})",
       "legendFormat": "# of shoots"
      }
     ]
    }
   ]
  },
  {
   "title": "Tiny Funnels",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tiny Funnel for $iaas",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 3 },
     "repeat": "iaas",
     "targets": [
      {
       "expr": "1- max(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "min"
      },
      { "expr": "$SLO/100", "legendFormat": "SLO" },
      {
       "expr": "1- min(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "max"
      },
      {
       "expr": "1- quantile(0.1, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "90%"
      },
      {
       "expr": "1- quantile(0.9, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "10%"
      },
      {
       "expr": "1- quantile(0.5, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "50%"
      },
      {
       "expr": "1- avg(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "avg"
      },
      {
       "expr": "count(probe_failure:run{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\"})",
       "legendFormat": "# of shoots"
      }
     ]
    },
    {
     "title": "Tiny Funnel for $iaas",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 3 },
     "targets": [
      {
       "expr": "1- max(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "min"
      },
      { "expr": "$SLO/100", "legendFormat": "SLO" },
      {
       "expr": "1- min(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "max"
      },
      {
       "expr": "1- quantile(0.1, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "90%"
      },
      {
       "expr": "1- quantile(0.9, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "10%"
      },
      {
       "expr": "1- quantile(0.5, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "50%"
      },
      {
       "expr": "1- avg(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "avg"
      },
      {
       "expr": "count(probe_failure:run{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\"})",
       "legendFormat": "# of shoots"
      }
     ]
    },
    {
     "title": "Tiny Funnel for $iaas",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "1- max(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "min"
      },
      { "expr": "$SLO/100", "legendFormat": "SLO" },
      {
       "expr": "1- min(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "max"
      },
      {
       "expr": "1- quantile(0.1, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "90%"
      },
      {
       "expr": "1- quantile(0.9, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "10%"
      },
      {
       "expr": "1- quantile(0.5, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "50%"
      },
      {
       "expr": "1- avg(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "avg"
      },
      {
       "expr": "count(probe_failure:run{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\"})",
       "legendFormat": "# of shoots"
      }
     ]
    },
    {
     "title": "Tiny Funnel for $iaas",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 3 },
     "targets": [
      {
       "expr": "1- max(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "min"
      },
      { "expr": "$SLO/100", "legendFormat": "SLO" },
      {
       "expr": "1- min(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "max"
      },
      {
       "expr": "1- quantile(0.1, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "90%"
      },
      {
       "expr": "1- quantile(0.9, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "10%"
      },
      {
       "expr": "1- quantile(0.5, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "50%"
      },
      {
       "expr": "1- avg(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "avg"
      },
      {
       "expr": "count(probe_failure:run{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\"})",
       "legendFormat": "# of shoots"
      }
     ]
    },
    {
     "title": "Tiny Funnel for $iaas",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "1- max(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "min"
      },
      { "expr": "$SLO/100", "legendFormat": "SLO" },
      {
       "expr": "1- min(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "max"
      },
      {
       "expr": "1- quantile(0.1, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "90%"
      },
      {
       "expr": "1- quantile(0.9, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "10%"
      },
      {
       "expr": "1- quantile(0.5, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "50%"
      },
      {
       "expr": "1- avg(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "avg"
      },
      {
       "expr": "count(probe_failure:run{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\"})",
       "legendFormat": "# of shoots"
      }
     ]
    },
    {
     "title": "Tiny Funnel for $iaas",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 11 },
     "targets": [
      {
       "expr": "1- max(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "min"
      },
      { "expr": "$SLO/100", "legendFormat": "SLO" },
      {
       "expr": "1- min(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "max"
      },
      {
       "expr": "1- quantile(0.1, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "90%"
      },
      {
       "expr": "1- quantile(0.9, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "10%"
      },
      {
       "expr": "1- quantile(0.5, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "50%"
      },
      {
       "expr": "1- avg(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "avg"
      },
      {
       "expr": "count(probe_failure:run{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\"})",
       "legendFormat": "# of shoots"
      }
     ]
    },
    {
     "title": "Tiny Funnel for $iaas",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "1- max(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "min"
      },
      { "expr": "$SLO/100", "legendFormat": "SLO" },
      {
       "expr": "1- min(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "max"
      },
      {
       "expr": "1- quantile(0.1, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "90%"
      },
      {
       "expr": "1- quantile(0.9, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "10%"
      },
      {
       "expr": "1- quantile(0.5, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "50%"
      },
      {
       "expr": "1- avg(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "avg"
      },
      {
       "expr": "count(probe_failure:run{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\"})",
       "legendFormat": "# of shoots"
      }
     ]
    },
    {
     "title": "Tiny Funnel for $iaas",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 11 },
     "targets": [
      {
       "expr": "1- max(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "min"
      },
      { "expr": "$SLO/100", "legendFormat": "SLO" },
      {
       "expr": "1- min(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "max"
      },
      {
       "expr": "1- quantile(0.1, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "90%"
      },
      {
       "expr": "1- quantile(0.9, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "10%"
      },
      {
       "expr": "1- quantile(0.5, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "50%"
      },
      {
       "expr": "1- avg(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "avg"
      },
      {
       "expr": "count(probe_failure:run{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\"})",
       "legendFormat": "# of shoots"
      }
     ]
    },
    {
     "title": "Tiny Funnel for $iaas",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "1- max(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "min"
      },
      { "expr": "$SLO/100", "legendFormat": "SLO" },
      {
       "expr": "1- min(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "max"
      },
      {
       "expr": "1- quantile(0.1, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "90%"
      },
      {
       "expr": "1- quantile(0.9, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "10%"
      },
      {
       "expr": "1- quantile(0.5, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "50%"
      },
      {
       "expr": "1- avg(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "avg"
      },
      {
       "expr": "count(probe_failure:run{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\"})",
       "legendFormat": "# of shoots"
      }
     ]
    }
   ]
  },
  {
   "title": "Funnel for $iaas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "repeat": "iaas",
   "collapsed": true,
   "panels": [
    {
     "title": "Funnel for $iaas",
     "type": "graph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "1- max(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "min"
      },
      { "expr": "$SLO/100", "legendFormat": "SLO" },
      {
       "expr": "1- min(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "max"
      },
      {
       "expr": "1- quantile(0.1, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "90%"
      },
      {
       "expr": "1- quantile(0.9, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "10%"
      },
      {
       "expr": "1- quantile(0.5, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "50%"
      },
      {
       "expr": "1- avg(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "avg"
      },
      {
       "expr": "count(probe_failure:run{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\"})",
       "legendFormat": "# of shoots"
      }
     ]
    }
   ]
  },
  {
   "title": "Funnel for $iaas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Funnel for $iaas",
     "type": "graph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "1- max(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "min"
      },
      { "expr": "$SLO/100", "legendFormat": "SLO" },
      {
       "expr": "1- min(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "max"
      },
      {
       "expr": "1- quantile(0.1, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "90%"
      },
      {
       "expr": "1- quantile(0.9, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "10%"
      },
      {
       "expr": "1- quantile(0.5, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "50%"
      },
      {
       "expr": "1- avg(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "avg"
      },
      {
       "expr": "count(probe_failure:run{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\"})",
       "legendFormat": "# of shoots"
      }
     ]
    }
   ]
  },
  {
   "title": "Funnel for $iaas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Funnel for $iaas",
     "type": "graph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "1- max(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "min"
      },
      { "expr": "$SLO/100", "legendFormat": "SLO" },
      {
       "expr": "1- min(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "max"
      },
      {
       "expr": "1- quantile(0.1, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "90%"
      },
      {
       "expr": "1- quantile(0.9, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "10%"
      },
      {
       "expr": "1- quantile(0.5, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "50%"
      },
      {
       "expr": "1- avg(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "avg"
      },
      {
       "expr": "count(probe_failure:run{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\"})",
       "legendFormat": "# of shoots"
      }
     ]
    }
   ]
  },
  {
   "title": "Funnel for $iaas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Funnel for $iaas",
     "type": "graph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "1- max(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "min"
      },
      { "expr": "$SLO/100", "legendFormat": "SLO" },
      {
       "expr": "1- min(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "max"
      },
      {
       "expr": "1- quantile(0.1, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "90%"
      },
      {
       "expr": "1- quantile(0.9, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "10%"
      },
      {
       "expr": "1- quantile(0.5, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "50%"
      },
      {
       "expr": "1- avg(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "avg"
      },
      {
       "expr": "count(probe_failure:run{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\"})",
       "legendFormat": "# of shoots"
      }
     ]
    }
   ]
  },
  {
   "title": "Funnel for $iaas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Funnel for $iaas",
     "type": "graph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "1- max(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "min"
      },
      { "expr": "$SLO/100", "legendFormat": "SLO" },
      {
       "expr": "1- min(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "max"
      },
      {
       "expr": "1- quantile(0.1, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "90%"
      },
      {
       "expr": "1- quantile(0.9, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "10%"
      },
      {
       "expr": "1- quantile(0.5, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "50%"
      },
      {
       "expr": "1- avg(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "avg"
      },
      {
       "expr": "count(probe_failure:run{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\"})",
       "legendFormat": "# of shoots"
      }
     ]
    }
   ]
  },
  {
   "title": "Funnel for $iaas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Funnel for $iaas",
     "type": "graph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "1- max(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "min"
      },
      { "expr": "$SLO/100", "legendFormat": "SLO" },
      {
       "expr": "1- min(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "max"
      },
      {
       "expr": "1- quantile(0.1, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "90%"
      },
      {
       "expr": "1- quantile(0.9, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "10%"
      },
      {
       "expr": "1- quantile(0.5, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "50%"
      },
      {
       "expr": "1- avg(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "avg"
      },
      {
       "expr": "count(probe_failure:run{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\"})",
       "legendFormat": "# of shoots"
      }
     ]
    }
   ]
  },
  {
   "title": "Funnel for $iaas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Funnel for $iaas",
     "type": "graph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "1- max(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "min"
      },
      { "expr": "$SLO/100", "legendFormat": "SLO" },
      {
       "expr": "1- min(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "max"
      },
      {
       "expr": "1- quantile(0.1, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "90%"
      },
      {
       "expr": "1- quantile(0.9, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "10%"
      },
      {
       "expr": "1- quantile(0.5, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "50%"
      },
      {
       "expr": "1- avg(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "avg"
      },
      {
       "expr": "count(probe_failure:run{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\"})",
       "legendFormat": "# of shoots"
      }
     ]
    }
   ]
  },
  {
   "title": "Funnel for $iaas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Funnel for $iaas",
     "type": "graph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "1- max(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "min"
      },
      { "expr": "$SLO/100", "legendFormat": "SLO" },
      {
       "expr": "1- min(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "max"
      },
      {
       "expr": "1- quantile(0.1, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "90%"
      },
      {
       "expr": "1- quantile(0.9, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "10%"
      },
      {
       "expr": "1- quantile(0.5, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "50%"
      },
      {
       "expr": "1- avg(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "avg"
      },
      {
       "expr": "count(probe_failure:run{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\"})",
       "legendFormat": "# of shoots"
      }
     ]
    }
   ]
  },
  {
   "title": "Funnel for $iaas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Funnel for $iaas",
     "type": "graph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "1- max(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "min"
      },
      { "expr": "$SLO/100", "legendFormat": "SLO" },
      {
       "expr": "1- min(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "max"
      },
      {
       "expr": "1- quantile(0.1, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "90%"
      },
      {
       "expr": "1- quantile(0.9, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "10%"
      },
      {
       "expr": "1- quantile(0.5, probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "50%"
      },
      {
       "expr": "1- avg(probe_failure:run:time:total:percent{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\",term=~\"$term\",window=\"$window\"})",
       "legendFormat": "avg"
      },
      {
       "expr": "count(probe_failure:run{iaas=~\"$iaas\",purpose=~\"$purpose\",project=~\"$project\"})",
       "legendFormat": "# of shoots"
      }
     ]
    }
   ]
  }
 ]
}