// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gardener/gardener/pkg/client/kubernetes (interfaces: PodExecutor)
//
// Generated by this command:
//
//	mockgen -package mock -destination=mocks_podexecutor.go github.com/gardener/gardener/pkg/client/kubernetes PodExecutor
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPodExecutor is a mock of PodExecutor interface.
type MockPodExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockPodExecutorMockRecorder
	isgomock struct{}
}

// MockPodExecutorMockRecorder is the mock recorder for MockPodExecutor.
type MockPodExecutorMockRecorder struct {
	mock *MockPodExecutor
}

// NewMockPodExecutor creates a new mock instance.
func NewMockPodExecutor(ctrl *gomock.Controller) *MockPodExecutor {
	mock := &MockPodExecutor{ctrl: ctrl}
	mock.recorder = &MockPodExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPodExecutor) EXPECT() *MockPodExecutorMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockPodExecutor) Execute(ctx context.Context, namespace, name, containerName, command string) (io.Reader, io.Reader, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, namespace, name, containerName, command)
	ret0, _ := ret[0].(io.Reader)
	ret1, _ := ret[1].(io.Reader)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Execute indicates an expected call of Execute.
func (mr *MockPodExecutorMockRecorder) Execute(ctx, namespace, name, containerName, command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockPodExecutor)(nil).Execute), ctx, namespace, name, containerName, command)
}
