apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: health
spec:
  groups:
    - name: health.rules
      rules:
        # Scrape jobs are down
        - record: health:meta:job:down
          labels:
            type: health:meta
          expr: up == 0 == bool 0

        # Scrape jobs are down for a period of time
        - record: health:meta:job:failing
          labels:
            type: health:meta
          expr: up + (sum_over_time(up[4m] offset 1m) or up * on () group_left() vector(0)) == 0 == bool 0

        # No samples scraped
        - record: health:meta:job:scrapes:empty
          labels:
            type: health:meta
          expr: scrape_samples_scraped == 0 == bool 0

        # kube-state-metrics metrics are absent
        - record: health:meta:kube_state_metrics:absent
          expr: absent(kube_pod_container_resource_requests{pod=~"gardenlet-.+"})
          labels:
            type: health:meta

        # Federated cAdvisor metrics are absent
        - record: health:meta:federate:cadvisor:absent
          expr: absent(container_cpu_usage_seconds_total{pod=~"gardenlet-.+"})
          labels:
            type: health:meta

        # Create reason label for failing health checks
        - record: health:meta:failing
          expr: |
            label_replace({__name__!="health:meta:failing", type="health:meta"}, "reason", "$1", "__name__", "health:meta:(.*)")

        # Report failing health checks but inhibit absent metrics when jobs are down
        - record: health:failing
          labels:
            type: health
          expr: |2
              health:meta:failing{reason="job:failing"}
            or
              health:meta:failing and on () absent(health:meta:job:down)

        # Flapping
        - record: health:flapping
          labels:
            type: health
          expr: |
            count_over_time((count_over_time(health:meta:failing[2m:]) == 1)[10m:]) > 4 > bool 4
