{
 "title": "API Server",
 "tags": [
  "controlplane",
  "seed"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "apiserver",
    "label": "API Server",
    "query": {
     "query": "label_values(apiserver_request_total,pod)"
    }
   },
   {
    "name": "verb",
    "label": "Verbs",
    "query": "DELETE,PUT,POST,DELETECOLLECTION,WATCH,GET,LIST,PATCH,CONNECT,UPDATE,CREATE"
   },
   { "name": "operation", "label": "Admission Operation", "query": "CREATE,UPDATE,DELETE" },
   {
    "name": "quantile",
    "query": {
     "query": "label_values(apiserver_latency_seconds:quantile, quantile)"
    }
   }
  ]
 },
 "panels": [
  { "title": "API Server Admission", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Duration Per In-Tree Plugin",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.9,sum(rate(apiserver_admission_controller_admission_duration_seconds_bucket{pod=~\"$apiserver\",operation=~\"$operation\"}[$__rate_interval])) by(le,name))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Duration Per Webhook",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90,sum(rate(apiserver_admission_webhook_admission_duration_seconds_bucket{pod=~\"$apiserver\",operation=~\"$operation\"}[$__rate_interval])) by(le,name))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Duration Per Step",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90,sum(rate(apiserver_admission_step_admission_duration_seconds_bucket{pod=~\"$apiserver\",operation=~\"$operation\"}[$__rate_interval])) by(le,type))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Rejection Count Per Webhook",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "none", "label": "rejections/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_admission_webhook_rejection_count{pod=~\"$apiserver\",operation=~\"$operation\"}[$__rate_interval])) by (name,error_type)",
     "legendFormat": "{{name}} ({{error_type}})"
    }
   ]
  },
  { "title": "API Server Auditing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Total Events",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "events/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_audit_event_total{pod=~\"$apiserver\"}[$__rate_interval]))",
     "legendFormat": "Events"
    }
   ]
  },
  {
   "title": "Rejected Events",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "events/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_audit_requests_rejected_total{pod=~\"$apiserver\"}[$__rate_interval]))",
     "legendFormat": "Events"
    }
   ]
  },
  { "title": "API Server Authentication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Total Authenticated User Requests",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "requests/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(authenticated_user_requests{pod=~\"$apiserver\"}[$__rate_interval]))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Authentication Attempts By Result",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "attemps/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(authentication_attempts{pod=~\"$apiserver\"}[$__rate_interval])) by(result)",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "API Server Request and Responses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 }
  },
  {
   "title": "Overall Request Rates",
   "type": "graph",
   "description": "Shows the rate of all API server requests.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "requests/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{pod=~\"$apiserver\"}[$__rate_interval]))",
     "legendFormat": "Request Rate"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "graph",
   "description": "Shows the request latency of each verb for the API server.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max by(verb, quantile) (apiserver_latency_seconds:quantile{pod=~\"$apiserver\", verb=~\"$verb\",quantile=~\"$quantile\",subresource!~\"log|portforward|exec|proxy|attach\"})",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "Request Rates Per Verb",
   "type": "graph",
   "description": "Shows the request rate per verb for the API server.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short", "label": "requests/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{pod=~\"$apiserver\"}[$__rate_interval])) by(verb)",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "Request Rates Per Verb (Avg)",
   "type": "graph",
   "description": "Shows the average rate of requests to the API server.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short", "label": "requests/s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(apiserver_request_total{pod=~\"$apiserver\",verb=~\"$verb\"}[$__rate_interval])) by (verb)",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "Request Rates Per Scope",
   "type": "graph",
   "description": "Shows the request rate per scope for the API server.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short", "label": "requests/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{pod=~\"$apiserver\",scope!=\"\"}[$__rate_interval])) by(scope)",
     "legendFormat": "{{scope}}-scope"
    }
   ]
  },
  {
   "title": "Request Rates Per Resource",
   "type": "graph",
   "description": "Shows the request rate per resource for the API server.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short", "label": "requests/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{pod=~\"$apiserver\"}[$__rate_interval])) by(resource)",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "API Server Request Rates Per Verb And Resource",
   "type": "graph",
   "description": "Shows the request rate per verb and resource for the API server.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short", "label": "requests/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{verb=~\"$verb\"}[$__rate_interval])) by(resource,verb,subresource)",
     "legendFormat": "{{verb}} /{{resource}}/{{subresource}}"
    }
   ]
  },
  {
   "title": "Inflight Requests By Request Kind",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short", "label": "requests/s" }
   ],
   "targets": [
    {
     "expr": "sum(max_over_time(apiserver_current_inflight_requests{pod=~\"$apiserver\"}[1m])) by (request_kind)",
     "legendFormat": "{{request_kind}}"
    }
   ]
  },
  {
   "title": "Inqueue Requests By Request Kind",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "short", "label": "requests/s" }
   ],
   "targets": [
    {
     "expr": "sum(max_over_time(apiserver_current_inqueue_requests{pod=~\"$apiserver\"}[1m])) by (request_kind)",
     "legendFormat": "{{request_kind}}"
    }
   ]
  },
  {
   "title": "Response Sizes Per Resource",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90,sum(rate(apiserver_response_sizes_bucket{pod=~\"$apiserver\",verb=~\"$verb\"}[$__rate_interval])) by(le,resource,subresource))",
     "legendFormat": "{{resource}}{{subresource}}"
    }
   ]
  },
  {
   "title": "Request Terminations By Resource And Code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_terminations_total{pod=~\"$apiserver\",verb=~\"$verb\"}[$__rate_interval])) by (resource,subresource,code)",
     "legendFormat": "{{ resource }}{{subresource}} ({{code}})"
    }
   ]
  },
  {
   "title": "Response Size Rate Per Resource and Verb",
   "type": "graph",
   "description": "This panel shows the rate of response sizes by resource and verb.\n\nOutstandingly high values could give a hint for shoot operators on where\nto start on the journey of reducing the load on the API servers,\nby making sure to use WATCH requests instead of periodic LIST and\nGET requests in the various controllers.\n\nHigh values for WATCH requests could hint at reducing the rate of change for the specific resource.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_response_sizes_sum{pod=~\"$apiserver\",verb=~\"$verb\"}[$__rate_interval])) by(resource, verb) > 0",
     "legendFormat": "{{resource}} {{verb}}"
    }
   ]
  },
  { "title": "API Server Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "ETCD Total Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(etcd_db_total_size_in_bytes{pod=~\"$apiserver\"}) by (endpoint) or max(apiserver_storage_db_total_size_in_bytes{pod=~\"$apiserver\"}) by (endpoint)",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "ETCD Object Counts By Resource",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 93 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(etcd_object_counts{pod=~\"$apiserver\"}) by (resource) or max(apiserver_storage_objects{pod=~\"$apiserver\"}) by (resource)",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Storage Transformation Duration By Type",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90,sum(rate(apiserver_storage_transformation_duration_seconds_bucket{pod=~\"$apiserver\"}[$__rate_interval])) by(le,transformation_type))",
     "legendFormat": "{{transformation_type}}"
    }
   ]
  },
  {
   "title": "Total Storage Transformation Operations By Type And Prefix",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 99 },
   "yaxes": [
    { "format": "none", "label": "operations/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_storage_transformation_operations_total{pod=~\"$apiserver\"}[$__rate_interval])) by (transformation_type,transformer_prefix)",
     "legendFormat": "{{transformation_type}},{{transformer_prefix}}"
    }
   ]
  },
  {
   "title": "ETCD Request Duration Per Type",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.9,sum(rate(etcd_request_duration_seconds_bucket{pod=~\"$apiserver\"}[$__rate_interval])) by(le,type))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "API Server Watches", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 111 } },
  {
   "title": "Registered Watches Per Kind",
   "type": "graph",
   "description": "Panel shows how many watches are open (including the API Server's in-tree admission plug-ins).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "    sum by (kind) (apiserver_registered_watchers{pod=~\"$apiserver\",kind!=\"\"})\n  + on () group_left ()\n    absent(apiserver_longrunning_requests) * 0\nor\n  sum by (resource) (apiserver_longrunning_requests{pod=~\"$apiserver\",verb=\"WATCH\"})",
     "legendFormat": "{{resource}}{{kind}}"
    }
   ]
  },
  {
   "title": "Init Event Count Per Resource",
   "type": "graph",
   "description": "Counter of init events processed in watch cache.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "yaxes": [
    { "format": "short", "label": "watch events/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_init_events_total{pod=~\"$apiserver\"}[$__rate_interval])) by(resource)",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Event Size Per Kind",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 120 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90,sum(rate(apiserver_watch_events_sizes_bucket{pod=~\"$apiserver\"}[$__rate_interval])) by(le,kind))",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Event Count Per Kind",
   "type": "graph",
   "description": "Shows the watch event count per kind",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 120 },
   "yaxes": [
    { "format": "short", "label": "watch events/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_watch_events_total{pod=~\"$apiserver\"}[$__rate_interval])) by(kind)",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Cache Capacity Increases By Resource",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 127 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(watch_cache_capacity_increase_total{pod=~\"$apiserver\"}[$__rate_interval])) by (resource)",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Cache Capacity Decreases By Resource",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 127 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(watch_cache_capacity_decrease_total{pod=~\"$apiserver\"}[$__rate_interval])) by (resource)",
     "legendFormat": "{{resource}}"
    }
   ]
  }
 ]
}