apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# We need the secret to be applied before the SecretBinding and CredentialsBinding. If we used a `secretGenerator` here,
# the generated would be applied too late. By having a dedicated kustomization we control the order again.
resources:
- kubeconfig
- secretbinding.yaml
- credentialsbinding.yaml
