{{- if hasPrefix "shoot-" .Release.Namespace }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-to-kind-network
  namespace: {{ .Release.Namespace }}
  annotations:
    gardener.cloud/description: Allows egress from pods labeled with 'networking.gardener.cloud/to-kind-network=allowed'
      to all containers in the kind docker network, which includes the infrastructure cluster of provider-local (the
      cluster hosting the machine pods). This is needed for provider-local components (e.g., cloud-controller-manager
      and machine-controller-manager), as the infrastructure cluster is not necessarily the runtime/seed cluster (e.g.,
      for the second seed).
spec:
  podSelector:
    matchLabels:
      networking.gardener.cloud/to-kind-network: allowed
  # The egress rules are the same as in the allow-to-kind-network NetworkPolicy of the provider-local extension, see
  # charts/gardener/provider-local/templates/networkpolicy.yaml. Keep them in sync.
  egress:
  - to:
    # kind network CIDR
    - ipBlock:
        cidr: 172.18.0.0/24
    - ipBlock:
        cidr: fd00:10::/64
    # range for "load balancer" IPs (added to loopback interface on host), including:
    # - local DNS server (bind9): 172.18.255.53 / fd00:ff::53
    # - gind apiserver load balancer: 172.18.255.123
    # - dynamically allocated IPs for LoadBalancer services: 172.18.255.224/27 / fd00:ff::e0/123
    - ipBlock:
        cidr: 172.18.255.0/24
    - ipBlock:
        cidr: fd00:ff::/64
  policyTypes:
  - Egress
{{- end }}
