{
 "title": "Reversed VPN Envoy Proxy",
 "description": "This dashboard shows data for the reversed VPN seed server envoy-proxy.",
 "tags": [
  "network",
  "controlplane",
  "seed"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_cluster_upstream_cx_active{envoy_cluster_name=\"dynamic_forward_proxy_cluster\",job=\"reversed-vpn-envoy-side-car\"}",
     "legendFormat": "active connections"
    }
   ]
  },
  {
   "title": "Connection timeouts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_cluster_upstream_cx_connect_timeout{envoy_cluster_name=\"dynamic_forward_proxy_cluster\",job=\"reversed-vpn-envoy-side-car\"}",
     "legendFormat": "connection timeouts"
    }
   ]
  },
  {
   "title": "Connection fails",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_cluster_upstream_cx_connect_fail{envoy_cluster_name=\"dynamic_forward_proxy_cluster\",job=\"reversed-vpn-envoy-side-car\"}",
     "legendFormat": "failed connections"
    }
   ]
  },
  {
   "title": "Connection establishment",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum(rate(envoy_cluster_upstream_cx_connect_ms_bucket{envoy_cluster_name=\"dynamic_forward_proxy_cluster\",job=\"reversed-vpn-envoy-side-car\"}[$__rate_interval])) by (le))",
     "legendFormat": "99 quantil"
    },
    {
     "expr": "histogram_quantile(0.95,sum(rate(envoy_cluster_upstream_cx_connect_ms_bucket{envoy_cluster_name=\"dynamic_forward_proxy_cluster\",job=\"reversed-vpn-envoy-side-car\"}[$__rate_interval])) by (le))",
     "legendFormat": "95 quantil"
    },
    {
     "expr": "histogram_quantile(0.90,sum(rate(envoy_cluster_upstream_cx_connect_ms_bucket{envoy_cluster_name=\"dynamic_forward_proxy_cluster\",job=\"reversed-vpn-envoy-side-car\"}[$__rate_interval])) by (le))",
     "legendFormat": "90 quantil"
    }
   ]
  },
  {
   "title": "Connection establishment heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by (le)(rate(envoy_cluster_upstream_cx_connect_ms_bucket{envoy_cluster_name=\"dynamic_forward_proxy_cluster\",job=\"reversed-vpn-envoy-side-car\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Upstream connection length",
   "type": "graph",
   "description": "Connections from envoy proxy to VPN shoot.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum(rate(envoy_cluster_upstream_cx_length_ms_bucket{envoy_cluster_name=\"dynamic_forward_proxy_cluster\",job=\"reversed-vpn-envoy-side-car\"}[$__rate_interval])) by (le))",
     "legendFormat": "99 quantil"
    },
    {
     "expr": "histogram_quantile(0.95,sum(rate(envoy_cluster_upstream_cx_length_ms_bucket{envoy_cluster_name=\"dynamic_forward_proxy_cluster\",job=\"reversed-vpn-envoy-side-car\"}[$__rate_interval])) by (le))",
     "legendFormat": "95 quantil"
    },
    {
     "expr": "histogram_quantile(0.90,sum(rate(envoy_cluster_upstream_cx_length_ms_bucket{envoy_cluster_name=\"dynamic_forward_proxy_cluster\",job=\"reversed-vpn-envoy-side-car\"}[$__rate_interval])) by (le))",
     "legendFormat": "90 quantil"
    }
   ]
  },
  {
   "title": "Upstream connection length heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum by (le)(rate(envoy_cluster_upstream_cx_length_ms_bucket{envoy_cluster_name=\"dynamic_forward_proxy_cluster\",job=\"reversed-vpn-envoy-side-car\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Downstream connection length",
   "type": "graph",
   "description": "Connections from envoy proxy to apiserver.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum(rate(envoy_http_downstream_cx_length_ms_bucket{envoy_http_conn_manager_prefix=\"ingress_http\",job=\"reversed-vpn-envoy-side-car\"}[$__rate_interval])) by (le))",
     "legendFormat": "99 quantil"
    },
    {
     "expr": "histogram_quantile(0.95,sum(rate(envoy_http_downstream_cx_length_ms_bucket{envoy_http_conn_manager_prefix=\"ingress_http\",job=\"reversed-vpn-envoy-side-car\"}[$__rate_interval])) by (le))",
     "legendFormat": "95 quantil"
    },
    {
     "expr": "histogram_quantile(0.90,sum(rate(envoy_http_downstream_cx_length_ms_bucket{envoy_http_conn_manager_prefix=\"ingress_http\",job=\"reversed-vpn-envoy-side-car\"}[$__rate_interval])) by (le))",
     "legendFormat": "90 quantil"
    }
   ]
  },
  {
   "title": "Donwstream connection length heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum by (le)(rate(envoy_http_downstream_cx_length_ms_bucket{envoy_http_conn_manager_prefix=\"ingress_http\",job=\"reversed-vpn-envoy-side-car\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(envoy_cluster_upstream_rq_total{envoy_cluster_name=\"dynamic_forward_proxy_cluster\",job=\"reversed-vpn-envoy-side-car\"}[$__rate_interval])",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "Requests completed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(envoy_cluster_upstream_rq_completed{envoy_cluster_name=\"dynamic_forward_proxy_cluster\",job=\"reversed-vpn-envoy-side-car\"}[$__rate_interval])",
     "legendFormat": "completed requests"
    }
   ]
  },
  {
   "title": "Request retries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_cluster_upstream_rq_retry{envoy_cluster_name=\"dynamic_forward_proxy_cluster\",job=\"reversed-vpn-envoy-side-car\"}",
     "legendFormat": "request retries"
    }
   ]
  },
  {
   "title": "Request retry limit exceeded",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_cluster_upstream_rq_retry_limit_exceeded{envoy_cluster_name=\"dynamic_forward_proxy_cluster\",job=\"reversed-vpn-envoy-side-car\"}",
     "legendFormat": "request retry limit exceeded"
    }
   ]
  },
  {
   "title": "Request retry overflow",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_cluster_upstream_rq_retry_overflow{envoy_cluster_name=\"dynamic_forward_proxy_cluster\",job=\"reversed-vpn-envoy-side-car\"}",
     "legendFormat": "request retry overflow"
    }
   ]
  },
  {
   "title": "Request resets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_cluster_upstream_rq_rx_reset{envoy_cluster_name=\"dynamic_forward_proxy_cluster\",job=\"reversed-vpn-envoy-side-car\"}",
     "legendFormat": "remote resets"
    },
    {
     "expr": "envoy_cluster_upstream_rq_tx_reset{envoy_cluster_name=\"dynamic_forward_proxy_cluster\",job=\"reversed-vpn-envoy-side-car\"}",
     "legendFormat": "local resets"
    }
   ]
  },
  {
   "title": "Connection Overflows",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_cluster_upstream_cx_overflow{envoy_cluster_name=\"dynamic_forward_proxy_cluster\",job=\"reversed-vpn-envoy-side-car\"}",
     "legendFormat": "connection overflows"
    }
   ]
  },
  { "title": "Network traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Upstream network traffic",
   "type": "graph",
   "description": "Traffic from envoy proxy to VPN shoot.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(envoy_cluster_upstream_cx_rx_bytes_total{envoy_cluster_name=\"dynamic_forward_proxy_cluster\",job=\"reversed-vpn-envoy-side-car\"}[$__rate_interval])",
     "legendFormat": "in"
    },
    {
     "expr": "rate(envoy_cluster_upstream_cx_tx_bytes_total{envoy_cluster_name=\"dynamic_forward_proxy_cluster\",job=\"reversed-vpn-envoy-side-car\"}[$__rate_interval])",
     "legendFormat": "out"
    }
   ]
  },
  {
   "title": "Downstream network traffic",
   "type": "graph",
   "description": "Traffic from apiserver to envoy proxy.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(envoy_http_downstream_cx_rx_bytes_total{envoy_http_conn_manager_prefix=\"ingress_http\",job=\"reversed-vpn-envoy-side-car\"}[$__rate_interval])",
     "legendFormat": "in"
    },
    {
     "expr": "rate(envoy_http_downstream_cx_tx_bytes_total{envoy_http_conn_manager_prefix=\"ingress_http\",job=\"reversed-vpn-envoy-side-car\"}[$__rate_interval])",
     "legendFormat": "out"
    }
   ]
  },
  { "title": "HTTP codes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Downstream client error rate",
   "type": "graph",
   "description": "This graph shows the client error rate of the reversed VPN server envoy proxy sidecar container.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_xx{envoy_http_conn_manager_prefix=\"ingress_http\", envoy_response_code_class=\"4\",job=\"reversed-vpn-envoy-side-car\"}[$__rate_interval]))/ sum(rate(\nenvoy_http_downstream_rq_xx{envoy_http_conn_manager_prefix=\"ingress_http\",job=\"reversed-vpn-envoy-side-car\"}[$__rate_interval]))",
     "legendFormat": "4xx error rate"
    }
   ]
  },
  {
   "title": "Upstream client error rate",
   "type": "graph",
   "description": "This graph shows the client error rate of the reversed VPN server envoy proxy sidecar container.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_external_upstream_rq_xx{envoy_cluster_name=\"dynamic_forward_proxy_cluster\", envoy_response_code_class=\"4\",job=\"reversed-vpn-envoy-side-car\"}[$__rate_interval]))/ sum(rate(\nenvoy_cluster_external_upstream_rq_xx{envoy_cluster_name=\"dynamic_forward_proxy_cluster\",job=\"reversed-vpn-envoy-side-car\"}[$__rate_interval]))",
     "legendFormat": "4xx error rate"
    }
   ]
  },
  {
   "title": "Downstream server error rate",
   "type": "graph",
   "description": "This graph shows the server error rate of the reversed VPN server envoy proxy sidecar container.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_xx{envoy_http_conn_manager_prefix=\"ingress_http\", envoy_response_code_class=\"5\",job=\"reversed-vpn-envoy-side-car\"}[$__rate_interval]))/ sum(rate(\nenvoy_http_downstream_rq_xx{envoy_http_conn_manager_prefix=\"ingress_http\",job=\"reversed-vpn-envoy-side-car\"}[$__rate_interval]))",
     "legendFormat": "5xx error rate"
    }
   ]
  },
  {
   "title": "Upstream server error rate",
   "type": "graph",
   "description": "This graph shows the server error rate of the reversed VPN server envoy proxy sidecar container.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 85 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_external_upstream_rq_xx{envoy_cluster_name=\"dynamic_forward_proxy_cluster\", envoy_response_code_class=\"5\",job=\"reversed-vpn-envoy-side-car\"}[$__rate_interval]))/ sum(rate(\nenvoy_cluster_external_upstream_rq_xx{envoy_cluster_name=\"dynamic_forward_proxy_cluster\",job=\"reversed-vpn-envoy-side-car\"}[$__rate_interval]))",
     "legendFormat": "5xx error rate"
    }
   ]
  },
  {
   "title": "Downstream successful response rate",
   "type": "graph",
   "description": "This graph shows the successful response rate of the reversed VPN server envoy proxy sidecar container.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_xx{envoy_http_conn_manager_prefix=\"ingress_http\", envoy_response_code_class=\"2\",job=\"reversed-vpn-envoy-side-car\"}[$__rate_interval]))/ sum(rate(\nenvoy_http_downstream_rq_xx{envoy_http_conn_manager_prefix=\"ingress_http\",job=\"reversed-vpn-envoy-side-car\"}[$__rate_interval]))",
     "legendFormat": "2xx successful response rate"
    }
   ]
  },
  {
   "title": "Upstream successful response rate",
   "type": "graph",
   "description": "This graph shows the successful response rate of the reversed VPN server envoy proxy sidecar container.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 94 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_external_upstream_rq_xx{envoy_cluster_name=\"dynamic_forward_proxy_cluster\", envoy_response_code_class=\"2\",job=\"reversed-vpn-envoy-side-car\"}[$__rate_interval]))/ sum(rate(\nenvoy_cluster_external_upstream_rq_xx{envoy_cluster_name=\"dynamic_forward_proxy_cluster\",job=\"reversed-vpn-envoy-side-car\"}[$__rate_interval]))",
     "legendFormat": "2xx successful response rate"
    }
   ]
  },
  { "title": "DNS Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 } },
  {
   "title": "DNS query attempts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(envoy_dns_cache_dynamic_forward_proxy_cache_config_dns_query_attempt{job=\"reversed-vpn-envoy-side-car\"}[$__rate_interval])",
     "legendFormat": "dns query attempts"
    }
   ]
  },
  {
   "title": "DNS query failures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(envoy_dns_cache_dynamic_forward_proxy_cache_config_dns_query_failure{job=\"reversed-vpn-envoy-side-car\"}[$__rate_interval])",
     "legendFormat": "dns query failures"
    }
   ]
  },
  {
   "title": "Successful DNS queries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(envoy_dns_cache_dynamic_forward_proxy_cache_config_dns_query_success{job=\"reversed-vpn-envoy-side-car\"}[$__rate_interval])",
     "legendFormat": "successful dns queries"
    }
   ]
  },
  {
   "title": "DNS Cache Hosts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_dns_cache_dynamic_forward_proxy_cache_config_num_hosts{job=\"reversed-vpn-envoy-side-car\"}",
     "legendFormat": "hosts"
    }
   ]
  },
  {
   "title": "DNS Cache Host Overflows",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_dns_cache_dynamic_forward_proxy_cache_config_host_overflow{job=\"reversed-vpn-envoy-side-car\"}",
     "legendFormat": "host overflows"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 128 } },
  {
   "title": "Memory stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 129 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "envoy_server_memory_allocated{job=\"reversed-vpn-envoy-side-car\"}",
     "legendFormat": "memory allocated"
    },
    {
     "expr": "envoy_server_memory_heap_size{job=\"reversed-vpn-envoy-side-car\"}",
     "legendFormat": "memory heap size"
    },
    {
     "expr": "envoy_server_memory_physical_size{job=\"reversed-vpn-envoy-side-car\"}",
     "legendFormat": "physical memory size"
    }
   ]
  }
 ]
}