apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

sortOptions:
  order: fifo

resources:
- ../../base

components:
- ../../../../gardenconfig/components/credentials/secret-project-garden-with-kind-kubeconfig

patches:
- path: patch-shoot-managed-infra.yaml
- target:
    kind: Shoot
  patch: |
    # The base Shoot is configured for HA (3 control plane nodes). The managed-infra scenario only
    # supports single-node control planes for now, so we override the HA settings back to single-node.
    - op: remove
      path: /spec/controlPlane
    - op: replace
      path: /spec/provider/workers/0/minimum
      value: 1
    - op: replace
      path: /spec/provider/workers/0/maximum
      value: 1
    - op: remove
      path: /spec/provider/workers/0/maxSurge
    - op: remove
      path: /spec/provider/workers/0/maxUnavailable

    - op: add
      path: /spec/provider/workers/0/machine/image/version
      value: 1.0.0
    - op: add
      path: /spec/provider/workers/1/machine/image/version
      value: 1.0.0
# TODO: Add once implemented in provider local
#    - op: add
#      path: /spec/provider/workers/0/controlPlane/exposure
#      value:
#        extension: {}
