apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-gardener-imagepullsecrets
  annotations:
    policies.kyverno.io/title: Add imagePullSecrets for Gardener images
    policies.kyverno.io/category: Other
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Locally built Gardener images are pushed to a container registry on the seed.
      This registry requires an imagePullSecret, which cannot be added to gardener components by gardener itself.
spec:
  failurePolicy: Ignore
  rules:
  - name: add-gardener-imagepullsecret
    match:
      all:
      - resources:
          kinds:
          - Pod
    context:
      - name: registrydomain
        configMap:
          name: registry-domain
          namespace: registry
    mutate:
      patchStrategicMerge:
        spec:
          containers:
          - <(image): "{{ registrydomain.data.domain }}/*"
          imagePullSecrets:
          - name: gardener-images
