{
 "title": "Cluster Overview",
 "tags": [
  "controlplane",
  "monitoring"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Control Plane", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "kube-apiserver",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "absent(up{job=\"kube-apiserver\"} == 1)"
    }
   ]
  },
  {
   "title": "kube-controller-manager",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "absent(up{job=\"kube-apiserver\"} == 1)"
    }
   ]
  },
  {
   "title": "kube-scheduler",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "absent(up{job=\"kube-scheduler\"} == 1)"
    }
   ]
  },
  {
   "title": "ETCD Main",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "absent(up{job=\"kube-etcd3\", role=\"main\"} == 1)"
    }
   ]
  },
  {
   "title": "ETCD Events",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "absent(up{job=\"kube-etcd3\", role=\"events\"} == 1)"
    }
   ]
  },
  {
   "title": "cluster-autoscaler",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "absent(up{job=\"cluster-autoscaler\"} == 1)"
    }
   ]
  },
  { "title": "Worker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Kubelet(s)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "absent(up{job=\"kube-kubelet\"} == 1)"
    }
   ]
  },
  {
   "title": "CoreDNS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "absent(up{job=\"coredns\"} == 1)"
    }
   ]
  },
  { "title": "Common", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "VPN Connection",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "absent(up{job=\"vpn-connection\"} == 1)"
    }
   ]
  },
  {
   "title": "Crashlooping Pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(increase(kube_pod_container_status_restarts[1h]) > 5)"
    }
   ]
  },
  {
   "title": "Auditlog Failures Ratio",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 12 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate (apiserver_audit_error_total{plugin=\"webhook\"} [5m])) by (app ,role) / ignoring(plugin) sum(rate(apiserver_audit_event_total [5m])) by (app, role)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  { "title": "Monitoring & Logging", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Alerts Firing",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\",alertname!=\"DeadMansSwitch\"})"
    }
   ]
  },
  {
   "title": "Alerts Pending",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"pending\",alertname!=\"DeadMansSwitch\"})"
    }
   ]
  },
  {
   "title": "Prometheus",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "absent(up{job=\"prometheus\"} == 1)"
    }
   ]
  },
  {
   "title": "state-metrics-seed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "absent(up{job=\"kube-state-metrics\",type=\"seed\"} == 1)"
    }
   ]
  },
  {
   "title": "state-metrics-shoot",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "absent(up{job=\"kube-state-metrics\",type=\"shoot\"} == 1)"
    }
   ]
  },
  {
   "title": "node-exporter",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "absent(up{job=\"node-exporter\"} == 1)"
    }
   ]
  },
  {
   "title": "elasticsearch",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "absent(up{job=\"elasticsearch-logging\"} == 1)"
    }
   ]
  },
  {
   "title": "Alert overview",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "count by (alertname, alertstate, severity)(ALERTS)"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "none", "label": "alert count" }
   ],
   "targets": [
    {
     "expr": "sum(ALERTS) by (alertstate, alertname, alertstate)",
     "legendFormat": "{{alertname}} {{alertstate}}"
    }
   ]
  }
 ]
}