{
 "title": "Controller Runtime / Controller Details",
 "tags": [ "controller-runtime" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(controller_runtime_reconcile_total{}, job)"
    }
   },
   {
    "name": "controller",
    "query": {
     "query": "label_values(controller_runtime_reconcile_total{job=\"$job\"}, controller)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(controller_runtime_reconcile_total{job=\"$job\",controller=\"$controller\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Reconciliations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Reconciliation Rate by pod",
   "type": "timeseries",
   "description": "Shows the reconciliation rate for a controller by pod.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{job=\"$job\",controller=~\"$controller\",pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Reconciliation Rate by result",
   "type": "timeseries",
   "description": "Shows the reconciliation rate per result per controller by pod.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{job=\"$job\",controller=~\"$controller\",pod=~\"$pod\"}[$__rate_interval])) by (result)",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Error Rate by pod",
   "type": "timeseries",
   "description": "Shows the total number of reconciliation errors per controller by pod.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_errors_total{job=\"$job\",controller=~\"$controller\",pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Reconciliation time (P50, P90, P99)",
   "type": "timeseries",
   "description": "Shows the length per reconciliation per controller by pod.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(controller_runtime_reconcile_time_seconds_bucket{job=\"$job\",controller=~\"$controller\",pod=~\"$pod\"}[$__rate_interval])) by (controller,le))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(controller_runtime_reconcile_time_seconds_bucket{job=\"$job\",controller=~\"$controller\",pod=~\"$pod\"}[$__rate_interval])) by (controller,le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(controller_runtime_reconcile_time_seconds_bucket{job=\"$job\",controller=~\"$controller\",pod=~\"$pod\"}[$__rate_interval])) by (controller,le))",
     "legendFormat": "P99"
    }
   ]
  },
  { "title": "Workers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Active Controller Workers by pod",
   "type": "timeseries",
   "description": "Shows the active workers per controller by pod.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(controller_runtime_active_workers{job=\"$job\",controller=~\"$controller\",pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "max(controller_runtime_max_concurrent_reconciles{job=\"$job\",controller=~\"$controller\",pod=~\"$pod\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Total workers by pod",
   "type": "table",
   "description": "Shows the maximum number of concurrent reconciliations per controller by pod.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(controller_runtime_max_concurrent_reconciles{job=\"$job\",controller=~\"$controller\",pod=~\"$pod\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Unfinished Work by pod",
   "type": "timeseries",
   "description": "Rate of unfinished work per second not observed in work duration metrics. A constant value of 1 could indicate 1 stuck worker routine.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(workqueue_unfinished_work_seconds{job=\"$job\",name=~\"$controller\",pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Longest Running Worker by pod",
   "type": "timeseries",
   "description": "Shows for how many seconds the longest running worker of a pod for a workqueue has been running.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(workqueue_longest_running_processor_seconds{job=\"$job\",name=~\"$controller\",pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Work Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Enqueues by pod",
   "type": "timeseries",
   "description": "Shows the rate of adds to the work queue. by pod",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(workqueue_adds_total{job=\"$job\",name=~\"$controller\",pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Retries by pod",
   "type": "timeseries",
   "description": "Shows the total number of retries handled by the workqueue by pod.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(workqueue_retries_total{job=\"$job\",name=~\"$controller\",pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Work Rate",
   "type": "timeseries",
   "description": "Shows how many items of the workqueue are processed.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(workqueue_work_duration_seconds_count{job=\"$job\",name=~\"$controller\"}[$__rate_interval])) by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Work Duration (P50, P90, P99)",
   "type": "timeseries",
   "description": "Seconds processing an item from workqueue takes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(workqueue_work_duration_seconds_bucket{job=\"$job\",name=~\"$controller\",pod=~\"$pod\"}[$__rate_interval])) by (name,le))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(workqueue_work_duration_seconds_bucket{job=\"$job\",name=~\"$controller\",pod=~\"$pod\"}[$__rate_interval])) by (name,le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(workqueue_work_duration_seconds_bucket{job=\"$job\",name=~\"$controller\",pod=~\"$pod\"}[$__rate_interval])) by (name,le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Queue Duration (P50, P90, P99)",
   "type": "timeseries",
   "description": "Seconds an item stays in workqueue before being requested.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(workqueue_queue_duration_seconds_bucket{job=\"$job\",name=~\"$controller\",pod=~\"$pod\"}[$__rate_interval])) by (name,le))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(workqueue_queue_duration_seconds_bucket{job=\"$job\",name=~\"$controller\",pod=~\"$pod\"}[$__rate_interval])) by (name,le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(workqueue_queue_duration_seconds_bucket{job=\"$job\",name=~\"$controller\",pod=~\"$pod\"}[$__rate_interval])) by (name,le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Queue Length by pod",
   "type": "graph",
   "description": "Shows the current length of the workqueue by pod.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(workqueue_depth{job=\"$job\",name=~\"$controller\",pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}