{
 "title": "CoreDNS",
 "tags": [
  "network",
  "shoot"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "CoreDNS Pod",
    "query": "label_values(coredns_cache_size, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"$pod\"}[1m]))",
     "legendFormat": "Current"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{pod=~\"$pod\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{pod=~\"$pod\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod=~\"$pod\"})",
     "legendFormat": "Current"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{pod=~\"$pod\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{pod=~\"$pod\"})",
     "legendFormat": "Limits:"
    }
   ]
  },
  {
   "title": "DNS Requests (Packets per Second)",
   "type": "graph",
   "description": "Average rate of DNS requests (in packets per second) split by DNS record types, used protocol and DNS zone.\n\nNote: The `dot` zone is the local zone managed by the CoreDNS instance.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_request_type_count_total{pod=~\"$pod\"}[5m])) by (type)",
     "legendFormat": "By Record: {{type}}"
    },
    {
     "expr": "sum(rate(coredns_dns_request_count_total{pod=~\"$pod\"}[5m])) by (proto)",
     "legendFormat": "By Protocol: {{proto}}"
    },
    {
     "expr": "sum(rate(coredns_dns_request_count_total{pod=~\"$pod\"}[5m])) by (zone)",
     "legendFormat": "By Zone: {{zone}}"
    }
   ]
  },
  {
   "title": "DNS Lookup Responses",
   "type": "graph",
   "description": "The average per second rate of lookup requests split by their status codes (rcode).",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(coredns_dns_response_rcode_count_total{pod=\"$pod\"}[5m])",
     "legendFormat": "{{rcode}}"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cache Hits and Misses",
     "type": "graph",
     "description": "The `cache hits` rate describes how many DNS requests were answered due to a cached entry.\n\nThe `cache misses` rate describes how much DNS requests need to be looked up, because the requests entry does not exist in the local cache.\n\nThe rates are per second averages and displayed in packets per second.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "rate(coredns_cache_hits_total{pod=~\"$pod\"}[5m])",
       "legendFormat": "cache hits"
      },
      {
       "expr": "rate(coredns_cache_misses_total{pod=~\"$pod\"}[5m])",
       "legendFormat": "cache misses"
      }
     ]
    },
    {
     "title": "Cache Size",
     "type": "graph",
     "description": "Count of cached entries in the cache of the DNS.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(coredns_cache_size{pod=\"$pod\"})",
       "legendFormat": "cache size"
      }
     ]
    }
   ]
  },
  {
   "title": "Upstream DNS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Upstream DNS requests",
     "type": "graph",
     "description": "Average request (packets per second) rate made to upstream DNS.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(coredns_forward_request_count_total{pod=\"$pod\"}[1h])) by (to)",
       "legendFormat": "{{to}}"
      }
     ]
    },
    {
     "title": "Upstream DNS Responses",
     "type": "graph",
     "description": "Average per second rate of responses from upstream DNS split by status code (rcode).",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(coredns_forward_response_rcode_count_total{pod=\"$pod\"}[1h])",
       "legendFormat": "{{rcode}} ({{to}})"
      }
     ]
    }
   ]
  }
 ]
}