{
 "title": "Controller Runtime / Webhooks",
 "tags": [ "controller-runtime" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(controller_runtime_webhook_requests_total{}, job)"
    }
   },
   {
    "name": "webhook",
    "query": {
     "query": "label_values(controller_runtime_webhook_requests_total{job=\"$job\"},webhook)"
    }
   },
   { "name": "percentile", "query": "50,90,99" }
  ]
 },
 "panels": [
  { "title": "Headlines (over time range)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total requests",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_webhook_requests_total{job=\"$job\",webhook=~\"$webhook\"}[$__range])) by (webhook)",
     "legendFormat": "{{webhook}}"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_webhook_latency_seconds_count{job=\"$job\",webhook=~\"$webhook\"}[$__range])) by(webhook)",
     "legendFormat": "{{webhook}}"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Total Requests by webhook",
   "type": "timeseries",
   "description": "Shows the total number of admission requests being served.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_webhook_requests_total{job=\"$job\",webhook=~\"$webhook\"}[$__rate_interval])) by (webhook)",
     "legendFormat": "{{webhook}}"
    }
   ]
  },
  {
   "title": "Total Requests by code",
   "type": "timeseries",
   "description": "Shows the total number of admission requests being served.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_webhook_requests_total{job=\"$job\",webhook=~\"$webhook\"}[$__rate_interval])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Inflight Requests",
   "type": "timeseries",
   "description": "Shows the current number of admission requests being served.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(controller_runtime_webhook_requests_in_flight{job=\"$job\",webhook=~\"$webhook\"}) by (webhook)",
     "legendFormat": "{{webhook}}"
    }
   ]
  },
  {
   "title": "Latency (${percentile}th Percentile)",
   "type": "timeseries",
   "description": "Shows the latency of processing admission requests.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile/100,sum(rate(controller_runtime_webhook_latency_seconds_bucket{job=\"$job\",webhook=~\"$webhook\"}[$__rate_interval])) by(le,webhook))",
     "legendFormat": "{{webhook}}"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "description": "Shows the latency of processing admission requests.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_webhook_latency_seconds_count{job=\"$job\",webhook=~\"$webhook\"}[$__rate_interval])) by(webhook)",
     "legendFormat": "{{webhook}}"
    }
   ]
  }
 ]
}