{
 "title": "ETCD",
 "tags": [
  "controlplane",
  "seed"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": "main, events" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Up",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(etcd_server_has_leader{role=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "RPC Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 5, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{role=~\"$cluster\",grpc_type=\"unary\"}[$__rate_interval]))",
     "legendFormat": "RPC Rate"
    },
    {
     "expr": "sum(rate(grpc_server_handled_total{role=~\"$cluster\",grpc_type=\"unary\",grpc_code!=\"OK\"}[$__rate_interval]))",
     "legendFormat": "RPC Failed Rate"
    }
   ]
  },
  {
   "title": "Active Streams",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(grpc_server_started_total{role=~\"$cluster\",grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\"}) - sum(grpc_server_handled_total{role=~\"$cluster\",grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\"})",
     "legendFormat": "Watch Streams"
    },
    {
     "expr": "sum(grpc_server_started_total{role=~\"$cluster\",grpc_service=\"etcdserverpb.Lease\",grpc_type=\"bidi_stream\"}) - sum(grpc_server_handled_total{role=~\"$cluster\",grpc_service=\"etcdserverpb.Lease\",grpc_type=\"bidi_stream\"})",
     "legendFormat": "Lease Streams"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"kube-etcd3-$cluster\"}",
     "legendFormat": "{{pod}} Resident Memory"
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "etcd_mvcc_db_total_size_in_bytes{role=~\"$cluster\"}",
     "legendFormat": "{{pod}} DB Size"
    }
   ]
  },
  {
   "title": "Disk Sync Duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket{role=~\"$cluster\"}[$__rate_interval])) by (instance, le))",
     "legendFormat": "{{pod}} WAL fsync"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket{role=~\"$cluster\"}[$__rate_interval])) by (instance, le))",
     "legendFormat": "{{pod}} DB fsync"
    }
   ]
  },
  {
   "title": "Client Traffic In",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_received_bytes_total{role=~\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{pod}} Client Traffic In"
    }
   ]
  },
  {
   "title": "Client Traffic Out",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_sent_bytes_total{role=~\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{pod}} Client Traffic Out"
    }
   ]
  },
  { "title": "Container Disk I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Container Disk Read Operations (2m rate)",
   "type": "graph",
   "description": "One minute rates for all filesystem read operations executed within the container(s).\n\nThe data has the following designation scheme: <pod-name> / <container-name>",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{namespace=\"kube-system\", pod=~\"etcd-(${cluster:pipe}).*\"}[$__rate_interval])) by(pod, container)",
     "legendFormat": "{{pod}} / {{container}}"
    }
   ]
  },
  {
   "title": "Container Disk Write Operations (2m rate)",
   "type": "graph",
   "description": "One minute rates for all filesystem write operations executed within the container(s).\n\nThe data has the following designation scheme: <pod-name> / <container-name>",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{namespace=\"kube-system\", pod=~\"etcd-(${cluster:pipe}).*\"}[$__rate_interval])) by(pod, container)",
     "legendFormat": "{{pod}} / {{container}}"
    }
   ]
  }
 ]
}