{
 "title": "ETCD Compaction Job",
 "tags": [
  "seed",
  "control-plane"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Successful Jobs",
   "type": "stat",
   "description": "Number of succeeded compaction jobs initiated by compaction controller in the selected time range.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(floor(increase(etcddruid_compaction_jobs_total{succeeded=\"true\"}[${__range}])))"
    }
   ]
  },
  {
   "title": "Failed Jobs",
   "type": "stat",
   "description": "Number of failed compaction jobs initiated by compaction controller in the selected time range",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(floor(increase(etcddruid_compaction_jobs_total{succeeded=\"false\"}[${__range}])))"
    }
   ]
  },
  {
   "title": "Current Running Jobs",
   "type": "graph",
   "description": "Number of currently running compaction jobs.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(etcddruid_compaction_jobs_current{}) by (etcd_namespace)",
     "legendFormat": "Compaction Job ({{etcd_namespace}})"
    }
   ]
  },
  {
   "title": "Accumulated Delta Events",
   "type": "graph",
   "description": "Total number of etcd events to be compacted by a compaction job.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(etcddruid_compaction_num_delta_events{}) by (etcd_namespace)",
     "legendFormat": "Accumulated Delta Events ({{etcd_namespace}})"
    }
   ]
  },
  {
   "title": "Job Duration",
   "type": "heatmap",
   "description": "Total time taken in seconds to finish a running compaction job",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(etcddruid_compaction_job_duration_seconds_bucket{succeeded=\"true\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"etcd-main-compactor.+\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "cpu",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"etcd-main-compactor.+\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}