// Code generated by client-gen. DO NOT EDIT.

package v1beta1

type BackupInfrastructureExpansion interface{}

type CloudProfileExpansion interface{}

type ProjectExpansion interface{}

type QuotaExpansion interface{}

type SecretBindingExpansion interface{}

type SeedExpansion interface{}

type ShootExpansion interface{}
