apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- patch: |-
    - op: replace
      path: /networking/ipFamily
      value: ipv6
    - op: replace
      path: /networking/podSubnet
      value: "fd00:10:1::/48"
    - op: replace
      path: /networking/serviceSubnet
      value: "fd00:10:2::/112"
  target:
    group: kind.x-k8s.io
    kind: Cluster
    name: local
