// Code generated by client-gen. DO NOT EDIT.

package internalversion

type CloudProfileExpansion interface{}

type QuotaExpansion interface{}

type SecretBindingExpansion interface{}

type SeedExpansion interface{}

type ShootExpansion interface{}
