{
 "title": "Controller Runtime / Webhook Details",
 "tags": [ "controller-runtime" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(controller_runtime_webhook_requests_total{}, job)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(controller_runtime_webhook_requests_total{job=\"$job\"},pod)"
    }
   },
   {
    "name": "webhook",
    "query": {
     "query": "label_values(controller_runtime_webhook_requests_total{job=\"$job\",pod=~\"$pod\"},webhook)"
    }
   },
   {
    "name": "code",
    "query": {
     "query": "label_values(controller_runtime_webhook_requests_total{job=\"$job\",pod=~\"$pod\",webhook=\"$webhook\"},code)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Rate by pod",
   "type": "timeseries",
   "description": "Shows the total number of admission requests being served.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_webhook_requests_total{job=\"$job\",webhook=\"$webhook\",code=~\"$code\",pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Request Rate by code",
   "type": "timeseries",
   "description": "Shows the total number of admission requests being served.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_webhook_requests_total{job=\"$job\",webhook=\"$webhook\",code=~\"$code\",pod=~\"$pod\"}[$__rate_interval])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Inflight Requests by pod",
   "type": "timeseries",
   "description": "Shows the current number of admission requests being served.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(controller_runtime_webhook_requests_in_flight{job=\"$job\",pod=~\"$pod\",webhook=\"$webhook\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Latency (P50, P90, P99)",
   "type": "timeseries",
   "description": "Shows the latency of processing admission requests.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5,sum(rate(controller_runtime_webhook_latency_seconds_bucket{job=\"$job\",pod=~\"$pod\",webhook=\"$webhook\"}[$__rate_interval])) by(le,webhook))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.9,sum(rate(controller_runtime_webhook_latency_seconds_bucket{job=\"$job\",pod=~\"$pod\",webhook=\"$webhook\"}[$__rate_interval])) by(le,webhook))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99,sum(rate(controller_runtime_webhook_latency_seconds_bucket{job=\"$job\",pod=~\"$pod\",webhook=\"$webhook\"}[$__rate_interval])) by(le,webhook))",
     "legendFormat": "P99"
    }
   ]
  }
 ]
}