#!/usr/bin/env bash
#
# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

LABEL="${1:-local-garden}"

docker rm -f $(docker ps -f "label=$LABEL" -aq) 2&> /dev/null || true
docker network rm $(docker network ls -qf "label=$LABEL") 2&> /dev/null || true
