#!/usr/bin/env bash

IP_ROUTE=""
IP_ADDRESS=""
ADD_HOSTS=""
if ! ( [[ "$(uname -s)" == *"Darwin"* ]] || [[ "$(uname -s)" == "Linux" && "$(uname -r)" =~ "microsoft-standard" ]] ); then
  IP_ROUTE=$(ip route get 1)
  IP_ADDRESS=$(echo ${IP_ROUTE#*src} | awk '{print $1}')
  ADD_HOSTS="--add-host gardener.localhost:$IP_ADDRESS"
fi

LABEL=${1:-local-garden}
ACTIVATE_SEEDAUTHORIZER=${2:-false}

IMAGE=k8s.gcr.io/kube-apiserver:v1.20.2
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
MOUNTS="-v $SCRIPTPATH/certificates/certs:/certs -v $SCRIPTPATH/certificates/keys:/keys -v $SCRIPTPATH/configs:/configs"
ETCD_PORT=12379
LISTEN_PORT="2443"

ADMISSION_CONTROLLER_EXTERNAL_NAME=gardener.localhost
if [[ "$(uname -s)" == *"Darwin"* ]] || [[ "$(uname -s)" == "Linux" && "$(uname -r)" =~ "microsoft-standard" ]] ; then
  ADMISSION_CONTROLLER_EXTERNAL_NAME=host.docker.internal
fi

cat<< EOF > "$SCRIPTPATH/configs/authwebhook.yaml"
apiVersion: v1
kind: Config
current-context: seedauthorizer
clusters:
- name: gardener-admission-controller
  cluster:
    insecure-skip-tls-verify: true
    server: https://$ADMISSION_CONTROLLER_EXTERNAL_NAME:2721/webhooks/auth/seed
users:
- name: kube-apiserver
  user: {}
contexts:
- name: seedauthorizer
  context:
    cluster: gardener-admission-controller
    user: kube-apiserver
EOF

AUTHORIZATION_FLAGS="--authorization-mode=RBAC"
if $ACTIVATE_SEEDAUTHORIZER; then
  AUTHORIZATION_FLAGS="--authorization-mode=RBAC,Webhook --authorization-webhook-config-file=/configs/authwebhook.yaml --authorization-webhook-cache-authorized-ttl=0 --authorization-webhook-cache-unauthorized-ttl=0"
fi

echo "Starting gardener-dev kube-apiserver!"
docker run -d --name kube-apiserver -l $LABEL $ADD_HOSTS --network gardener-dev --rm -p $LISTEN_PORT:$LISTEN_PORT $MOUNTS $IMAGE /usr/local/bin/kube-apiserver \
  --etcd-servers="https://etcd:$ETCD_PORT" \
  --storage-media-type='application/json' \
  $AUTHORIZATION_FLAGS \
  --etcd-cafile="/certs/ca.crt" \
  --etcd-keyfile="/keys/kube-apiserver-etcd-client.key" \
  --etcd-certfile="/certs/kube-apiserver-etcd-client.crt" \
  --tls-cert-file="/certs/kube-apiserver.crt" \
  --tls-private-key-file="/keys/kube-apiserver.key" \
  --requestheader-client-ca-file="/certs/ca.crt" \
  --requestheader-extra-headers-prefix=X-Remote-Extra- \
  --requestheader-group-headers=X-Remote-Group \
  --requestheader-username-headers=X-Remote-User \
  --client-ca-file="/certs/ca.crt" \
  --proxy-client-key-file="/keys/front-proxy-client.key" \
  --proxy-client-cert-file="/certs/front-proxy-client.crt" \
  --service-account-key-file="/keys/sa.key" \
  --service-account-signing-key-file="/keys/sa.key" \
  --service-account-issuer="local-garden" \
  --service-cluster-ip-range="10.0.0.0/24" \
  --secure-port=$LISTEN_PORT
