#!/usr/bin/env bash
#
# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

LABEL="${1:-local-garden}"

IMAGE=quay.io/coreos/etcd:v3.3.10
PORT=22380
ETCDPORT=22379
CLUSTERNAME=gardener-etcd

# Change this value to the desired storage location
ETCD_DATA_DIR="$PWD/dev/gardener-etcd/gardener"

PORTS="-p $PORT:$PORT -p $ETCDPORT:$ETCDPORT"
MOUNTS="-v $ETCD_DATA_DIR:/etcd-data"

echo "Starting gardener-dev gardener-etcd cluster!"
docker run -d --name g-etcd -l $LABEL --network gardener-dev --rm $PORTS $MOUNTS $IMAGE etcd --name $CLUSTERNAME \
 --listen-client-urls "http://0.0.0.0:${ETCDPORT}" \
 --advertise-client-urls "http://0.0.0.0:${ETCDPORT}" \
 --listen-peer-urls "http://0.0.0.0:${PORT}" \
 --data-dir="/etcd-data"
