{
 "title": "API Server Proxy",
 "tags": [
  "istio",
  "shoot"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "Proxy",
    "query": "label_values(up{job=\"apiserver-proxy\"},pod)"
   }
  ]
 },
 "panels": [
  { "title": "Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "This dashboard shows data for the API Server Proxy running in the Shoot clusters as part of the [SNI for Kube API Server](https://github.com/gardener/gardener/blob/master/docs/proposals/08-shoot-apiserver-via-sni.md) proposal. It also means that the Gardener administrator for this cluster has enabled the `APIServerSNI` feature gate and installation of an `apiserver-proxy` component in the `kube-system` namespace of the cluster. Any workload attempting to connect to the Shoot API Server via the `kubernetes` Service in the `default` namespace (or the automatic build-in discovery) is redirected to this `apiserver-proxy`.\n\nTerminology:\n\n- `Downstream` is a client or host that connects to the apiserver-proxy, sends requests, and receives response. This is normally a Kubernetes controller running in a Pod and uses the build-in apiserver discovery.\n- `Upstream` is a single Kube-API Server endpoint for this Shoot cluster that receives connections and requests from apiserver-proxy and returns responses.\n- `Cluster` is the collection of all Kube-API Server upstream endpoints that `apiserver-proxy` connects to."
   }
  },
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Cluster Updates",
   "type": "graph",
   "description": "Cluster update happens when the `apiserver-proxy` tries to resolve its upstream cluster (e.g DNS resolution)",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(clamp_min(envoy_cluster_update_attempt{pod=~\"$pod\"} - envoy_cluster_update_attempt{pod=~\"$pod\"} offset $__interval, 0))",
     "legendFormat": "Attempts"
    },
    {
     "expr": "sum(clamp_min(envoy_cluster_update_failure{pod=~\"$pod\"} - envoy_cluster_update_failure{pod=~\"$pod\"} offset $__interval, 0))",
     "legendFormat": "Failures"
    }
   ]
  },
  {
   "title": "Bind Errors",
   "type": "graph",
   "description": "Errors when attempting to bind to a network interface. This error should not happen.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(clamp_min(envoy_cluster_bind_errors{pod=~\"$pod\"} - envoy_cluster_bind_errors{pod=~\"$pod\"} offset $__interval, 0))",
     "legendFormat": "Errors"
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Downstream",
   "type": "graph",
   "description": "The amount of data send from cluster Pods to the `apiserver-proxy` ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_tcp_downstream_cx_rx_bytes_total{pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(rate(envoy_tcp_downstream_cx_tx_bytes_total{pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "Transmitted"
    }
   ]
  },
  {
   "title": "Upstream ",
   "type": "graph",
   "description": "The amount of data send from `apiserver-proxy`  to the upstream Shoot Kube API Server",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_rx_bytes_total{pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_tx_bytes_total{pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "Transmitted"
    }
   ]
  },
  {
   "title": "PROXY Protocol Overhead",
   "type": "graph",
   "description": "`apiserver-proxy`  uses [PROXY Protocol](http://www.haproxy.org/download/2.0/doc/proxy-protocol.txt) to talk to upstream hosts. This is the overhead.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_tx_bytes_total{pod=~\"$pod\"}[$__rate_interval])) - sum(rate(envoy_tcp_downstream_cx_rx_bytes_total{pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "bytes"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Downstream Connections",
   "type": "graph",
   "description": "How many downstream connections are opened from Pods to the `apiserver-proxy` .",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(clamp_min(envoy_listener_downstream_cx_total{pod=~\"$pod\"} - envoy_listener_downstream_cx_total{pod=~\"$pod\"} offset $__interval, 0))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(clamp_min(envoy_listener_downstream_cx_overflow{pod=~\"$pod\"} - envoy_listener_downstream_cx_overflow{pod=~\"$pod\"} offset $__interval, 0))",
     "legendFormat": "Overflow"
    },
    {
     "expr": "sum(clamp_min(envoy_tcp_downstream_cx_no_route{pod=~\"$pod\"} - envoy_tcp_downstream_cx_no_route{pod=~\"$pod\"} offset $__interval, 0))",
     "legendFormat": "No route"
    }
   ]
  },
  {
   "title": "Upstream Cluster Health Errors",
   "type": "graph",
   "description": "The amount of errors the `apiserver-proxy`  experiences when doing healtchecks to the upstream Shoot Kube API Server",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(clamp_min(envoy_cluster_lb_healthy_panic{pod=~\"$pod\"} - envoy_cluster_lb_healthy_panic{pod=~\"$pod\"} offset $__interval, 0))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Upstream Connection Failures",
   "type": "graph",
   "description": "The amount of of failures when the `apiserver-proxy`  tries to connect to the upstream Shoot Kube API Server",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(clamp_min(envoy_cluster_upstream_cx_none_healthy{pod=~\"$pod\"} - envoy_cluster_upstream_cx_none_healthy{pod=~\"$pod\"} offset $__interval, 0))",
     "legendFormat": "Failures"
    }
   ]
  },
  {
   "title": "Downstream Connection Length",
   "type": "graph",
   "description": "The total time a downstream connection from Pods is opened to the `apiserver-proxy` .",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(envoy_listener_downstream_cx_length_ms_bucket{pod=~\"$pod\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50 "
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(envoy_listener_downstream_cx_length_ms_bucket{pod=~\"$pod\"}[$__rate_interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_listener_downstream_cx_length_ms_bucket{pod=~\"$pod\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(envoy_listener_downstream_cx_length_ms_bucket{pod=~\"$pod\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99.9"
    }
   ]
  },
  {
   "title": "Upstream Connection Opening Time",
   "type": "graph",
   "description": "The ammount of time an upstream connection from the `apiserver-proxy`  to the Shoot Kube API Seaarver takes to open",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 37 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(envoy_cluster_upstream_cx_connect_ms_bucket{pod=~\"$pod\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50 "
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(envoy_cluster_upstream_cx_connect_ms_bucket{pod=~\"$pod\"}[$__rate_interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_cluster_upstream_cx_connect_ms_bucket{pod=~\"$pod\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(envoy_cluster_upstream_cx_connect_ms_bucket{pod=~\"$pod\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99.9"
    }
   ]
  },
  {
   "title": "Upstream Connection Length",
   "type": "graph",
   "description": "The time a connection is opened from the `apiserver-proxy` to the upstream Shoot Kube API Server",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 37 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(envoy_cluster_upstream_cx_length_ms_bucket{pod=~\"$pod\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50 "
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(envoy_cluster_upstream_cx_length_ms_bucket{pod=~\"$pod\"}[$__rate_interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_cluster_upstream_cx_length_ms_bucket{pod=~\"$pod\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(envoy_cluster_upstream_cx_length_ms_bucket{pod=~\"$pod\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99.9"
    }
   ]
  }
 ]
}