{
 "title": "Alerts",
 "tags": [
  "monitoring",
  "seed"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Severity", "query": "label_values(ALERTS,severity)" },
   {
    "name": "AlertState",
    "label": "Alert State",
    "query": "label_values(ALERTS,alertstate)"
   },
   {
    "name": "Alertname",
    "query": "label_values(ALERTS, alertname)"
   },
   {
    "name": "Infra",
    "query": "label_values(ALERTS, shoot_infra)"
   }
  ]
 },
 "panels": [
  { "title": "Total Alerts Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Alerts by Infrastructure  ($Severity|$AlertState|$Alertname|$Infra)",
   "type": "bargauge",
   "description": "Shows the number of alerts by infrastructure.",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count(ALERTS{severity=~\"$Severity\", alertstate=~\"$AlertState\", alertname=~\"$Alertname\", shoot_infra=~\"$Infra\"}) by (shoot_infra)",
     "legendFormat": "{{shoot_infra}}"
    }
   ]
  },
  {
   "title": "Firing Alerts",
   "type": "singlestat",
   "description": "Shows how many alerts are currently firing for shoots using this seed.",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\"})"
    }
   ]
  },
  {
   "title": "Pending Alerts",
   "type": "singlestat",
   "description": "Shows how many alerts are currently pending for shoots using this seed.",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"pending\"})"
    }
   ]
  },
  {
   "title": "% of Clusters with Alerts",
   "type": "gauge",
   "description": "Shows the percentage of clusters that have at least 1 firing or pending alert.",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "targets": [
    {
     "expr": "count(count(ALERTS) by (shoot_name)) / count(count(shoot:availability) by (shoot_name)) * 100"
    }
   ]
  },
  {
   "title": "Clusters with Firing Alerts",
   "type": "singlestat",
   "description": "Shows how many clusters have at least 1 firing alert.",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count(ALERTS{alertstate=\"firing\"}) by (shoot_name))"
    }
   ]
  },
  {
   "title": "Clusters with Pending Alerts",
   "type": "singlestat",
   "description": "Shows how many clusters currently have at least 1 pending alert.",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count(ALERTS{alertstate=\"pending\"}) by (shoot_name))"
    }
   ]
  },
  {
   "title": "Clusters Total",
   "type": "singlestat",
   "description": "Shows the total number of shoots with a control plane on this seed.",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count(shoot:availability) by (shoot_name))"
    }
   ]
  },
  {
   "title": "Active Alerts ($Severity|$AlertState|$Alertname|$Infra)",
   "type": "graph",
   "description": "Shows alerts that are/were active with the selected severity and alert state from the selected clusters. Includes the alertnames of the alerts.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(ALERTS{alertname=~\"$Alertname\", severity=~\"$Severity\", alertstate=~\"$AlertState\", shoot_infra=~\"$Infra\"}) by (alertname)",
     "legendFormat": "{{ alertname }}"
    }
   ]
  },
  { "title": "Alerts by Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Cluster Alert Count ($Severity|$AlertState|$Alertname|$Infra)",
   "type": "graph",
   "description": "Shows the number of alerts in each cluster.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Alerts" }
   ],
   "targets": [
    {
     "expr": "count(ALERTS{alertname=~\"$Alertname\", severity=~\"$Severity\", alertstate=~\"$AlertState\", shoot_infra=~\"$Infra\"}) by (project,name)",
     "legendFormat": "{{ project }}/{{ name }}"
    }
   ]
  },
  {
   "title": "Cluster Alerts ($Severity|$AlertState|$Alertname|$Infra)",
   "type": "table",
   "description": "Shows all alerts that are currently active from the selected clusters, severity, and alert state.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "count(ALERTS{severity=~\"$Severity\",alertname=~\"$Alertname\", alertstate=~\"$AlertState\",shoot_infra=~\"$Infra\"}) by (alertname, project,shoot_name, severity, alertstate, shoot_infra)"
    }
   ]
  }
 ]
}