{
 "title": "Gardener Admission Controller",
 "tags": [
  "controlplane",
  "garden"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "query": {
     "query": "label_values(gardener_admission_controller_rejected_resources_total, namespace)"
    }
   },
   {
    "name": "Kind",
    "query": {
     "query": "label_values(gardener_admission_controller_rejected_resources_total, kind)"
    }
   },
   {
    "name": "Operation",
    "query": {
     "query": "label_values(gardener_admission_controller_rejected_resources_total, operation)"
    }
   },
   {
    "name": "Reason",
    "query": {
     "query": "label_values(gardener_admission_controller_rejected_resources_total, reason)"
    }
   },
   {
    "name": "kind",
    "label": "Kind",
    "query": {
     "query": "label_values(gardener_admission_controller_seed_authorizer_graph_update_duration_seconds_bucket, kind)"
    }
   },
   {
    "name": "graph_operation",
    "label": "Graph Operation",
    "query": {
     "query": "label_values(gardener_admission_controller_seed_authorizer_graph_update_duration_seconds_bucket, operation)"
    }
   }
  ]
 },
 "panels": [
  { "title": "SeedAuthorizer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Graph Update Duration Per Kind And Graph Operation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.9,sum(rate(gardener_admission_controller_seed_authorizer_graph_update_duration_seconds_bucket{operation=~\"$graph_operation\",kind=~\"$kind\"}[$__rate_interval])) by(le,kind,operation))",
     "legendFormat": "{{operation}} {{kind}}"
    }
   ]
  },
  {
   "title": "Graph Path Check Duration To Seed Per FromKind",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.9,sum(rate(gardener_admission_controller_seed_authorizer_graph_path_check_duration_seconds_bucket{fromKind=~\"$kind\"}[$__rate_interval])) by(le,fromKind))",
     "legendFormat": "{{fromKind}}"
    }
   ]
  },
  { "title": "Admission Webhooks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Rejected Resources",
   "type": "graph",
   "description": "Number of resources rejected by the Gardener Admission Controller.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, reason, kind, operation) (\n  clamp_min(\n    sum without (instance) (\n      gardener_admission_controller_rejected_resources_total{namespace=~\"$Namespace\", kind=~\"$Kind\", operation=~\"$Operation\", reason=~\"$Reason\"}\n    )\n    - \n    (sum without (instance) (\n      gardener_admission_controller_rejected_resources_total{namespace=~\"$Namespace\", kind=~\"$Kind\", operation=~\"$Operation\", reason=~\"$Reason\"} offset $__interval\n    ) \n    or\n    sum without (instance) (\n      gardener_admission_controller_rejected_resources_total{namespace=~\"$Namespace\", kind=~\"$Kind\", operation=~\"$Operation\", reason=~\"$Reason\"}\n    ) * 0)\n    , 0\n  )\n)",
     "legendFormat": "{{ namespace }}/{{ kind }}/{{ operation }}/{{ reason }}"
    }
   ]
  }
 ]
}