{
 "title": "Resource usage by container",
 "time": { "from": "now-1d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "seed",
    "query": {
     "query": "label_values(seed:kube_pod_container_resource_requests_cpu_cores:sum_by_container, seed)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(seed:kube_pod_container_resource_requests_cpu_cores:sum_by_container, container)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(seed:container_cpu_usage_seconds_total:sum_by_container{container=\"$container\", seed=~\"$seed\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(seed:kube_pod_container_resource_requests_cpu_cores:sum_by_container{container=\"$container\", seed=~\"$seed\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(seed:kube_pod_container_resource_limits_cpu_cores:sum_by_container{container=\"$container\", seed=~\"$seed\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "description": "How many percent of the CPU requests are used.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * sum(seed:container_cpu_usage_seconds_total:sum_by_container{container=\"$container\", seed=~\"$seed\"}) / sum(seed:kube_pod_container_resource_requests_cpu_cores:sum_by_container{container=\"$container\", seed=~\"$seed\"})",
     "legendFormat": "Utilization"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(seed:container_memory_working_set_bytes:sum_by_container{container=\"$container\", seed=~\"$seed\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(seed:kube_pod_container_resource_requests_memory_bytes:sum_by_container{container=\"$container\", seed=~\"$seed\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(seed:kube_pod_container_resource_limits_memory_bytes:sum_by_container{container=\"$container\", seed=~\"$seed\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "description": "How many percent of the memory requests are used.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * sum(seed:container_memory_working_set_bytes:sum_by_container{container=\"$container\", seed=~\"$seed\"}) / sum(seed:kube_pod_container_resource_requests_memory_bytes:sum_by_container{container=\"$container\", seed=~\"$seed\"})",
     "legendFormat": "Utilization"
    }
   ]
  }
 ]
}