{
 "title": "Shoot Details",
 "description": "Dashboard with details to a Shoot clusters state.",
 "tags": [
  "Shoot",
  "Gardener"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "Project",
    "query": "label_values(garden_shoot_info, project)"
   },
   {
    "name": "shoot",
    "label": "Shoot",
    "query": "label_values(garden_shoot_info{project=\"$project\"}, name)"
   }
  ]
 },
 "panels": [
  { "title": "Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Infrastructure",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "garden_shoot_info{project=\"$project\", name=\"$shoot\"}",
     "legendFormat": "{{iaas}}"
    }
   ]
  },
  {
   "title": "Region",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "garden_shoot_info{project=\"$project\", name=\"$shoot\"}",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Seed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "garden_shoot_info{project=\"$project\", name=\"$shoot\"}",
     "legendFormat": "{{seed}}"
    }
   ]
  },
  {
   "title": "K8S Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "garden_shoot_info{project=\"$project\", name=\"$shoot\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Node Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "shoot:kube_node_info:count{project=~\"$project\", shoot_name=~\"$shoot\"}"
    }
   ]
  },
  {
   "title": "Shoot Availability",
   "type": "graph",
   "description": "Shows if the API Server is reachable from the shoot cluster.",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "shoot:availability{project=~\"$project\", shoot_name=\"$shoot\"}",
     "legendFormat": "{{ project }}/{{ shoot_name }}"
    }
   ]
  },
  {
   "title": "K8s Versions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(garden_shoot_info{project=\"$project\", name=\"$shoot\"}) by (name,project,version) + 1",
     "legendFormat": "{{project}}/{{name}}: {{version}}"
    }
   ]
  },
  { "title": "Seed↔Shoot Connectivity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Shoot APIServer Availablity",
   "type": "graph",
   "description": "Shows APIServer availability for shoots hosted on seed $shoot across regions.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "shoot:availability * on(name, project) group_left(region, iaas, seed_region, seed_iaas) (garden_shoot_info{seed=\"$shoot\", is_seed=\"false\"} * 0 + 1)",
     "legendFormat": "{{name}}: {{kind}} ({{iaas}}, {{region}})/({{seed_iaas}}, {{seed_region}})"
    }
   ]
  },
  {
   "title": "State",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Conditions (0=false, 1=ok, -1=unknown)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short", "label": "Condition State" }
     ],
     "targets": [
      {
       "expr": "garden_shoot_condition{project=\"$project\", name=\"$shoot\"}",
       "legendFormat": "{{condition}}"
      }
     ]
    },
    {
     "title": "Gardener Operation Status",
     "type": "graph",
     "gridPos": { "h": 7, "w": 11, "x": 10, "y": 9 },
     "yaxes": [
      { "format": "short", "label": "Shoot State" }
     ],
     "targets": [
      {
       "expr": "garden_shoot_operation_states{project=\"$project\", name=\"$shoot\"}",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 7, "w": 3, "x": 21, "y": 9 },
     "content": "##### State legend\n0 = operation not active  \n1 = succeeded  \n2 = processing  \n3 = pending  \n4 = error  \n5 = failed  \n"
    },
    {
     "title": "Kube-apiservers",
     "type": "graph",
     "description": "The number of kube-apiservers running in the control plane of cluster $project / $shoot.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(shoot:kube_apiserver:sum_by_pod{project=~\"$project\", shoot_name=~\"$shoot\"})",
       "legendFormat": "Kube APIServers"
      }
     ]
    },
    {
     "title": "Cluster Nodes",
     "type": "graph",
     "description": "Shows the number of active nodes in the shoot cluster $project / $shoot.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "shoot:kube_node_info:count{project=~\"$project\", shoot_name=~\"$shoot\"}",
       "legendFormat": "nodes"
      }
     ]
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Alerts",
   "type": "graph",
   "description": "Shows pending and firing alerts in the cluster.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(ALERTS{project=~\"$project\", shoot_name=~\"$shoot\"}) by (alertname, alertstate)",
     "legendFormat": "{{ alertname }}/{{ alertstate }}"
    }
   ]
  }
 ]
}