{
 "title": "Shoot SLA",
 "time": { "from": "now-15d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "iaas",
    "query": "label_values(garden_shoot_condition, iaas)"
   },
   {
    "name": "project",
    "query": "label_values(garden_shoot_condition{condition=\"APIServerAvailable\",operation=\"Reconcile\",iaas=\"$iaas\"}, project)"
   },
   {
    "name": "name",
    "query": "label_values(garden_shoot_condition{condition=\"APIServerAvailable\",operation=\"Reconcile\",iaas=\"$iaas\", project=~\"$project\"}, name)"
   },
   {
    "name": "purpose",
    "query": "label_values(garden_shoot_condition{condition=\"APIServerAvailable\",operation=\"Reconcile\"}, purpose)"
   }
  ]
 },
 "panels": [
  {
   "title": "SLA (over the last 7 days)",
   "type": "text",
   "gridPos": { "h": 2, "w": 22, "x": 0, "y": 0 },
   "options": {
    "content": "[99.95%][] allows for 5 minutes of downtime per week\n\n[99.95%]: https://uptime.is/99.95\n\n\n"
   }
  },
  {
   "title": "# of shoots",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(\n  count_over_time(\n    garden_shoot_condition{condition=\"APIServerAvailable\",operation=\"Reconcile\",project=~\"$project\",name=~\"$name\",iaas=\"$iaas\", purpose=~\"$purpose\"}[7d:]\n  )\n)"
    }
   ]
  },
  {
   "title": "# with > 5 down minutes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(\n  count_over_time(\n    (garden_shoot_condition{condition=\"APIServerAvailable\",operation=\"Reconcile\",project=~\"$project\",name=~\"$name\",iaas=\"$iaas\", purpose=~\"$purpose\"} < 1)[7d:]\n  ) > 5\n)"
    }
   ]
  },
  {
   "title": "% with > 5 down minutes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 7, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(\n  count_over_time(\n    (garden_shoot_condition{condition=\"APIServerAvailable\",operation=\"Reconcile\",iaas=\"$iaas\",project=~\"$project\",name=~\"$name\",purpose=~\"$purpose\"} < 1)[7d:]\n  ) > 5\n)\n/\ncount(\n  count_over_time(\n    (garden_shoot_condition{condition=\"APIServerAvailable\",operation=\"Reconcile\",iaas=\"$iaas\",project=~\"$project\",name=~\"$name\",purpose=~\"$purpose\"})[7d :]\n  )\n)"
    }
   ]
  },
  {
   "title": "Shoots with > 5 down minutes during the last 7 days",
   "type": "table",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (project, name) (\n  count_over_time(\n    (garden_shoot_condition{condition=\"APIServerAvailable\",operation=\"Reconcile\",iaas=\"$iaas\",project=~\"$project\",name=~\"$name\",purpose=~\"$purpose\"} < 1)[7d:]\n  ) > 5\n)"
    }
   ]
  },
  {
   "title": "Down minutes",
   "type": "graph",
   "gridPos": { "h": 15, "w": 11, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "min_over_time(\n  garden_shoot_condition{condition=\"APIServerAvailable\",operation=\"Reconcile\",iaas=\"$iaas\",project=~\"$project\",name=~\"$name\",purpose=~\"$purpose\"}[$__interval:]\n) < 1",
     "legendFormat": "{{project}} {{name}}"
    }
   ]
  },
  {
   "title": "Cumulative down minutes of the trailing 7 days (filtered for >3), >5 violates 99.95% SLO",
   "type": "graph",
   "gridPos": { "h": 15, "w": 13, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count_over_time(\n  (sum without (instance)\n     (garden_shoot_condition{condition=\"APIServerAvailable\",operation=\"Reconcile\",iaas=\"$iaas\",project=~\"$project\",name=~\"$name\",purpose=~\"$purpose\"} < 1)\n  )[7d:]\n) > 3",
     "legendFormat": "{{project}} {{name}}"
    }
   ]
  }
 ]
}