{
 "title": "Shoot Availability",
 "tags": [
  "shoot",
  "landscape"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Shoots by Infrastructure",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(garden_shoot_info) by (iaas)",
     "legendFormat": "{{ iaas }}"
    }
   ]
  },
  {
   "title": "Shoot Availability",
   "type": "gauge",
   "description": "Shows the current % of available shoots.",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "count(garden_shoot_condition{condition=\"APIServerAvailable\"} == 1) / count(garden_shoot_info) * 100"
    }
   ]
  },
  {
   "title": "Total number of shoots",
   "type": "gauge",
   "description": "Shows the total number of shoot clusters (including shooted seeds).",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "targets": [
    { "expr": "count(garden_shoot_info)" }
   ]
  },
  {
   "title": "Unavailable Shoots",
   "type": "gauge",
   "description": "Shows the total number of unavailable shoot clusters (including shooted seeds).",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "expr": "count(garden_shoot_condition{condition=\"APIServerAvailable\"} == 0)"
    }
   ]
  },
  {
   "title": "Total Availability",
   "type": "graph",
   "description": "Shows the availability of all shoot clusters.",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(garden_shoot_condition{condition=\"APIServerAvailable\"} == 1) / count(garden_shoot_info) * 100",
     "legendFormat": "Availability"
    }
   ]
  },
  {
   "title": "Shoot Availability",
   "type": "graph",
   "description": "Shows the availability of all shoots.",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "garden_shoot_condition{condition=\"APIServerAvailable\"}",
     "legendFormat": "{{ iaas }}/shoot--{{ project }}--{{ name }}/{{ seed }}"
    }
   ]
  },
  {
   "title": "Unavailable Shoots",
   "type": "table",
   "description": "List of shoots that are unavailable.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "count(garden_shoot_condition{condition=\"APIServerAvailable\"} == 0) by (name, project, seed, iaas)"
    }
   ]
  }
 ]
}