{
 "title": "Virtual Garden ETCD Backup Dashboard",
 "description": "Dashboard with information about the virtual garden etcd backups.",
 "tags": [ "Gardener" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(etcdbr_network_received_bytes, role)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latest Snapshot Timestamp",
   "type": "singlestat",
   "description": "Timestamp of the latest snapshot successfully uploaded to the snapstore.",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 1 },
   "format": "dateTimeAsUS",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(etcdbr_snapshot_latest_timestamp{role=\"$cluster\"})*1000"
    }
   ]
  },
  {
   "title": "Maximum Possible Data Loss",
   "type": "singlestat",
   "description": "Maximum duration worth of possible data loss in the event that etcd data gets corrupted at this moment.",
   "gridPos": { "h": 5, "w": 6, "x": 11, "y": 1 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "time()-max(etcdbr_snapshot_latest_timestamp{role=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Latest Snapshot Revision",
   "type": "singlestat",
   "description": "Latest revision of the data from the latest snapshot uploaded to the snapstore.",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(etcdbr_snapshot_latest_revision{role=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Full Snapshots",
   "type": "graph",
   "description": "Total number of full snapshots successfully uploaded to the snapstore, as well as total number of failed attempts for the same, over time.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "etcdbr_snapshot_duration_seconds_count{role=\"$cluster\",kind=\"Full\",succeeded=\"true\"}",
     "legendFormat": "Succeeded"
    },
    {
     "expr": "etcdbr_snapshot_duration_seconds_count{role=\"$cluster\",kind=\"Full\",succeeded=\"false\"}",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Delta Snapshots",
   "type": "graph",
   "description": "Total number of delta snapshots successfully uploaded to the snapstore, as well as total number of failed attempts for the same, over time.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "etcdbr_snapshot_duration_seconds_count{role=\"$cluster\",kind=\"Incr\",succeeded=\"true\"}",
     "legendFormat": "Succeeded"
    },
    {
     "expr": "etcdbr_snapshot_duration_seconds_count{role=\"$cluster\",kind=\"Incr\",succeeded=\"false\"}",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Snapshot Garbage Collection",
   "type": "graph",
   "description": "Total number of snapshots successfully garbage-collected from the snapstore, as well as total number of failed attempts for the same, over time.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(etcdbr_snapshot_gc_total{role=\"$cluster\",succeeded=\"true\",kind=~\"Full|Incr\"})",
     "legendFormat": "Succeeded"
    },
    {
     "expr": "sum(etcdbr_snapshot_gc_total{role=\"$cluster\",succeeded=\"false\",kind=~\"Full|Incr\"})",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Etcd Defragmentation",
   "type": "graph",
   "description": "Total number of successful and failed attempts to defragment the etcd data store over time.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "etcdbr_defragmentation_duration_seconds_count{role=\"$cluster\",succeeded=\"true\"}",
     "legendFormat": "Succeeded"
    },
    {
     "expr": "etcdbr_defragmentation_duration_seconds_count{role=\"$cluster\",succeeded=\"false\"}",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Snapshot Duration",
   "type": "graph",
   "description": "Duration of taking full and delta snapshots over time.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcdbr_snapshot_duration_seconds_bucket{role=\"$cluster\",kind=\"Full\"}[2h])) by (le))",
     "legendFormat": "Full"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcdbr_snapshot_duration_seconds_bucket{role=\"$cluster\",kind=\"Incr\"}[10m])) by (le))",
     "legendFormat": "Delta"
    }
   ]
  },
  {
   "title": "Etcd Data Validation",
   "type": "graph",
   "description": "Total number of successful and failed attempts at etcd data validations over time.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "etcdbr_validation_duration_seconds_count{role=\"$cluster\",succeeded=\"true\"}",
     "legendFormat": "Succeeded"
    },
    {
     "expr": "etcdbr_validation_duration_seconds_count{role=\"$cluster\",succeeded=\"false\"}",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Etcd Data Restoration",
   "type": "graph",
   "description": "Total number of successful and failed attempts at etcd data restorations over time.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "etcdbr_restoration_duration_seconds_count{role=\"$cluster\",succeeded=\"true\"}",
     "legendFormat": "Succeeded"
    },
    {
     "expr": "etcdbr_restoration_duration_seconds_count{role=\"$cluster\",succeeded=\"false\"}",
     "legendFormat": "Failed"
    }
   ]
  },
  { "title": "Resource Consumption", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Memory",
   "type": "graph",
   "description": "Memory consumed by etcd-backup-restore process over time.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{role=\"$cluster\",job=\"virtual-garden-etcd-backup\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "description": "Total CPU usage by etcd-backup-restore process as a percentage of total available CPU to the container, over time.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{role=\"$cluster\",job=\"virtual-garden-etcd-backup\"}[5m]) * 100",
     "legendFormat": "CPU"
    }
   ]
  }
 ]
}