#!/bin/bash -e
#
# Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

go run cmd/registry-migrator/main.go \
  --backup-file "$HOME/Desktop/etcd-step1.backup" \
  --old-registry-prefix "/registry/garden.sapcloud.io" \
  --new-registry-prefix "/registry-gardener" \
  --endpoints "http://localhost:32379" \
  --force=false \
  --delete=false

go run cmd/registry-migrator/main.go \
  --backup-file "$HOME/Desktop/etcd-step2.backup" \
   --old-registry-prefix "/registry-gardener/garden.sapcloud.io" \
   --new-registry-prefix "/registry-gardener/core.gardener.cloud" \
   --endpoints "http://localhost:32379" \
   --force=false \
   --delete=false
