#!/usr/bin/env bash
#
# SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -e
set -u

NAME="$1"
NAMESPACE="${2:-$(id -u -n)}"
OPERATION="${3:-reconcile}"

kubectl --namespace "$NAMESPACE" annotate shoot "$NAME" gardener.cloud/operation="$OPERATION" --overwrite
