//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	config "github.com/gardener/gardener/pkg/controllermanager/apis/config"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	componentbaseconfig "k8s.io/component-base/config"
	configv1alpha1 "k8s.io/component-base/config/v1alpha1"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*BastionControllerConfiguration)(nil), (*config.BastionControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_BastionControllerConfiguration_To_config_BastionControllerConfiguration(a.(*BastionControllerConfiguration), b.(*config.BastionControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.BastionControllerConfiguration)(nil), (*BastionControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_BastionControllerConfiguration_To_v1alpha1_BastionControllerConfiguration(a.(*config.BastionControllerConfiguration), b.(*BastionControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CertificateSigningRequestControllerConfiguration)(nil), (*config.CertificateSigningRequestControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CertificateSigningRequestControllerConfiguration_To_config_CertificateSigningRequestControllerConfiguration(a.(*CertificateSigningRequestControllerConfiguration), b.(*config.CertificateSigningRequestControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.CertificateSigningRequestControllerConfiguration)(nil), (*CertificateSigningRequestControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_CertificateSigningRequestControllerConfiguration_To_v1alpha1_CertificateSigningRequestControllerConfiguration(a.(*config.CertificateSigningRequestControllerConfiguration), b.(*CertificateSigningRequestControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CloudProfileControllerConfiguration)(nil), (*config.CloudProfileControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CloudProfileControllerConfiguration_To_config_CloudProfileControllerConfiguration(a.(*CloudProfileControllerConfiguration), b.(*config.CloudProfileControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.CloudProfileControllerConfiguration)(nil), (*CloudProfileControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_CloudProfileControllerConfiguration_To_v1alpha1_CloudProfileControllerConfiguration(a.(*config.CloudProfileControllerConfiguration), b.(*CloudProfileControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ConditionThreshold)(nil), (*config.ConditionThreshold)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ConditionThreshold_To_config_ConditionThreshold(a.(*ConditionThreshold), b.(*config.ConditionThreshold), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ConditionThreshold)(nil), (*ConditionThreshold)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ConditionThreshold_To_v1alpha1_ConditionThreshold(a.(*config.ConditionThreshold), b.(*ConditionThreshold), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ControllerDeploymentControllerConfiguration)(nil), (*config.ControllerDeploymentControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ControllerDeploymentControllerConfiguration_To_config_ControllerDeploymentControllerConfiguration(a.(*ControllerDeploymentControllerConfiguration), b.(*config.ControllerDeploymentControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ControllerDeploymentControllerConfiguration)(nil), (*ControllerDeploymentControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ControllerDeploymentControllerConfiguration_To_v1alpha1_ControllerDeploymentControllerConfiguration(a.(*config.ControllerDeploymentControllerConfiguration), b.(*ControllerDeploymentControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ControllerManagerConfiguration)(nil), (*config.ControllerManagerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ControllerManagerConfiguration_To_config_ControllerManagerConfiguration(a.(*ControllerManagerConfiguration), b.(*config.ControllerManagerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ControllerManagerConfiguration)(nil), (*ControllerManagerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ControllerManagerConfiguration_To_v1alpha1_ControllerManagerConfiguration(a.(*config.ControllerManagerConfiguration), b.(*ControllerManagerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ControllerManagerControllerConfiguration)(nil), (*config.ControllerManagerControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ControllerManagerControllerConfiguration_To_config_ControllerManagerControllerConfiguration(a.(*ControllerManagerControllerConfiguration), b.(*config.ControllerManagerControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ControllerManagerControllerConfiguration)(nil), (*ControllerManagerControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ControllerManagerControllerConfiguration_To_v1alpha1_ControllerManagerControllerConfiguration(a.(*config.ControllerManagerControllerConfiguration), b.(*ControllerManagerControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ControllerRegistrationControllerConfiguration)(nil), (*config.ControllerRegistrationControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ControllerRegistrationControllerConfiguration_To_config_ControllerRegistrationControllerConfiguration(a.(*ControllerRegistrationControllerConfiguration), b.(*config.ControllerRegistrationControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ControllerRegistrationControllerConfiguration)(nil), (*ControllerRegistrationControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ControllerRegistrationControllerConfiguration_To_v1alpha1_ControllerRegistrationControllerConfiguration(a.(*config.ControllerRegistrationControllerConfiguration), b.(*ControllerRegistrationControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*EventControllerConfiguration)(nil), (*config.EventControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_EventControllerConfiguration_To_config_EventControllerConfiguration(a.(*EventControllerConfiguration), b.(*config.EventControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.EventControllerConfiguration)(nil), (*EventControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_EventControllerConfiguration_To_v1alpha1_EventControllerConfiguration(a.(*config.EventControllerConfiguration), b.(*EventControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ExposureClassControllerConfiguration)(nil), (*config.ExposureClassControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ExposureClassControllerConfiguration_To_config_ExposureClassControllerConfiguration(a.(*ExposureClassControllerConfiguration), b.(*config.ExposureClassControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ExposureClassControllerConfiguration)(nil), (*ExposureClassControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ExposureClassControllerConfiguration_To_v1alpha1_ExposureClassControllerConfiguration(a.(*config.ExposureClassControllerConfiguration), b.(*ExposureClassControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ManagedSeedSetControllerConfiguration)(nil), (*config.ManagedSeedSetControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ManagedSeedSetControllerConfiguration_To_config_ManagedSeedSetControllerConfiguration(a.(*ManagedSeedSetControllerConfiguration), b.(*config.ManagedSeedSetControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ManagedSeedSetControllerConfiguration)(nil), (*ManagedSeedSetControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ManagedSeedSetControllerConfiguration_To_v1alpha1_ManagedSeedSetControllerConfiguration(a.(*config.ManagedSeedSetControllerConfiguration), b.(*ManagedSeedSetControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProjectControllerConfiguration)(nil), (*config.ProjectControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProjectControllerConfiguration_To_config_ProjectControllerConfiguration(a.(*ProjectControllerConfiguration), b.(*config.ProjectControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ProjectControllerConfiguration)(nil), (*ProjectControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ProjectControllerConfiguration_To_v1alpha1_ProjectControllerConfiguration(a.(*config.ProjectControllerConfiguration), b.(*ProjectControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.QuotaConfiguration)(nil), (*QuotaConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_QuotaConfiguration_To_v1alpha1_QuotaConfiguration(a.(*config.QuotaConfiguration), b.(*QuotaConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*QuotaControllerConfiguration)(nil), (*config.QuotaControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_QuotaControllerConfiguration_To_config_QuotaControllerConfiguration(a.(*QuotaControllerConfiguration), b.(*config.QuotaControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.QuotaControllerConfiguration)(nil), (*QuotaControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_QuotaControllerConfiguration_To_v1alpha1_QuotaControllerConfiguration(a.(*config.QuotaControllerConfiguration), b.(*QuotaControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SecretBindingControllerConfiguration)(nil), (*config.SecretBindingControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SecretBindingControllerConfiguration_To_config_SecretBindingControllerConfiguration(a.(*SecretBindingControllerConfiguration), b.(*config.SecretBindingControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.SecretBindingControllerConfiguration)(nil), (*SecretBindingControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_SecretBindingControllerConfiguration_To_v1alpha1_SecretBindingControllerConfiguration(a.(*config.SecretBindingControllerConfiguration), b.(*SecretBindingControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SeedBackupBucketsCheckControllerConfiguration)(nil), (*config.SeedBackupBucketsCheckControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SeedBackupBucketsCheckControllerConfiguration_To_config_SeedBackupBucketsCheckControllerConfiguration(a.(*SeedBackupBucketsCheckControllerConfiguration), b.(*config.SeedBackupBucketsCheckControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.SeedBackupBucketsCheckControllerConfiguration)(nil), (*SeedBackupBucketsCheckControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_SeedBackupBucketsCheckControllerConfiguration_To_v1alpha1_SeedBackupBucketsCheckControllerConfiguration(a.(*config.SeedBackupBucketsCheckControllerConfiguration), b.(*SeedBackupBucketsCheckControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SeedControllerConfiguration)(nil), (*config.SeedControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SeedControllerConfiguration_To_config_SeedControllerConfiguration(a.(*SeedControllerConfiguration), b.(*config.SeedControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.SeedControllerConfiguration)(nil), (*SeedControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_SeedControllerConfiguration_To_v1alpha1_SeedControllerConfiguration(a.(*config.SeedControllerConfiguration), b.(*SeedControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SeedExtensionsCheckControllerConfiguration)(nil), (*config.SeedExtensionsCheckControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SeedExtensionsCheckControllerConfiguration_To_config_SeedExtensionsCheckControllerConfiguration(a.(*SeedExtensionsCheckControllerConfiguration), b.(*config.SeedExtensionsCheckControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.SeedExtensionsCheckControllerConfiguration)(nil), (*SeedExtensionsCheckControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_SeedExtensionsCheckControllerConfiguration_To_v1alpha1_SeedExtensionsCheckControllerConfiguration(a.(*config.SeedExtensionsCheckControllerConfiguration), b.(*SeedExtensionsCheckControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Server)(nil), (*config.Server)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Server_To_config_Server(a.(*Server), b.(*config.Server), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.Server)(nil), (*Server)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_Server_To_v1alpha1_Server(a.(*config.Server), b.(*Server), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ServerConfiguration)(nil), (*config.ServerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ServerConfiguration_To_config_ServerConfiguration(a.(*ServerConfiguration), b.(*config.ServerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ServerConfiguration)(nil), (*ServerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ServerConfiguration_To_v1alpha1_ServerConfiguration(a.(*config.ServerConfiguration), b.(*ServerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ShootConditionsControllerConfiguration)(nil), (*config.ShootConditionsControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ShootConditionsControllerConfiguration_To_config_ShootConditionsControllerConfiguration(a.(*ShootConditionsControllerConfiguration), b.(*config.ShootConditionsControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ShootConditionsControllerConfiguration)(nil), (*ShootConditionsControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ShootConditionsControllerConfiguration_To_v1alpha1_ShootConditionsControllerConfiguration(a.(*config.ShootConditionsControllerConfiguration), b.(*ShootConditionsControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ShootHibernationControllerConfiguration)(nil), (*config.ShootHibernationControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ShootHibernationControllerConfiguration_To_config_ShootHibernationControllerConfiguration(a.(*ShootHibernationControllerConfiguration), b.(*config.ShootHibernationControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ShootHibernationControllerConfiguration)(nil), (*ShootHibernationControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ShootHibernationControllerConfiguration_To_v1alpha1_ShootHibernationControllerConfiguration(a.(*config.ShootHibernationControllerConfiguration), b.(*ShootHibernationControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ShootMaintenanceControllerConfiguration)(nil), (*config.ShootMaintenanceControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ShootMaintenanceControllerConfiguration_To_config_ShootMaintenanceControllerConfiguration(a.(*ShootMaintenanceControllerConfiguration), b.(*config.ShootMaintenanceControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ShootMaintenanceControllerConfiguration)(nil), (*ShootMaintenanceControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ShootMaintenanceControllerConfiguration_To_v1alpha1_ShootMaintenanceControllerConfiguration(a.(*config.ShootMaintenanceControllerConfiguration), b.(*ShootMaintenanceControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ShootQuotaControllerConfiguration)(nil), (*config.ShootQuotaControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ShootQuotaControllerConfiguration_To_config_ShootQuotaControllerConfiguration(a.(*ShootQuotaControllerConfiguration), b.(*config.ShootQuotaControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ShootQuotaControllerConfiguration)(nil), (*ShootQuotaControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ShootQuotaControllerConfiguration_To_v1alpha1_ShootQuotaControllerConfiguration(a.(*config.ShootQuotaControllerConfiguration), b.(*ShootQuotaControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ShootReferenceControllerConfiguration)(nil), (*config.ShootReferenceControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ShootReferenceControllerConfiguration_To_config_ShootReferenceControllerConfiguration(a.(*ShootReferenceControllerConfiguration), b.(*config.ShootReferenceControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ShootReferenceControllerConfiguration)(nil), (*ShootReferenceControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ShootReferenceControllerConfiguration_To_v1alpha1_ShootReferenceControllerConfiguration(a.(*config.ShootReferenceControllerConfiguration), b.(*ShootReferenceControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ShootRetryControllerConfiguration)(nil), (*config.ShootRetryControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ShootRetryControllerConfiguration_To_config_ShootRetryControllerConfiguration(a.(*ShootRetryControllerConfiguration), b.(*config.ShootRetryControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ShootRetryControllerConfiguration)(nil), (*ShootRetryControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ShootRetryControllerConfiguration_To_v1alpha1_ShootRetryControllerConfiguration(a.(*config.ShootRetryControllerConfiguration), b.(*ShootRetryControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ShootStatusLabelControllerConfiguration)(nil), (*config.ShootStatusLabelControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ShootStatusLabelControllerConfiguration_To_config_ShootStatusLabelControllerConfiguration(a.(*ShootStatusLabelControllerConfiguration), b.(*config.ShootStatusLabelControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ShootStatusLabelControllerConfiguration)(nil), (*ShootStatusLabelControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ShootStatusLabelControllerConfiguration_To_v1alpha1_ShootStatusLabelControllerConfiguration(a.(*config.ShootStatusLabelControllerConfiguration), b.(*ShootStatusLabelControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*QuotaConfiguration)(nil), (*config.QuotaConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_QuotaConfiguration_To_config_QuotaConfiguration(a.(*QuotaConfiguration), b.(*config.QuotaConfiguration), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_BastionControllerConfiguration_To_config_BastionControllerConfiguration(in *BastionControllerConfiguration, out *config.BastionControllerConfiguration, s conversion.Scope) error {
	out.ConcurrentSyncs = (*int)(unsafe.Pointer(in.ConcurrentSyncs))
	out.MaxLifetime = (*v1.Duration)(unsafe.Pointer(in.MaxLifetime))
	return nil
}

// Convert_v1alpha1_BastionControllerConfiguration_To_config_BastionControllerConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_BastionControllerConfiguration_To_config_BastionControllerConfiguration(in *BastionControllerConfiguration, out *config.BastionControllerConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_BastionControllerConfiguration_To_config_BastionControllerConfiguration(in, out, s)
}

func autoConvert_config_BastionControllerConfiguration_To_v1alpha1_BastionControllerConfiguration(in *config.BastionControllerConfiguration, out *BastionControllerConfiguration, s conversion.Scope) error {
	out.ConcurrentSyncs = (*int)(unsafe.Pointer(in.ConcurrentSyncs))
	out.MaxLifetime = (*v1.Duration)(unsafe.Pointer(in.MaxLifetime))
	return nil
}

// Convert_config_BastionControllerConfiguration_To_v1alpha1_BastionControllerConfiguration is an autogenerated conversion function.
func Convert_config_BastionControllerConfiguration_To_v1alpha1_BastionControllerConfiguration(in *config.BastionControllerConfiguration, out *BastionControllerConfiguration, s conversion.Scope) error {
	return autoConvert_config_BastionControllerConfiguration_To_v1alpha1_BastionControllerConfiguration(in, out, s)
}

func autoConvert_v1alpha1_CertificateSigningRequestControllerConfiguration_To_config_CertificateSigningRequestControllerConfiguration(in *CertificateSigningRequestControllerConfiguration, out *config.CertificateSigningRequestControllerConfiguration, s conversion.Scope) error {
	out.ConcurrentSyncs = (*int)(unsafe.Pointer(in.ConcurrentSyncs))
	return nil
}

// Convert_v1alpha1_CertificateSigningRequestControllerConfiguration_To_config_CertificateSigningRequestControllerConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_CertificateSigningRequestControllerConfiguration_To_config_CertificateSigningRequestControllerConfiguration(in *CertificateSigningRequestControllerConfiguration, out *config.CertificateSigningRequestControllerConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_CertificateSigningRequestControllerConfiguration_To_config_CertificateSigningRequestControllerConfiguration(in, out, s)
}

func autoConvert_config_CertificateSigningRequestControllerConfiguration_To_v1alpha1_CertificateSigningRequestControllerConfiguration(in *config.CertificateSigningRequestControllerConfiguration, out *CertificateSigningRequestControllerConfiguration, s conversion.Scope) error {
	out.ConcurrentSyncs = (*int)(unsafe.Pointer(in.ConcurrentSyncs))
	return nil
}

// Convert_config_CertificateSigningRequestControllerConfiguration_To_v1alpha1_CertificateSigningRequestControllerConfiguration is an autogenerated conversion function.
func Convert_config_CertificateSigningRequestControllerConfiguration_To_v1alpha1_CertificateSigningRequestControllerConfiguration(in *config.CertificateSigningRequestControllerConfiguration, out *CertificateSigningRequestControllerConfiguration, s conversion.Scope) error {
	return autoConvert_config_CertificateSigningRequestControllerConfiguration_To_v1alpha1_CertificateSigningRequestControllerConfiguration(in, out, s)
}

func autoConvert_v1alpha1_CloudProfileControllerConfiguration_To_config_CloudProfileControllerConfiguration(in *CloudProfileControllerConfiguration, out *config.CloudProfileControllerConfiguration, s conversion.Scope) error {
	out.ConcurrentSyncs = (*int)(unsafe.Pointer(in.ConcurrentSyncs))
	return nil
}

// Convert_v1alpha1_CloudProfileControllerConfiguration_To_config_CloudProfileControllerConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_CloudProfileControllerConfiguration_To_config_CloudProfileControllerConfiguration(in *CloudProfileControllerConfiguration, out *config.CloudProfileControllerConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_CloudProfileControllerConfiguration_To_config_CloudProfileControllerConfiguration(in, out, s)
}

func autoConvert_config_CloudProfileControllerConfiguration_To_v1alpha1_CloudProfileControllerConfiguration(in *config.CloudProfileControllerConfiguration, out *CloudProfileControllerConfiguration, s conversion.Scope) error {
	out.ConcurrentSyncs = (*int)(unsafe.Pointer(in.ConcurrentSyncs))
	return nil
}

// Convert_config_CloudProfileControllerConfiguration_To_v1alpha1_CloudProfileControllerConfiguration is an autogenerated conversion function.
func Convert_config_CloudProfileControllerConfiguration_To_v1alpha1_CloudProfileControllerConfiguration(in *config.CloudProfileControllerConfiguration, out *CloudProfileControllerConfiguration, s conversion.Scope) error {
	return autoConvert_config_CloudProfileControllerConfiguration_To_v1alpha1_CloudProfileControllerConfiguration(in, out, s)
}

func autoConvert_v1alpha1_ConditionThreshold_To_config_ConditionThreshold(in *ConditionThreshold, out *config.ConditionThreshold, s conversion.Scope) error {
	out.Type = in.Type
	out.Duration = in.Duration
	return nil
}

// Convert_v1alpha1_ConditionThreshold_To_config_ConditionThreshold is an autogenerated conversion function.
func Convert_v1alpha1_ConditionThreshold_To_config_ConditionThreshold(in *ConditionThreshold, out *config.ConditionThreshold, s conversion.Scope) error {
	return autoConvert_v1alpha1_ConditionThreshold_To_config_ConditionThreshold(in, out, s)
}

func autoConvert_config_ConditionThreshold_To_v1alpha1_ConditionThreshold(in *config.ConditionThreshold, out *ConditionThreshold, s conversion.Scope) error {
	out.Type = in.Type
	out.Duration = in.Duration
	return nil
}

// Convert_config_ConditionThreshold_To_v1alpha1_ConditionThreshold is an autogenerated conversion function.
func Convert_config_ConditionThreshold_To_v1alpha1_ConditionThreshold(in *config.ConditionThreshold, out *ConditionThreshold, s conversion.Scope) error {
	return autoConvert_config_ConditionThreshold_To_v1alpha1_ConditionThreshold(in, out, s)
}

func autoConvert_v1alpha1_ControllerDeploymentControllerConfiguration_To_config_ControllerDeploymentControllerConfiguration(in *ControllerDeploymentControllerConfiguration, out *config.ControllerDeploymentControllerConfiguration, s conversion.Scope) error {
	out.ConcurrentSyncs = (*int)(unsafe.Pointer(in.ConcurrentSyncs))
	return nil
}

// Convert_v1alpha1_ControllerDeploymentControllerConfiguration_To_config_ControllerDeploymentControllerConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_ControllerDeploymentControllerConfiguration_To_config_ControllerDeploymentControllerConfiguration(in *ControllerDeploymentControllerConfiguration, out *config.ControllerDeploymentControllerConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_ControllerDeploymentControllerConfiguration_To_config_ControllerDeploymentControllerConfiguration(in, out, s)
}

func autoConvert_config_ControllerDeploymentControllerConfiguration_To_v1alpha1_ControllerDeploymentControllerConfiguration(in *config.ControllerDeploymentControllerConfiguration, out *ControllerDeploymentControllerConfiguration, s conversion.Scope) error {
	out.ConcurrentSyncs = (*int)(unsafe.Pointer(in.ConcurrentSyncs))
	return nil
}

// Convert_config_ControllerDeploymentControllerConfiguration_To_v1alpha1_ControllerDeploymentControllerConfiguration is an autogenerated conversion function.
func Convert_config_ControllerDeploymentControllerConfiguration_To_v1alpha1_ControllerDeploymentControllerConfiguration(in *config.ControllerDeploymentControllerConfiguration, out *ControllerDeploymentControllerConfiguration, s conversion.Scope) error {
	return autoConvert_config_ControllerDeploymentControllerConfiguration_To_v1alpha1_ControllerDeploymentControllerConfiguration(in, out, s)
}

func autoConvert_v1alpha1_ControllerManagerConfiguration_To_config_ControllerManagerConfiguration(in *ControllerManagerConfiguration, out *config.ControllerManagerConfiguration, s conversion.Scope) error {
	if err := configv1alpha1.Convert_v1alpha1_ClientConnectionConfiguration_To_config_ClientConnectionConfiguration(&in.GardenClientConnection, &out.GardenClientConnection, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ControllerManagerControllerConfiguration_To_config_ControllerManagerControllerConfiguration(&in.Controllers, &out.Controllers, s); err != nil {
		return err
	}
	if in.LeaderElection != nil {
		in, out := &in.LeaderElection, &out.LeaderElection
		*out = new(componentbaseconfig.LeaderElectionConfiguration)
		if err := configv1alpha1.Convert_v1alpha1_LeaderElectionConfiguration_To_config_LeaderElectionConfiguration(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.LeaderElection = nil
	}
	out.LogLevel = in.LogLevel
	out.LogFormat = in.LogFormat
	if err := Convert_v1alpha1_ServerConfiguration_To_config_ServerConfiguration(&in.Server, &out.Server, s); err != nil {
		return err
	}
	if in.Debugging != nil {
		in, out := &in.Debugging, &out.Debugging
		*out = new(componentbaseconfig.DebuggingConfiguration)
		if err := configv1alpha1.Convert_v1alpha1_DebuggingConfiguration_To_config_DebuggingConfiguration(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.Debugging = nil
	}
	out.FeatureGates = *(*map[string]bool)(unsafe.Pointer(&in.FeatureGates))
	return nil
}

// Convert_v1alpha1_ControllerManagerConfiguration_To_config_ControllerManagerConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_ControllerManagerConfiguration_To_config_ControllerManagerConfiguration(in *ControllerManagerConfiguration, out *config.ControllerManagerConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_ControllerManagerConfiguration_To_config_ControllerManagerConfiguration(in, out, s)
}

func autoConvert_config_ControllerManagerConfiguration_To_v1alpha1_ControllerManagerConfiguration(in *config.ControllerManagerConfiguration, out *ControllerManagerConfiguration, s conversion.Scope) error {
	if err := configv1alpha1.Convert_config_ClientConnectionConfiguration_To_v1alpha1_ClientConnectionConfiguration(&in.GardenClientConnection, &out.GardenClientConnection, s); err != nil {
		return err
	}
	if err := Convert_config_ControllerManagerControllerConfiguration_To_v1alpha1_ControllerManagerControllerConfiguration(&in.Controllers, &out.Controllers, s); err != nil {
		return err
	}
	if in.LeaderElection != nil {
		in, out := &in.LeaderElection, &out.LeaderElection
		*out = new(configv1alpha1.LeaderElectionConfiguration)
		if err := configv1alpha1.Convert_config_LeaderElectionConfiguration_To_v1alpha1_LeaderElectionConfiguration(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.LeaderElection = nil
	}
	out.LogLevel = in.LogLevel
	out.LogFormat = in.LogFormat
	if err := Convert_config_ServerConfiguration_To_v1alpha1_ServerConfiguration(&in.Server, &out.Server, s); err != nil {
		return err
	}
	if in.Debugging != nil {
		in, out := &in.Debugging, &out.Debugging
		*out = new(configv1alpha1.DebuggingConfiguration)
		if err := configv1alpha1.Convert_config_DebuggingConfiguration_To_v1alpha1_DebuggingConfiguration(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.Debugging = nil
	}
	out.FeatureGates = *(*map[string]bool)(unsafe.Pointer(&in.FeatureGates))
	return nil
}

// Convert_config_ControllerManagerConfiguration_To_v1alpha1_ControllerManagerConfiguration is an autogenerated conversion function.
func Convert_config_ControllerManagerConfiguration_To_v1alpha1_ControllerManagerConfiguration(in *config.ControllerManagerConfiguration, out *ControllerManagerConfiguration, s conversion.Scope) error {
	return autoConvert_config_ControllerManagerConfiguration_To_v1alpha1_ControllerManagerConfiguration(in, out, s)
}

func autoConvert_v1alpha1_ControllerManagerControllerConfiguration_To_config_ControllerManagerControllerConfiguration(in *ControllerManagerControllerConfiguration, out *config.ControllerManagerControllerConfiguration, s conversion.Scope) error {
	out.Bastion = (*config.BastionControllerConfiguration)(unsafe.Pointer(in.Bastion))
	out.CertificateSigningRequest = (*config.CertificateSigningRequestControllerConfiguration)(unsafe.Pointer(in.CertificateSigningRequest))
	out.CloudProfile = (*config.CloudProfileControllerConfiguration)(unsafe.Pointer(in.CloudProfile))
	out.ControllerDeployment = (*config.ControllerDeploymentControllerConfiguration)(unsafe.Pointer(in.ControllerDeployment))
	out.ControllerRegistration = (*config.ControllerRegistrationControllerConfiguration)(unsafe.Pointer(in.ControllerRegistration))
	out.Event = (*config.EventControllerConfiguration)(unsafe.Pointer(in.Event))
	out.ExposureClass = (*config.ExposureClassControllerConfiguration)(unsafe.Pointer(in.ExposureClass))
	if in.Project != nil {
		in, out := &in.Project, &out.Project
		*out = new(config.ProjectControllerConfiguration)
		if err := Convert_v1alpha1_ProjectControllerConfiguration_To_config_ProjectControllerConfiguration(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.Project = nil
	}
	out.Quota = (*config.QuotaControllerConfiguration)(unsafe.Pointer(in.Quota))
	out.SecretBinding = (*config.SecretBindingControllerConfiguration)(unsafe.Pointer(in.SecretBinding))
	out.Seed = (*config.SeedControllerConfiguration)(unsafe.Pointer(in.Seed))
	out.SeedExtensionsCheck = (*config.SeedExtensionsCheckControllerConfiguration)(unsafe.Pointer(in.SeedExtensionsCheck))
	out.SeedBackupBucketsCheck = (*config.SeedBackupBucketsCheckControllerConfiguration)(unsafe.Pointer(in.SeedBackupBucketsCheck))
	if err := Convert_v1alpha1_ShootMaintenanceControllerConfiguration_To_config_ShootMaintenanceControllerConfiguration(&in.ShootMaintenance, &out.ShootMaintenance, s); err != nil {
		return err
	}
	out.ShootQuota = (*config.ShootQuotaControllerConfiguration)(unsafe.Pointer(in.ShootQuota))
	if err := Convert_v1alpha1_ShootHibernationControllerConfiguration_To_config_ShootHibernationControllerConfiguration(&in.ShootHibernation, &out.ShootHibernation, s); err != nil {
		return err
	}
	out.ShootReference = (*config.ShootReferenceControllerConfiguration)(unsafe.Pointer(in.ShootReference))
	out.ShootRetry = (*config.ShootRetryControllerConfiguration)(unsafe.Pointer(in.ShootRetry))
	out.ShootConditions = (*config.ShootConditionsControllerConfiguration)(unsafe.Pointer(in.ShootConditions))
	out.ShootStatusLabel = (*config.ShootStatusLabelControllerConfiguration)(unsafe.Pointer(in.ShootStatusLabel))
	out.ManagedSeedSet = (*config.ManagedSeedSetControllerConfiguration)(unsafe.Pointer(in.ManagedSeedSet))
	return nil
}

// Convert_v1alpha1_ControllerManagerControllerConfiguration_To_config_ControllerManagerControllerConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_ControllerManagerControllerConfiguration_To_config_ControllerManagerControllerConfiguration(in *ControllerManagerControllerConfiguration, out *config.ControllerManagerControllerConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_ControllerManagerControllerConfiguration_To_config_ControllerManagerControllerConfiguration(in, out, s)
}

func autoConvert_config_ControllerManagerControllerConfiguration_To_v1alpha1_ControllerManagerControllerConfiguration(in *config.ControllerManagerControllerConfiguration, out *ControllerManagerControllerConfiguration, s conversion.Scope) error {
	out.Bastion = (*BastionControllerConfiguration)(unsafe.Pointer(in.Bastion))
	out.CertificateSigningRequest = (*CertificateSigningRequestControllerConfiguration)(unsafe.Pointer(in.CertificateSigningRequest))
	out.CloudProfile = (*CloudProfileControllerConfiguration)(unsafe.Pointer(in.CloudProfile))
	out.ControllerDeployment = (*ControllerDeploymentControllerConfiguration)(unsafe.Pointer(in.ControllerDeployment))
	out.ControllerRegistration = (*ControllerRegistrationControllerConfiguration)(unsafe.Pointer(in.ControllerRegistration))
	out.Event = (*EventControllerConfiguration)(unsafe.Pointer(in.Event))
	out.ExposureClass = (*ExposureClassControllerConfiguration)(unsafe.Pointer(in.ExposureClass))
	if in.Project != nil {
		in, out := &in.Project, &out.Project
		*out = new(ProjectControllerConfiguration)
		if err := Convert_config_ProjectControllerConfiguration_To_v1alpha1_ProjectControllerConfiguration(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.Project = nil
	}
	out.Quota = (*QuotaControllerConfiguration)(unsafe.Pointer(in.Quota))
	out.SecretBinding = (*SecretBindingControllerConfiguration)(unsafe.Pointer(in.SecretBinding))
	out.Seed = (*SeedControllerConfiguration)(unsafe.Pointer(in.Seed))
	out.SeedExtensionsCheck = (*SeedExtensionsCheckControllerConfiguration)(unsafe.Pointer(in.SeedExtensionsCheck))
	out.SeedBackupBucketsCheck = (*SeedBackupBucketsCheckControllerConfiguration)(unsafe.Pointer(in.SeedBackupBucketsCheck))
	if err := Convert_config_ShootMaintenanceControllerConfiguration_To_v1alpha1_ShootMaintenanceControllerConfiguration(&in.ShootMaintenance, &out.ShootMaintenance, s); err != nil {
		return err
	}
	out.ShootQuota = (*ShootQuotaControllerConfiguration)(unsafe.Pointer(in.ShootQuota))
	if err := Convert_config_ShootHibernationControllerConfiguration_To_v1alpha1_ShootHibernationControllerConfiguration(&in.ShootHibernation, &out.ShootHibernation, s); err != nil {
		return err
	}
	out.ShootReference = (*ShootReferenceControllerConfiguration)(unsafe.Pointer(in.ShootReference))
	out.ShootRetry = (*ShootRetryControllerConfiguration)(unsafe.Pointer(in.ShootRetry))
	out.ShootConditions = (*ShootConditionsControllerConfiguration)(unsafe.Pointer(in.ShootConditions))
	out.ShootStatusLabel = (*ShootStatusLabelControllerConfiguration)(unsafe.Pointer(in.ShootStatusLabel))
	out.ManagedSeedSet = (*ManagedSeedSetControllerConfiguration)(unsafe.Pointer(in.ManagedSeedSet))
	return nil
}

// Convert_config_ControllerManagerControllerConfiguration_To_v1alpha1_ControllerManagerControllerConfiguration is an autogenerated conversion function.
func Convert_config_ControllerManagerControllerConfiguration_To_v1alpha1_ControllerManagerControllerConfiguration(in *config.ControllerManagerControllerConfiguration, out *ControllerManagerControllerConfiguration, s conversion.Scope) error {
	return autoConvert_config_ControllerManagerControllerConfiguration_To_v1alpha1_ControllerManagerControllerConfiguration(in, out, s)
}

func autoConvert_v1alpha1_ControllerRegistrationControllerConfiguration_To_config_ControllerRegistrationControllerConfiguration(in *ControllerRegistrationControllerConfiguration, out *config.ControllerRegistrationControllerConfiguration, s conversion.Scope) error {
	out.ConcurrentSyncs = (*int)(unsafe.Pointer(in.ConcurrentSyncs))
	return nil
}

// Convert_v1alpha1_ControllerRegistrationControllerConfiguration_To_config_ControllerRegistrationControllerConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_ControllerRegistrationControllerConfiguration_To_config_ControllerRegistrationControllerConfiguration(in *ControllerRegistrationControllerConfiguration, out *config.ControllerRegistrationControllerConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_ControllerRegistrationControllerConfiguration_To_config_ControllerRegistrationControllerConfiguration(in, out, s)
}

func autoConvert_config_ControllerRegistrationControllerConfiguration_To_v1alpha1_ControllerRegistrationControllerConfiguration(in *config.ControllerRegistrationControllerConfiguration, out *ControllerRegistrationControllerConfiguration, s conversion.Scope) error {
	out.ConcurrentSyncs = (*int)(unsafe.Pointer(in.ConcurrentSyncs))
	return nil
}

// Convert_config_ControllerRegistrationControllerConfiguration_To_v1alpha1_ControllerRegistrationControllerConfiguration is an autogenerated conversion function.
func Convert_config_ControllerRegistrationControllerConfiguration_To_v1alpha1_ControllerRegistrationControllerConfiguration(in *config.ControllerRegistrationControllerConfiguration, out *ControllerRegistrationControllerConfiguration, s conversion.Scope) error {
	return autoConvert_config_ControllerRegistrationControllerConfiguration_To_v1alpha1_ControllerRegistrationControllerConfiguration(in, out, s)
}

func autoConvert_v1alpha1_EventControllerConfiguration_To_config_EventControllerConfiguration(in *EventControllerConfiguration, out *config.EventControllerConfiguration, s conversion.Scope) error {
	out.ConcurrentSyncs = (*int)(unsafe.Pointer(in.ConcurrentSyncs))
	out.TTLNonShootEvents = (*v1.Duration)(unsafe.Pointer(in.TTLNonShootEvents))
	return nil
}

// Convert_v1alpha1_EventControllerConfiguration_To_config_EventControllerConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_EventControllerConfiguration_To_config_EventControllerConfiguration(in *EventControllerConfiguration, out *config.EventControllerConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_EventControllerConfiguration_To_config_EventControllerConfiguration(in, out, s)
}

func autoConvert_config_EventControllerConfiguration_To_v1alpha1_EventControllerConfiguration(in *config.EventControllerConfiguration, out *EventControllerConfiguration, s conversion.Scope) error {
	out.ConcurrentSyncs = (*int)(unsafe.Pointer(in.ConcurrentSyncs))
	out.TTLNonShootEvents = (*v1.Duration)(unsafe.Pointer(in.TTLNonShootEvents))
	return nil
}

// Convert_config_EventControllerConfiguration_To_v1alpha1_EventControllerConfiguration is an autogenerated conversion function.
func Convert_config_EventControllerConfiguration_To_v1alpha1_EventControllerConfiguration(in *config.EventControllerConfiguration, out *EventControllerConfiguration, s conversion.Scope) error {
	return autoConvert_config_EventControllerConfiguration_To_v1alpha1_EventControllerConfiguration(in, out, s)
}

func autoConvert_v1alpha1_ExposureClassControllerConfiguration_To_config_ExposureClassControllerConfiguration(in *ExposureClassControllerConfiguration, out *config.ExposureClassControllerConfiguration, s conversion.Scope) error {
	out.ConcurrentSyncs = (*int)(unsafe.Pointer(in.ConcurrentSyncs))
	return nil
}

// Convert_v1alpha1_ExposureClassControllerConfiguration_To_config_ExposureClassControllerConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_ExposureClassControllerConfiguration_To_config_ExposureClassControllerConfiguration(in *ExposureClassControllerConfiguration, out *config.ExposureClassControllerConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_ExposureClassControllerConfiguration_To_config_ExposureClassControllerConfiguration(in, out, s)
}

func autoConvert_config_ExposureClassControllerConfiguration_To_v1alpha1_ExposureClassControllerConfiguration(in *config.ExposureClassControllerConfiguration, out *ExposureClassControllerConfiguration, s conversion.Scope) error {
	out.ConcurrentSyncs = (*int)(unsafe.Pointer(in.ConcurrentSyncs))
	return nil
}

// Convert_config_ExposureClassControllerConfiguration_To_v1alpha1_ExposureClassControllerConfiguration is an autogenerated conversion function.
func Convert_config_ExposureClassControllerConfiguration_To_v1alpha1_ExposureClassControllerConfiguration(in *config.ExposureClassControllerConfiguration, out *ExposureClassControllerConfiguration, s conversion.Scope) error {
	return autoConvert_config_ExposureClassControllerConfiguration_To_v1alpha1_ExposureClassControllerConfiguration(in, out, s)
}

func autoConvert_v1alpha1_ManagedSeedSetControllerConfiguration_To_config_ManagedSeedSetControllerConfiguration(in *ManagedSeedSetControllerConfiguration, out *config.ManagedSeedSetControllerConfiguration, s conversion.Scope) error {
	out.ConcurrentSyncs = (*int)(unsafe.Pointer(in.ConcurrentSyncs))
	out.MaxShootRetries = (*int)(unsafe.Pointer(in.MaxShootRetries))
	out.SyncPeriod = in.SyncPeriod
	return nil
}

// Convert_v1alpha1_ManagedSeedSetControllerConfiguration_To_config_ManagedSeedSetControllerConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_ManagedSeedSetControllerConfiguration_To_config_ManagedSeedSetControllerConfiguration(in *ManagedSeedSetControllerConfiguration, out *config.ManagedSeedSetControllerConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_ManagedSeedSetControllerConfiguration_To_config_ManagedSeedSetControllerConfiguration(in, out, s)
}

func autoConvert_config_ManagedSeedSetControllerConfiguration_To_v1alpha1_ManagedSeedSetControllerConfiguration(in *config.ManagedSeedSetControllerConfiguration, out *ManagedSeedSetControllerConfiguration, s conversion.Scope) error {
	out.ConcurrentSyncs = (*int)(unsafe.Pointer(in.ConcurrentSyncs))
	out.MaxShootRetries = (*int)(unsafe.Pointer(in.MaxShootRetries))
	out.SyncPeriod = in.SyncPeriod
	return nil
}

// Convert_config_ManagedSeedSetControllerConfiguration_To_v1alpha1_ManagedSeedSetControllerConfiguration is an autogenerated conversion function.
func Convert_config_ManagedSeedSetControllerConfiguration_To_v1alpha1_ManagedSeedSetControllerConfiguration(in *config.ManagedSeedSetControllerConfiguration, out *ManagedSeedSetControllerConfiguration, s conversion.Scope) error {
	return autoConvert_config_ManagedSeedSetControllerConfiguration_To_v1alpha1_ManagedSeedSetControllerConfiguration(in, out, s)
}

func autoConvert_v1alpha1_ProjectControllerConfiguration_To_config_ProjectControllerConfiguration(in *ProjectControllerConfiguration, out *config.ProjectControllerConfiguration, s conversion.Scope) error {
	out.ConcurrentSyncs = (*int)(unsafe.Pointer(in.ConcurrentSyncs))
	out.MinimumLifetimeDays = (*int)(unsafe.Pointer(in.MinimumLifetimeDays))
	if in.Quotas != nil {
		in, out := &in.Quotas, &out.Quotas
		*out = make([]config.QuotaConfiguration, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_QuotaConfiguration_To_config_QuotaConfiguration(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Quotas = nil
	}
	out.StaleGracePeriodDays = (*int)(unsafe.Pointer(in.StaleGracePeriodDays))
	out.StaleExpirationTimeDays = (*int)(unsafe.Pointer(in.StaleExpirationTimeDays))
	out.StaleSyncPeriod = (*v1.Duration)(unsafe.Pointer(in.StaleSyncPeriod))
	return nil
}

// Convert_v1alpha1_ProjectControllerConfiguration_To_config_ProjectControllerConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_ProjectControllerConfiguration_To_config_ProjectControllerConfiguration(in *ProjectControllerConfiguration, out *config.ProjectControllerConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProjectControllerConfiguration_To_config_ProjectControllerConfiguration(in, out, s)
}

func autoConvert_config_ProjectControllerConfiguration_To_v1alpha1_ProjectControllerConfiguration(in *config.ProjectControllerConfiguration, out *ProjectControllerConfiguration, s conversion.Scope) error {
	out.ConcurrentSyncs = (*int)(unsafe.Pointer(in.ConcurrentSyncs))
	out.MinimumLifetimeDays = (*int)(unsafe.Pointer(in.MinimumLifetimeDays))
	if in.Quotas != nil {
		in, out := &in.Quotas, &out.Quotas
		*out = make([]QuotaConfiguration, len(*in))
		for i := range *in {
			if err := Convert_config_QuotaConfiguration_To_v1alpha1_QuotaConfiguration(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Quotas = nil
	}
	out.StaleGracePeriodDays = (*int)(unsafe.Pointer(in.StaleGracePeriodDays))
	out.StaleExpirationTimeDays = (*int)(unsafe.Pointer(in.StaleExpirationTimeDays))
	out.StaleSyncPeriod = (*v1.Duration)(unsafe.Pointer(in.StaleSyncPeriod))
	return nil
}

// Convert_config_ProjectControllerConfiguration_To_v1alpha1_ProjectControllerConfiguration is an autogenerated conversion function.
func Convert_config_ProjectControllerConfiguration_To_v1alpha1_ProjectControllerConfiguration(in *config.ProjectControllerConfiguration, out *ProjectControllerConfiguration, s conversion.Scope) error {
	return autoConvert_config_ProjectControllerConfiguration_To_v1alpha1_ProjectControllerConfiguration(in, out, s)
}

func autoConvert_v1alpha1_QuotaConfiguration_To_config_QuotaConfiguration(in *QuotaConfiguration, out *config.QuotaConfiguration, s conversion.Scope) error {
	if err := runtime.Convert_runtime_RawExtension_To_runtime_Object(&in.Config, &out.Config, s); err != nil {
		return err
	}
	out.ProjectSelector = (*v1.LabelSelector)(unsafe.Pointer(in.ProjectSelector))
	return nil
}

func autoConvert_config_QuotaConfiguration_To_v1alpha1_QuotaConfiguration(in *config.QuotaConfiguration, out *QuotaConfiguration, s conversion.Scope) error {
	if err := runtime.Convert_runtime_Object_To_runtime_RawExtension(&in.Config, &out.Config, s); err != nil {
		return err
	}
	out.ProjectSelector = (*v1.LabelSelector)(unsafe.Pointer(in.ProjectSelector))
	return nil
}

// Convert_config_QuotaConfiguration_To_v1alpha1_QuotaConfiguration is an autogenerated conversion function.
func Convert_config_QuotaConfiguration_To_v1alpha1_QuotaConfiguration(in *config.QuotaConfiguration, out *QuotaConfiguration, s conversion.Scope) error {
	return autoConvert_config_QuotaConfiguration_To_v1alpha1_QuotaConfiguration(in, out, s)
}

func autoConvert_v1alpha1_QuotaControllerConfiguration_To_config_QuotaControllerConfiguration(in *QuotaControllerConfiguration, out *config.QuotaControllerConfiguration, s conversion.Scope) error {
	out.ConcurrentSyncs = (*int)(unsafe.Pointer(in.ConcurrentSyncs))
	return nil
}

// Convert_v1alpha1_QuotaControllerConfiguration_To_config_QuotaControllerConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_QuotaControllerConfiguration_To_config_QuotaControllerConfiguration(in *QuotaControllerConfiguration, out *config.QuotaControllerConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_QuotaControllerConfiguration_To_config_QuotaControllerConfiguration(in, out, s)
}

func autoConvert_config_QuotaControllerConfiguration_To_v1alpha1_QuotaControllerConfiguration(in *config.QuotaControllerConfiguration, out *QuotaControllerConfiguration, s conversion.Scope) error {
	out.ConcurrentSyncs = (*int)(unsafe.Pointer(in.ConcurrentSyncs))
	return nil
}

// Convert_config_QuotaControllerConfiguration_To_v1alpha1_QuotaControllerConfiguration is an autogenerated conversion function.
func Convert_config_QuotaControllerConfiguration_To_v1alpha1_QuotaControllerConfiguration(in *config.QuotaControllerConfiguration, out *QuotaControllerConfiguration, s conversion.Scope) error {
	return autoConvert_config_QuotaControllerConfiguration_To_v1alpha1_QuotaControllerConfiguration(in, out, s)
}

func autoConvert_v1alpha1_SecretBindingControllerConfiguration_To_config_SecretBindingControllerConfiguration(in *SecretBindingControllerConfiguration, out *config.SecretBindingControllerConfiguration, s conversion.Scope) error {
	out.ConcurrentSyncs = (*int)(unsafe.Pointer(in.ConcurrentSyncs))
	return nil
}

// Convert_v1alpha1_SecretBindingControllerConfiguration_To_config_SecretBindingControllerConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_SecretBindingControllerConfiguration_To_config_SecretBindingControllerConfiguration(in *SecretBindingControllerConfiguration, out *config.SecretBindingControllerConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_SecretBindingControllerConfiguration_To_config_SecretBindingControllerConfiguration(in, out, s)
}

func autoConvert_config_SecretBindingControllerConfiguration_To_v1alpha1_SecretBindingControllerConfiguration(in *config.SecretBindingControllerConfiguration, out *SecretBindingControllerConfiguration, s conversion.Scope) error {
	out.ConcurrentSyncs = (*int)(unsafe.Pointer(in.ConcurrentSyncs))
	return nil
}

// Convert_config_SecretBindingControllerConfiguration_To_v1alpha1_SecretBindingControllerConfiguration is an autogenerated conversion function.
func Convert_config_SecretBindingControllerConfiguration_To_v1alpha1_SecretBindingControllerConfiguration(in *config.SecretBindingControllerConfiguration, out *SecretBindingControllerConfiguration, s conversion.Scope) error {
	return autoConvert_config_SecretBindingControllerConfiguration_To_v1alpha1_SecretBindingControllerConfiguration(in, out, s)
}

func autoConvert_v1alpha1_SeedBackupBucketsCheckControllerConfiguration_To_config_SeedBackupBucketsCheckControllerConfiguration(in *SeedBackupBucketsCheckControllerConfiguration, out *config.SeedBackupBucketsCheckControllerConfiguration, s conversion.Scope) error {
	out.ConcurrentSyncs = (*int)(unsafe.Pointer(in.ConcurrentSyncs))
	out.SyncPeriod = (*v1.Duration)(unsafe.Pointer(in.SyncPeriod))
	out.ConditionThresholds = *(*[]config.ConditionThreshold)(unsafe.Pointer(&in.ConditionThresholds))
	return nil
}

// Convert_v1alpha1_SeedBackupBucketsCheckControllerConfiguration_To_config_SeedBackupBucketsCheckControllerConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_SeedBackupBucketsCheckControllerConfiguration_To_config_SeedBackupBucketsCheckControllerConfiguration(in *SeedBackupBucketsCheckControllerConfiguration, out *config.SeedBackupBucketsCheckControllerConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_SeedBackupBucketsCheckControllerConfiguration_To_config_SeedBackupBucketsCheckControllerConfiguration(in, out, s)
}

func autoConvert_config_SeedBackupBucketsCheckControllerConfiguration_To_v1alpha1_SeedBackupBucketsCheckControllerConfiguration(in *config.SeedBackupBucketsCheckControllerConfiguration, out *SeedBackupBucketsCheckControllerConfiguration, s conversion.Scope) error {
	out.ConcurrentSyncs = (*int)(unsafe.Pointer(in.ConcurrentSyncs))
	out.SyncPeriod = (*v1.Duration)(unsafe.Pointer(in.SyncPeriod))
	out.ConditionThresholds = *(*[]ConditionThreshold)(unsafe.Pointer(&in.ConditionThresholds))
	return nil
}

// Convert_config_SeedBackupBucketsCheckControllerConfiguration_To_v1alpha1_SeedBackupBucketsCheckControllerConfiguration is an autogenerated conversion function.
func Convert_config_SeedBackupBucketsCheckControllerConfiguration_To_v1alpha1_SeedBackupBucketsCheckControllerConfiguration(in *config.SeedBackupBucketsCheckControllerConfiguration, out *SeedBackupBucketsCheckControllerConfiguration, s conversion.Scope) error {
	return autoConvert_config_SeedBackupBucketsCheckControllerConfiguration_To_v1alpha1_SeedBackupBucketsCheckControllerConfiguration(in, out, s)
}

func autoConvert_v1alpha1_SeedControllerConfiguration_To_config_SeedControllerConfiguration(in *SeedControllerConfiguration, out *config.SeedControllerConfiguration, s conversion.Scope) error {
	out.ConcurrentSyncs = (*int)(unsafe.Pointer(in.ConcurrentSyncs))
	out.MonitorPeriod = (*v1.Duration)(unsafe.Pointer(in.MonitorPeriod))
	out.ShootMonitorPeriod = (*v1.Duration)(unsafe.Pointer(in.ShootMonitorPeriod))
	out.SyncPeriod = (*v1.Duration)(unsafe.Pointer(in.SyncPeriod))
	return nil
}

// Convert_v1alpha1_SeedControllerConfiguration_To_config_SeedControllerConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_SeedControllerConfiguration_To_config_SeedControllerConfiguration(in *SeedControllerConfiguration, out *config.SeedControllerConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_SeedControllerConfiguration_To_config_SeedControllerConfiguration(in, out, s)
}

func autoConvert_config_SeedControllerConfiguration_To_v1alpha1_SeedControllerConfiguration(in *config.SeedControllerConfiguration, out *SeedControllerConfiguration, s conversion.Scope) error {
	out.ConcurrentSyncs = (*int)(unsafe.Pointer(in.ConcurrentSyncs))
	out.MonitorPeriod = (*v1.Duration)(unsafe.Pointer(in.MonitorPeriod))
	out.ShootMonitorPeriod = (*v1.Duration)(unsafe.Pointer(in.ShootMonitorPeriod))
	out.SyncPeriod = (*v1.Duration)(unsafe.Pointer(in.SyncPeriod))
	return nil
}

// Convert_config_SeedControllerConfiguration_To_v1alpha1_SeedControllerConfiguration is an autogenerated conversion function.
func Convert_config_SeedControllerConfiguration_To_v1alpha1_SeedControllerConfiguration(in *config.SeedControllerConfiguration, out *SeedControllerConfiguration, s conversion.Scope) error {
	return autoConvert_config_SeedControllerConfiguration_To_v1alpha1_SeedControllerConfiguration(in, out, s)
}

func autoConvert_v1alpha1_SeedExtensionsCheckControllerConfiguration_To_config_SeedExtensionsCheckControllerConfiguration(in *SeedExtensionsCheckControllerConfiguration, out *config.SeedExtensionsCheckControllerConfiguration, s conversion.Scope) error {
	out.ConcurrentSyncs = (*int)(unsafe.Pointer(in.ConcurrentSyncs))
	out.SyncPeriod = (*v1.Duration)(unsafe.Pointer(in.SyncPeriod))
	out.ConditionThresholds = *(*[]config.ConditionThreshold)(unsafe.Pointer(&in.ConditionThresholds))
	return nil
}

// Convert_v1alpha1_SeedExtensionsCheckControllerConfiguration_To_config_SeedExtensionsCheckControllerConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_SeedExtensionsCheckControllerConfiguration_To_config_SeedExtensionsCheckControllerConfiguration(in *SeedExtensionsCheckControllerConfiguration, out *config.SeedExtensionsCheckControllerConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_SeedExtensionsCheckControllerConfiguration_To_config_SeedExtensionsCheckControllerConfiguration(in, out, s)
}

func autoConvert_config_SeedExtensionsCheckControllerConfiguration_To_v1alpha1_SeedExtensionsCheckControllerConfiguration(in *config.SeedExtensionsCheckControllerConfiguration, out *SeedExtensionsCheckControllerConfiguration, s conversion.Scope) error {
	out.ConcurrentSyncs = (*int)(unsafe.Pointer(in.ConcurrentSyncs))
	out.SyncPeriod = (*v1.Duration)(unsafe.Pointer(in.SyncPeriod))
	out.ConditionThresholds = *(*[]ConditionThreshold)(unsafe.Pointer(&in.ConditionThresholds))
	return nil
}

// Convert_config_SeedExtensionsCheckControllerConfiguration_To_v1alpha1_SeedExtensionsCheckControllerConfiguration is an autogenerated conversion function.
func Convert_config_SeedExtensionsCheckControllerConfiguration_To_v1alpha1_SeedExtensionsCheckControllerConfiguration(in *config.SeedExtensionsCheckControllerConfiguration, out *SeedExtensionsCheckControllerConfiguration, s conversion.Scope) error {
	return autoConvert_config_SeedExtensionsCheckControllerConfiguration_To_v1alpha1_SeedExtensionsCheckControllerConfiguration(in, out, s)
}

func autoConvert_v1alpha1_Server_To_config_Server(in *Server, out *config.Server, s conversion.Scope) error {
	out.BindAddress = in.BindAddress
	out.Port = in.Port
	return nil
}

// Convert_v1alpha1_Server_To_config_Server is an autogenerated conversion function.
func Convert_v1alpha1_Server_To_config_Server(in *Server, out *config.Server, s conversion.Scope) error {
	return autoConvert_v1alpha1_Server_To_config_Server(in, out, s)
}

func autoConvert_config_Server_To_v1alpha1_Server(in *config.Server, out *Server, s conversion.Scope) error {
	out.BindAddress = in.BindAddress
	out.Port = in.Port
	return nil
}

// Convert_config_Server_To_v1alpha1_Server is an autogenerated conversion function.
func Convert_config_Server_To_v1alpha1_Server(in *config.Server, out *Server, s conversion.Scope) error {
	return autoConvert_config_Server_To_v1alpha1_Server(in, out, s)
}

func autoConvert_v1alpha1_ServerConfiguration_To_config_ServerConfiguration(in *ServerConfiguration, out *config.ServerConfiguration, s conversion.Scope) error {
	out.HealthProbes = (*config.Server)(unsafe.Pointer(in.HealthProbes))
	out.Metrics = (*config.Server)(unsafe.Pointer(in.Metrics))
	return nil
}

// Convert_v1alpha1_ServerConfiguration_To_config_ServerConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_ServerConfiguration_To_config_ServerConfiguration(in *ServerConfiguration, out *config.ServerConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_ServerConfiguration_To_config_ServerConfiguration(in, out, s)
}

func autoConvert_config_ServerConfiguration_To_v1alpha1_ServerConfiguration(in *config.ServerConfiguration, out *ServerConfiguration, s conversion.Scope) error {
	out.HealthProbes = (*Server)(unsafe.Pointer(in.HealthProbes))
	out.Metrics = (*Server)(unsafe.Pointer(in.Metrics))
	return nil
}

// Convert_config_ServerConfiguration_To_v1alpha1_ServerConfiguration is an autogenerated conversion function.
func Convert_config_ServerConfiguration_To_v1alpha1_ServerConfiguration(in *config.ServerConfiguration, out *ServerConfiguration, s conversion.Scope) error {
	return autoConvert_config_ServerConfiguration_To_v1alpha1_ServerConfiguration(in, out, s)
}

func autoConvert_v1alpha1_ShootConditionsControllerConfiguration_To_config_ShootConditionsControllerConfiguration(in *ShootConditionsControllerConfiguration, out *config.ShootConditionsControllerConfiguration, s conversion.Scope) error {
	out.ConcurrentSyncs = (*int)(unsafe.Pointer(in.ConcurrentSyncs))
	return nil
}

// Convert_v1alpha1_ShootConditionsControllerConfiguration_To_config_ShootConditionsControllerConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_ShootConditionsControllerConfiguration_To_config_ShootConditionsControllerConfiguration(in *ShootConditionsControllerConfiguration, out *config.ShootConditionsControllerConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_ShootConditionsControllerConfiguration_To_config_ShootConditionsControllerConfiguration(in, out, s)
}

func autoConvert_config_ShootConditionsControllerConfiguration_To_v1alpha1_ShootConditionsControllerConfiguration(in *config.ShootConditionsControllerConfiguration, out *ShootConditionsControllerConfiguration, s conversion.Scope) error {
	out.ConcurrentSyncs = (*int)(unsafe.Pointer(in.ConcurrentSyncs))
	return nil
}

// Convert_config_ShootConditionsControllerConfiguration_To_v1alpha1_ShootConditionsControllerConfiguration is an autogenerated conversion function.
func Convert_config_ShootConditionsControllerConfiguration_To_v1alpha1_ShootConditionsControllerConfiguration(in *config.ShootConditionsControllerConfiguration, out *ShootConditionsControllerConfiguration, s conversion.Scope) error {
	return autoConvert_config_ShootConditionsControllerConfiguration_To_v1alpha1_ShootConditionsControllerConfiguration(in, out, s)
}

func autoConvert_v1alpha1_ShootHibernationControllerConfiguration_To_config_ShootHibernationControllerConfiguration(in *ShootHibernationControllerConfiguration, out *config.ShootHibernationControllerConfiguration, s conversion.Scope) error {
	out.ConcurrentSyncs = (*int)(unsafe.Pointer(in.ConcurrentSyncs))
	out.TriggerDeadlineDuration = (*v1.Duration)(unsafe.Pointer(in.TriggerDeadlineDuration))
	return nil
}

// Convert_v1alpha1_ShootHibernationControllerConfiguration_To_config_ShootHibernationControllerConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_ShootHibernationControllerConfiguration_To_config_ShootHibernationControllerConfiguration(in *ShootHibernationControllerConfiguration, out *config.ShootHibernationControllerConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_ShootHibernationControllerConfiguration_To_config_ShootHibernationControllerConfiguration(in, out, s)
}

func autoConvert_config_ShootHibernationControllerConfiguration_To_v1alpha1_ShootHibernationControllerConfiguration(in *config.ShootHibernationControllerConfiguration, out *ShootHibernationControllerConfiguration, s conversion.Scope) error {
	out.ConcurrentSyncs = (*int)(unsafe.Pointer(in.ConcurrentSyncs))
	out.TriggerDeadlineDuration = (*v1.Duration)(unsafe.Pointer(in.TriggerDeadlineDuration))
	return nil
}

// Convert_config_ShootHibernationControllerConfiguration_To_v1alpha1_ShootHibernationControllerConfiguration is an autogenerated conversion function.
func Convert_config_ShootHibernationControllerConfiguration_To_v1alpha1_ShootHibernationControllerConfiguration(in *config.ShootHibernationControllerConfiguration, out *ShootHibernationControllerConfiguration, s conversion.Scope) error {
	return autoConvert_config_ShootHibernationControllerConfiguration_To_v1alpha1_ShootHibernationControllerConfiguration(in, out, s)
}

func autoConvert_v1alpha1_ShootMaintenanceControllerConfiguration_To_config_ShootMaintenanceControllerConfiguration(in *ShootMaintenanceControllerConfiguration, out *config.ShootMaintenanceControllerConfiguration, s conversion.Scope) error {
	out.ConcurrentSyncs = (*int)(unsafe.Pointer(in.ConcurrentSyncs))
	out.EnableShootControlPlaneRestarter = (*bool)(unsafe.Pointer(in.EnableShootControlPlaneRestarter))
	out.EnableShootCoreAddonRestarter = (*bool)(unsafe.Pointer(in.EnableShootCoreAddonRestarter))
	return nil
}

// Convert_v1alpha1_ShootMaintenanceControllerConfiguration_To_config_ShootMaintenanceControllerConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_ShootMaintenanceControllerConfiguration_To_config_ShootMaintenanceControllerConfiguration(in *ShootMaintenanceControllerConfiguration, out *config.ShootMaintenanceControllerConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_ShootMaintenanceControllerConfiguration_To_config_ShootMaintenanceControllerConfiguration(in, out, s)
}

func autoConvert_config_ShootMaintenanceControllerConfiguration_To_v1alpha1_ShootMaintenanceControllerConfiguration(in *config.ShootMaintenanceControllerConfiguration, out *ShootMaintenanceControllerConfiguration, s conversion.Scope) error {
	out.ConcurrentSyncs = (*int)(unsafe.Pointer(in.ConcurrentSyncs))
	out.EnableShootControlPlaneRestarter = (*bool)(unsafe.Pointer(in.EnableShootControlPlaneRestarter))
	out.EnableShootCoreAddonRestarter = (*bool)(unsafe.Pointer(in.EnableShootCoreAddonRestarter))
	return nil
}

// Convert_config_ShootMaintenanceControllerConfiguration_To_v1alpha1_ShootMaintenanceControllerConfiguration is an autogenerated conversion function.
func Convert_config_ShootMaintenanceControllerConfiguration_To_v1alpha1_ShootMaintenanceControllerConfiguration(in *config.ShootMaintenanceControllerConfiguration, out *ShootMaintenanceControllerConfiguration, s conversion.Scope) error {
	return autoConvert_config_ShootMaintenanceControllerConfiguration_To_v1alpha1_ShootMaintenanceControllerConfiguration(in, out, s)
}

func autoConvert_v1alpha1_ShootQuotaControllerConfiguration_To_config_ShootQuotaControllerConfiguration(in *ShootQuotaControllerConfiguration, out *config.ShootQuotaControllerConfiguration, s conversion.Scope) error {
	out.ConcurrentSyncs = (*int)(unsafe.Pointer(in.ConcurrentSyncs))
	out.SyncPeriod = (*v1.Duration)(unsafe.Pointer(in.SyncPeriod))
	return nil
}

// Convert_v1alpha1_ShootQuotaControllerConfiguration_To_config_ShootQuotaControllerConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_ShootQuotaControllerConfiguration_To_config_ShootQuotaControllerConfiguration(in *ShootQuotaControllerConfiguration, out *config.ShootQuotaControllerConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_ShootQuotaControllerConfiguration_To_config_ShootQuotaControllerConfiguration(in, out, s)
}

func autoConvert_config_ShootQuotaControllerConfiguration_To_v1alpha1_ShootQuotaControllerConfiguration(in *config.ShootQuotaControllerConfiguration, out *ShootQuotaControllerConfiguration, s conversion.Scope) error {
	out.ConcurrentSyncs = (*int)(unsafe.Pointer(in.ConcurrentSyncs))
	out.SyncPeriod = (*v1.Duration)(unsafe.Pointer(in.SyncPeriod))
	return nil
}

// Convert_config_ShootQuotaControllerConfiguration_To_v1alpha1_ShootQuotaControllerConfiguration is an autogenerated conversion function.
func Convert_config_ShootQuotaControllerConfiguration_To_v1alpha1_ShootQuotaControllerConfiguration(in *config.ShootQuotaControllerConfiguration, out *ShootQuotaControllerConfiguration, s conversion.Scope) error {
	return autoConvert_config_ShootQuotaControllerConfiguration_To_v1alpha1_ShootQuotaControllerConfiguration(in, out, s)
}

func autoConvert_v1alpha1_ShootReferenceControllerConfiguration_To_config_ShootReferenceControllerConfiguration(in *ShootReferenceControllerConfiguration, out *config.ShootReferenceControllerConfiguration, s conversion.Scope) error {
	out.ConcurrentSyncs = (*int)(unsafe.Pointer(in.ConcurrentSyncs))
	return nil
}

// Convert_v1alpha1_ShootReferenceControllerConfiguration_To_config_ShootReferenceControllerConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_ShootReferenceControllerConfiguration_To_config_ShootReferenceControllerConfiguration(in *ShootReferenceControllerConfiguration, out *config.ShootReferenceControllerConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_ShootReferenceControllerConfiguration_To_config_ShootReferenceControllerConfiguration(in, out, s)
}

func autoConvert_config_ShootReferenceControllerConfiguration_To_v1alpha1_ShootReferenceControllerConfiguration(in *config.ShootReferenceControllerConfiguration, out *ShootReferenceControllerConfiguration, s conversion.Scope) error {
	out.ConcurrentSyncs = (*int)(unsafe.Pointer(in.ConcurrentSyncs))
	return nil
}

// Convert_config_ShootReferenceControllerConfiguration_To_v1alpha1_ShootReferenceControllerConfiguration is an autogenerated conversion function.
func Convert_config_ShootReferenceControllerConfiguration_To_v1alpha1_ShootReferenceControllerConfiguration(in *config.ShootReferenceControllerConfiguration, out *ShootReferenceControllerConfiguration, s conversion.Scope) error {
	return autoConvert_config_ShootReferenceControllerConfiguration_To_v1alpha1_ShootReferenceControllerConfiguration(in, out, s)
}

func autoConvert_v1alpha1_ShootRetryControllerConfiguration_To_config_ShootRetryControllerConfiguration(in *ShootRetryControllerConfiguration, out *config.ShootRetryControllerConfiguration, s conversion.Scope) error {
	out.ConcurrentSyncs = (*int)(unsafe.Pointer(in.ConcurrentSyncs))
	out.RetryPeriod = (*v1.Duration)(unsafe.Pointer(in.RetryPeriod))
	out.RetryJitterPeriod = (*v1.Duration)(unsafe.Pointer(in.RetryJitterPeriod))
	return nil
}

// Convert_v1alpha1_ShootRetryControllerConfiguration_To_config_ShootRetryControllerConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_ShootRetryControllerConfiguration_To_config_ShootRetryControllerConfiguration(in *ShootRetryControllerConfiguration, out *config.ShootRetryControllerConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_ShootRetryControllerConfiguration_To_config_ShootRetryControllerConfiguration(in, out, s)
}

func autoConvert_config_ShootRetryControllerConfiguration_To_v1alpha1_ShootRetryControllerConfiguration(in *config.ShootRetryControllerConfiguration, out *ShootRetryControllerConfiguration, s conversion.Scope) error {
	out.ConcurrentSyncs = (*int)(unsafe.Pointer(in.ConcurrentSyncs))
	out.RetryPeriod = (*v1.Duration)(unsafe.Pointer(in.RetryPeriod))
	out.RetryJitterPeriod = (*v1.Duration)(unsafe.Pointer(in.RetryJitterPeriod))
	return nil
}

// Convert_config_ShootRetryControllerConfiguration_To_v1alpha1_ShootRetryControllerConfiguration is an autogenerated conversion function.
func Convert_config_ShootRetryControllerConfiguration_To_v1alpha1_ShootRetryControllerConfiguration(in *config.ShootRetryControllerConfiguration, out *ShootRetryControllerConfiguration, s conversion.Scope) error {
	return autoConvert_config_ShootRetryControllerConfiguration_To_v1alpha1_ShootRetryControllerConfiguration(in, out, s)
}

func autoConvert_v1alpha1_ShootStatusLabelControllerConfiguration_To_config_ShootStatusLabelControllerConfiguration(in *ShootStatusLabelControllerConfiguration, out *config.ShootStatusLabelControllerConfiguration, s conversion.Scope) error {
	out.ConcurrentSyncs = (*int)(unsafe.Pointer(in.ConcurrentSyncs))
	return nil
}

// Convert_v1alpha1_ShootStatusLabelControllerConfiguration_To_config_ShootStatusLabelControllerConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_ShootStatusLabelControllerConfiguration_To_config_ShootStatusLabelControllerConfiguration(in *ShootStatusLabelControllerConfiguration, out *config.ShootStatusLabelControllerConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_ShootStatusLabelControllerConfiguration_To_config_ShootStatusLabelControllerConfiguration(in, out, s)
}

func autoConvert_config_ShootStatusLabelControllerConfiguration_To_v1alpha1_ShootStatusLabelControllerConfiguration(in *config.ShootStatusLabelControllerConfiguration, out *ShootStatusLabelControllerConfiguration, s conversion.Scope) error {
	out.ConcurrentSyncs = (*int)(unsafe.Pointer(in.ConcurrentSyncs))
	return nil
}

// Convert_config_ShootStatusLabelControllerConfiguration_To_v1alpha1_ShootStatusLabelControllerConfiguration is an autogenerated conversion function.
func Convert_config_ShootStatusLabelControllerConfiguration_To_v1alpha1_ShootStatusLabelControllerConfiguration(in *config.ShootStatusLabelControllerConfiguration, out *ShootStatusLabelControllerConfiguration, s conversion.Scope) error {
	return autoConvert_config_ShootStatusLabelControllerConfiguration_To_v1alpha1_ShootStatusLabelControllerConfiguration(in, out, s)
}
