{
 "title": "CoreDNS",
 "tags": [
  "network",
  "shoot"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "CoreDNS Pod",
    "query": {
     "query": "label_values(coredns_build_info, pod)"
    }
   },
   {
    "name": "service_kind",
    "query": {
     "query": "label_values(coredns_kubernetes_dns_programming_duration_seconds_count,service_kind)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DNS Requests",
   "type": "graph",
   "description": "Rate of DNS Requests received by CoreDNS.\n\nNote: The `dot` zone is the local zone managed by the CoreDNS instance.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total{pod=~\"$pod\"}[$__rate_interval])) by (exported_type)",
     "legendFormat": "By Record: {{exported_type}}"
    },
    {
     "expr": "sum(rate(coredns_dns_requests_total{pod=~\"$pod\"}[$__rate_interval])) by (proto)",
     "legendFormat": "By Protocol: {{proto}}"
    },
    {
     "expr": "sum(rate(coredns_dns_requests_total{pod=~\"$pod\"}[$__rate_interval])) by (zone)",
     "legendFormat": "By Zone: {{zone}}"
    }
   ]
  },
  {
   "title": "DNS Responses",
   "type": "graph",
   "description": "The average per second rate of lookup requests split by their status codes (rcode).",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_responses_total{pod=~\"$pod\"}[$__rate_interval])) by (rcode)",
     "legendFormat": "{{rcode}}"
    }
   ]
  },
  {
   "title": "DNS Requests Latency",
   "type": "graph",
   "description": "DNS Requests Latency in seconds",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum(rate(coredns_dns_request_duration_seconds_bucket{pod=~\"$pod\"}[$__rate_interval])) by (le, zone))",
     "legendFormat": "{{zone}} 99%"
    }
   ]
  },
  {
   "title": "DNS Requests Latency Heatmap",
   "type": "heatmap",
   "description": "DNS Requests Latency in seconds",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum by (le) (rate(coredns_dns_request_duration_seconds_bucket{pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Cache Hits and Misses",
   "type": "graph",
   "description": "The `cache hits` describes how many DNS requests were answered due to a cached entry.\n\nThe `cache misses` describes how many DNS requests need to be looked up, because the requests entry does not exist in the local cache.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_cache_hits_total{pod=~\"$pod\"}[$__rate_interval])) by(exported_type)",
     "legendFormat": "cache hits {{exported_type}}"
    },
    {
     "expr": "sum(rate(coredns_cache_misses_total{pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "cache misses"
    }
   ]
  },
  {
   "title": "Cache Size",
   "type": "graph",
   "description": "Count of cached entries in the cache of the DNS.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(coredns_cache_entries{pod=~\"$pod\"}) by (exported_type, zones)",
     "legendFormat": "{{exported_type}} {{zones}}"
    }
   ]
  },
  { "title": "Upstream DNS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Upstream DNS Requests",
   "type": "graph",
   "description": "Average request per second made to upstream DNS.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_proxy_request_duration_seconds_count{pod=~\"$pod\", proxy_name=\"forward\"}[$__rate_interval])) by (to)",
     "legendFormat": "{{to}}"
    }
   ]
  },
  {
   "title": "Upstream DNS Forward Responses Per Interval",
   "type": "graph",
   "description": "DNS forward responses per interval from upstream DNS split by status code (rcode).",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(coredns_proxy_request_duration_seconds_count{pod=~\"$pod\", proxy_name=\"forward\"} - coredns_proxy_request_duration_seconds_count{pod=~\"$pod\", proxy_name=\"forward\"} offset $__interval) by (to,rcode)",
     "legendFormat": "{{rcode}}  ({{to}})"
    }
   ]
  },
  {
   "title": "Upstream DNS Responses",
   "type": "graph",
   "description": "Average per second rate of responses from upstream DNS split by status code (rcode).",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(coredns_proxy_request_duration_seconds_count{pod=~\"$pod\", proxy_name=\"forward\"}[$__rate_interval])",
     "legendFormat": "{{rcode}} ({{to}})"
    }
   ]
  },
  {
   "title": "DNS Programming Latency ($service_kind)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "repeat": "service_kind"
  },
  {
   "title": "Rate of DNS Programming Events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "rate(coredns_kubernetes_dns_programming_duration_seconds_count{pod=~\"$pod\", service_kind=~\"$service_kind\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Increase in DNS Programming Seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 52 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(coredns_kubernetes_dns_programming_duration_seconds_sum{pod=~\"$pod\", service_kind=~\"$service_kind\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "DNS Programming Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "sum by (le) (rate(coredns_kubernetes_dns_programming_duration_seconds_bucket{pod=~\"$pod\", service_kind=~\"$service_kind\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}