{
 "title": "Kubernetes Control Plane Status",
 "tags": [
  "controlplane",
  "seed"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Number of nodes",
   "type": "singlestat",
   "description": "The current number of nodes in the cluster.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count(kube_node_info)" }
   ]
  },
  {
   "title": "API Servers UP",
   "type": "singlestat",
   "description": "Current uptime status of the kube apiservers.",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(up{job=\"kube-apiserver\"} == 1) / sum(up{job=\"kube-apiserver\"})) * 100"
    }
   ]
  },
  {
   "title": "Kube Controller Managers UP",
   "type": "singlestat",
   "description": "Current uptime status of the kube controller managers.",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(up{job=\"kube-controller-manager\"} == 1) / sum(up{job=\"kube-controller-manager\"})) * 100"
    }
   ]
  },
  {
   "title": "Schedulers UP",
   "type": "singlestat",
   "description": "Current uptime status of the kube schedulers.",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(up{job=\"kube-scheduler\"} == 1) / sum(up{job=\"kube-scheduler\"})) * 100"
    }
   ]
  },
  {
   "title": "API Server Request Error Rate",
   "type": "singlestat",
   "description": "Current kube-apiservers error request rate.",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(sum by(instance) (rate(apiserver_request_total{code=~\"5..\"}[$__rate_interval])) / sum by(instance) (rate(apiserver_request_total[$__rate_interval]))) * 100"
    }
   ]
  },
  { "title": "API Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "API Server Connectivity",
   "type": "text",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "options": {
    "content": "# Connectivity\n\n## Shoot\n\nShoot connectivity checks if the API Server is available from the shoot cluster. This is done via the blackbox exporter running in the shoot.\n\n## Seed\n\nSeed connectivity checks if the API Server is available from the seed. Prometheus tries to access the API Server via the external fully qualified domain name of the API server. \n\nFor more information check the [documentation](https://github.com/gardener/gardener/blob/master/docs/monitoring/connectivity.md)"
   }
  },
  {
   "title": "API Server Connectivity",
   "type": "graph",
   "description": "Checks the connection to the API Server from the seed and from the shoot (via loadbalancer).\n\n0 = down; 1 = up\n\n[Documentation](https://github.com/gardener/gardener/blob/master/docs/monitoring/connectivity.md)",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "none", "label": "Up" }
   ],
   "targets": [
    {
     "expr": "probe_success{job=~\"blackbox-apiserver|blackbox-exporter-k8s-service-check\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Kube API Server CPU usage",
   "type": "graph",
   "description": "Shows the CPU usage of the Kube API Server and shows the requests and limits.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"kube-apiserver-(.+)\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}-current"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\", pod=~\"kube-apiserver-(.+)\"}) by (pod)",
     "legendFormat": "{{pod}}-limits"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\", pod=~\"kube-apiserver-(.+)\"}) by (pod)",
     "legendFormat": "{{pod}}-requests"
    }
   ]
  },
  {
   "title": "Kube API Server Memory Usage",
   "type": "graph",
   "description": "Shows the memory usage of the Kube API Server.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"kube-apiserver-(.+)\"}) by (pod)",
     "legendFormat": "{{pod}}-current"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\", pod=~\"kube-apiserver-(.+)\"}) by (pod)",
     "legendFormat": "{{pod}}-limits"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\", pod=~\"kube-apiserver-(.+)\"}) by (pod)",
     "legendFormat": "{{pod}}-requests"
    }
   ]
  },
  {
   "title": "API Server Request Rates",
   "type": "graph",
   "description": "Shows the rate of all API server requests and the error rate of API server requests. Requests are the average rate of requests received in the past 5 minutes.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "requests/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{code=~\"5..\"}[$__rate_interval]))",
     "legendFormat": "Error Rate"
    },
    {
     "expr": "sum(rate(apiserver_request_total[$__rate_interval]))",
     "legendFormat": "Request Rate"
    }
   ]
  },
  {
   "title": "API Server Request Latency p99",
   "type": "graph",
   "description": "Shows the request latency of each verb for the API server.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "max by(verb) (shoot:apiserver_latency_seconds:quantile{quantile=\"0.99\"})",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "Etcd DB Size",
   "type": "graph",
   "description": "Shows the size of the ETCD DB",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "etcd_mvcc_db_total_size_in_bytes",
     "legendFormat": "etcd-{{role}} db size"
    }
   ]
  },
  {
   "title": "API Resources",
   "type": "graph",
   "description": "Shows the number of API Resources that are in the cluster.",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(etcd_object_counts) by (resource) or max(apiserver_storage_objects) by (resource)",
     "legendFormat": "{{resource}}"
    },
    {
     "expr": "sum(max(etcd_object_counts) by (resource)) or sum(max(apiserver_storage_objects) by (resource))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "API Server Watches",
   "type": "graph",
   "description": "Count of registered API Server watches split by watched resources. \n\nHigh number of watches can lead to performance issues of the API Server and the underlying ETCD.\n\nNote: **group** is a reference for the default k8s api group.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "Count Watches" }
   ],
   "targets": [
    {
     "expr": "    sum by (group, version, kind) (apiserver_registered_watchers)\n  + on () group_left ()\n    absent(apiserver_longrunning_requests) * 0\nor\n  sum by (group, version, resource) (apiserver_longrunning_requests)",
     "legendFormat": "{{group}}/{{version}}/{{resource}}{{kind}}"
    },
    {
     "expr": "sum(\n      sum by (group, version, kind) (apiserver_registered_watchers)\n    + on () group_left ()\n      absent(apiserver_longrunning_requests) * 0\n  or\n    sum by (group, version, resource) (apiserver_longrunning_requests)\n)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Kube-controller-manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kube-controller-manager CPU usage",
     "type": "graph",
     "description": "Shows the CPU usage of the kube-controller-manager and shows the requests and limits.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{pod=~\"kube-controller-manager-(.+)\"}[$__rate_interval])",
       "legendFormat": "{{pod}}-current"
      },
      {
       "expr": "kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\", pod=~\"kube-controller-manager-(.+)\"}",
       "legendFormat": "{{pod}}-limits"
      },
      {
       "expr": "kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\", pod=~\"kube-controller-manager-(.+)\"}",
       "legendFormat": "{{pod}}-requests"
      }
     ]
    },
    {
     "title": "Kube-controller-manager Memory Usage",
     "type": "graph",
     "description": "Shows the memory usage of the kube-controller-manager.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{pod=~\"kube-controller-manager-(.+)\"}",
       "legendFormat": "{{pod}}-current"
      },
      {
       "expr": "kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\", pod=~\"kube-controller-manager-(.+)\"}",
       "legendFormat": "{{pod}}-limits"
      },
      {
       "expr": "kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\", pod=~\"kube-controller-manager-(.+)\"}",
       "legendFormat": "{{pod}}-requests"
      }
     ]
    },
    {
     "title": "Request Rate to Kube API",
     "type": "graph",
     "description": "The average http request rate of the last 5m executed by the Kube Controller Manager to the cluster API server. The request are split by their response status codes.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(rest_client_requests_total{host=~\".*kube-apiserver.*\", job=\"kube-controller-manager\"}[$__rate_interval])) by(code)",
       "legendFormat": "{{code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kube-scheduler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kube-scheduler CPU usage",
     "type": "graph",
     "description": "Shows the CPU usage of the kube-scheduler and shows the requests and limits.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{pod=~\"kube-scheduler-(.+)\"}[$__rate_interval])",
       "legendFormat": "{{pod}}-current"
      },
      {
       "expr": "kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\", pod=~\"kube-scheduler-(.+)\"}",
       "legendFormat": "{{pod}}-limits"
      },
      {
       "expr": "kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\", pod=~\"kube-scheduler-(.+)\"}",
       "legendFormat": "{{pod}}-requests"
      }
     ]
    },
    {
     "title": "Kube-scheduler Memory Usage",
     "type": "graph",
     "description": "Shows the memory usage of the kube-scheduler.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{pod=~\"kube-scheduler-(.+)\"}",
       "legendFormat": "{{pod}}-current"
      },
      {
       "expr": "kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\", pod=~\"kube-scheduler-(.+)\"}",
       "legendFormat": "{{pod}}-limits"
      },
      {
       "expr": "kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\", pod=~\"kube-scheduler-(.+)\"}",
       "legendFormat": "{{pod}}-requests"
      }
     ]
    },
    {
     "title": "End to End Scheduling Latency Percentile",
     "type": "graph",
     "description": "Shows the 50th, 90th and 99th latency percentile for scheduling in the cluster.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cluster:scheduler_e2e_scheduling_duration_seconds:quantile",
       "legendFormat": "{{quantile}}"
      }
     ]
    },
    {
     "title": "Request Rate to Kube API",
     "type": "graph",
     "description": "The average http request rate of the last 5m executed by the Kube Scheduler to the cluster API server. The request are split by their response status codes.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(rest_client_requests_total{host=~\".*kube-apiserver.*\", job=\"kube-scheduler\"}[$__rate_interval])) by(code)",
       "legendFormat": "{{code}}"
      }
     ]
    }
   ]
  }
 ]
}